### PR TITLE
Mostly this fixes failing unit tests

### PR DESCRIPTION
**Pull request by ankith26**
Mostly deals with the `iconify()` function unittest, #2152

### CODE REVIEW

**Comment by ankith26** [comment]
Previously those unit tests would cycle for a Magical 5000 number.. That was not so consistent while testing across different platforms, particularly the low power ones. This PR makes sure that it waits for 1 second for the event so to happen

**Comment by MyreMylar** [comment]
That seems a lot more sensible.

**Review by MyreMylar — APPROVED** [review]
Thanks for the contribution. Hopefully this will make these tests less likely to fail across more hardware. 

👍 🎉

**Review by illume — APPROVED** [review]
👍

**Pull request merged**
