### PR TITLE
Resolve dead link in setup.py seen by debian users

### LINKED ISSUE #2531: Setup.py refers users to nonexistent help URL
Seen on StackOverflow: https://stackoverflow.com/questions/66692760/im-getting-errors-while-installing-pygame-on-my-chromebook-and-to-make-matters

Debian users are directed to https://www.pygame.org/wiki/CompileDebian, by [this line in setup.py](https://github.com/pygame/pygame/blob/main/setup.py#L53)

But the link doesn't exist.

### PR DESCRIPTION
**Pull request by Pierre-Sassoulas**
Closes #2531 and relates to https://github.com/pygame/pygameweb/issues/113

### CODE REVIEW

**Review by ankith26 — APPROVED** [review]
LGTM! 👍 
Thanks for the PR 🥳

**Review by illume — CHANGES_REQUESTED** [review]
Cool. Thanks for looking into this.

Do you think you could add the Debian one back? Also uncomment those other ones you've added (and we can add wiki pages for them too).

ps. I've added a wiki page for CompileDebian just linking to the CompileUbuntu one for now.

**Comment by Pierre-Sassoulas** [comment]
Thanks for the review, I updated the list.

> (and we can add wiki pages for them too).

I don't know where the wiki code is but let me know if can do that too :)

**Comment by Starbuck5** [comment]
@Pierre-Sassoulas the wiki can be edited on pygame.org like wikipedia, I believe.

https://www.pygame.org/wiki/

But you need an account on pygame.org, and new account creation has been stopped for a while because of spam.

**Review by illume — APPROVED** [review]
👍 🎈 thanks :)

**Pull request merged**
