### PR TITLE
Fix typo in music.rst

### PR DESCRIPTION
**Pull request by winterhazel**
Changed "previoulsy" to "previously"

### CODE REVIEW

**Review by novialriptide — APPROVED** [review]

**Comment by novialriptide** [comment]
Nice fumo profile picture

**Review by hellogaray — APPROVED** [review]
Good eye!

**Review by MightyJosip — APPROVED** [review]
👍

**Review by ankith26 — APPROVED** [review]
LGTM! Thanks for contributing to pygame! :pizza:

**Pull request merged**
