### PR TITLE
Update Vector3 overloaded constructor signature

### PR DESCRIPTION
**Pull request by bydariogamer**
Update the typing of the overloaded constructor of `Vector3` in `buildconfig/pygame-stubs/math.pyi` so it accepts both integer and float numbers.

### CODE REVIEW

**Review by ankith26 — APPROVED** [review]
LGTM! 🥳 
Thanks for the first PR! 👍

**Comment by Starbuck5** [comment]
We had a discussion about this over on discord, but the type hints for Vector2 and Vector3 init are still not correct, and it would be great to get those sorted in this PR.

This is what Ankith said:
Capture

Although I think the first overload case, for `Vector2()` (no args) is covered by the second overload case.

One of the problems is that the old ones use `Optional[stuff]`, which is the same as `Union[None, stuff]`. But Vectors don't take `None`.

**Comment by ankith26** [comment]
> Although I think the first overload case, for `Vector2()` (no args) is covered by the second overload case.
Uhh actually no, the second overload typehint still expects an argument, so we need the no arg overload

**Comment by Starbuck5** [comment]
Is typing `float` the same as `Union[int, float]`, because every int is compatible with float?

**Comment by ankith26** [comment]
Yes, according to some typing PEP, `Union[int, float]` is redundant for `float` because any value that can take float, should also take int without any problems

**Review by Starbuck5 — APPROVED** [review]
Alright, this looks good to me. Thanks for the contribution bydario 👍 

Or should I call you freeduck?

**Pull request merged**
