### PR TITLE
py2 code cleanups + doc updates

### PR DESCRIPTION
**Pull request by ankith26**
Continued from #2833 adding some more fixes

### CODE REVIEW

**Comment by Starbuck5** [comment]
For the pypy ones, have you tested that the problems persist on pypy3? It seems strange they would be labeled as pypy2 issues rather than pypy issues in the first place.

**Comment by ankith26** [comment]
> For the pypy ones, have you tested that the problems persist on pypy3?

Yup I did! And it segfaulted on pypy3 as well. So to clear confusion I updated those test skip doc strings to say that we skip on pypy (v3) as well

**Review by Starbuck5 — APPROVED** [review]
Thanks, looks good.

These all seem nice and straightforward, makes the reviewer in me happy.

**Comment by ankith26** [comment]
@Starbuck5 oh I just realised you reviewed! I pushed some more changes (mostly minor) that clean more py2 references in docs and python code, but now that I see you have already reviewed, I could cherry pick the new commit onto a separate branch if you'd like

**Comment by ankith26** [comment]
@Starbuck5 I have repurposed this PR to do py2 cleanups on python code and docs, and moves the typehint changes this PR does into #2882 along with more fixups for better organisation. Again, sorry for having done these changes after you reviewed because I forgot you had reviewed already, I hope it's fine ;)

**Review by MyreMylar — APPROVED** [review]
LGTM 👍 

I'd rather get these python 2 stripping changes over and done with asap.

**Pull request merged**
