### PR TITLE
Update Sprite.update and sprite Group.update docs

### PR DESCRIPTION
**Pull request by thiagojobson**
Hello,

I forgot to update the docs when I made #1375.

### CODE REVIEW

**Comment by illume** [comment]
Oh. Thanks :)

Would you mind updating the _sprite.pyx as well? We need to keep them in sync now too.

**Comment by thiagojobson** [comment]
Done. Please tell me if it is ok.

This will replace `sprites.py` in the future, right?

**Comment by illume** [comment]
Cool. Thanks!

With the cython stuff it needs to be compiled to C, and the C file committed as well.
```
python3 setup.py cython build
```


I guess it might replace sprite.py in the future. It's a bit of an experiment at the moment.

**Comment by thiagojobson** [comment]
Nice, I didn't know about cython!

**Pull request merged**
