### PR TITLE
Update list of datafiles in generated docs

### PR DESCRIPTION
**Pull request by wxh06**
Added `*.txt` for [`LGPL.txt`](https://github.com/pygame/pygame/blob/main/docs/LGPL.txt) and removed unused `*.gif`.
```python
add_datafiles(data_files, 'pygame/docs/generated',
              ['docs/generated',
                  ['*.html',             # Navigation and help pages
                   '*.txt',              # License text
                   '*.js',               # For doc search
                   ['ref',               # pygame reference
                       ['*.html',        # Reference pages
                        '*.js',          # Comments script
                        '*.json']],      # Comment data
                   ['c_api',             # pygame C API
                       ['*.html']],
                   ['tut',               # Tutorials
                       ['*.html',
                        ['tom',
                            ['*.html',
                             '*.png']]]],
                   ['_static',            # Sphinx added support files
                        ['*.css',
                         '*.png',
                         '*.ico',
                         '*.js']],
                   ['_images',            # Sphinx added reST ".. image::" refs
                        ['*.jpg',
                         '*.png',
                         '*.gif']],
                   ['_sources',           # Used for ref search
                        ['*.txt',
                         ['ref',
                            ['*.txt']]]]]])
```

### CODE REVIEW

**Comment by dr0id** [comment]
Welcome and thanks for the PR.
Maybe you haven't seen it, but I think its a duplicate to #2977 .

**Comment by Grimmys** [comment]
That's not a duplicate for me, there is just a conflict between both.

Mine is for fixing stuff (logos page), this one is just improvement of the files included in the wheels.

Can someone confirm `*.gif*` is not used?
Then I could cherry-pick this change in my PR and this one could be closed.

**Review by Starbuck5 — APPROVED** [review]
Can confirm there aren't any gifs in docs/generated, but there is a txt file.

Thanks for the PR.

**Review by ankith26 — APPROVED** [review]
LGTM! 
Technically this PR is kinda redundant after the docs PR was merged, which added `LGPL.txt` to datafiles, but it's still good because this PR makes it so that all text files are included.
Thanks for the PR 👍 🎉

**Pull request merged**
