### PR TITLE
Pipenv: Fixed incorrect base class comparison (#1997)

### PR DESCRIPTION
**Pull request by jtiai**
Fixes issue #1997 where comparison is made against wrong `Command` class.

### CODE REVIEW

**Comment by MyreMylar** [comment]
Tried this locally on windows and didn't notice it breaking anything, everything still builds as it did before.

Under what circumstances was this causing an error - the issue doesn't make it clear?

**Comment by jtiai** [comment]
Sorry forgot to add original error:
```
When trying to invoke setup.py:
```
$ python setup.py --help
Traceback (most recent call last):
  File "setup.py", line 616, in <module>
    class WinBuildExt(build_ext):
  File "setup.py", line 510, in decorator
    assert issubclass(command, Command)
AssertionError
```

Same error appeared when trying to install pygame from sources.

**Comment by MyreMylar** [comment]
Hmm, I don't get this error on windows as far as I can tell. Perhaps it depends on a specific python version?

**Comment by MyreMylar** [comment]
Added Pipenv to the title so we can find this again if we get any more reports/related issues.

**Pull request merged**
