### PR TITLE
adding unit test for display.gl_get_attribute()

### PR DESCRIPTION
**Pull request by aminouhammou**
I added a unit test for display.gl_get_attribute() by correcting some mistakes in [this previous PR.](https://github.com/pygame/pygame/pull/1975) 
 [Here](https://github.com/pygame/pygame/issues/1746) is the issue related to this unit test.

### CODE REVIEW

**Comment by illume** [comment]
Thanks for this. On my Mac, I get this failure.

```python
FAIL: test_gl_get_attribute (__main__.DisplayModuleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/display_test.py", line 280, in test_gl_get_attribute
    self.assertEqual(pygame.display.gl_get_attribute(pygame.GL_DEPTH_SIZE),24)
AssertionError: 32 != 24

Traceback (most recent call last):
  File "test/display_test.py", line 282, in test_gl_get_attribute
    self.assertEqual(pygame.display.gl_get_attribute(pygame.GL_ACCUM_RED_SIZE),16)
AssertionError: 32 != 16

Traceback (most recent call last):
  File "test/display_test.py", line 283, in test_gl_get_attribute
    self.assertEqual(pygame.display.gl_get_attribute(pygame.GL_ACCUM_GREEN_SIZE),16)
AssertionError: 32 != 16

# continued commenting out tests until line 288


Traceback (most recent call last):
  File "test/display_test.py", line 298, in test_gl_get_attribute
    self.assertEqual(pygame.display.gl_get_attribute(pygame.GL_CONTEXT_RELEASE_BEHAVIOR),1)
pygame.error: OpenGL error: GL_INVALID_ENUM


```

Note this doc from https://wiki.libsdl.org/SDL_GL_SetAttribute

> This function sets the OpenGL attribute attr to value. The requested attributes should be set before creating an OpenGL window. You should use SDL_GL_GetAttribute() to check the values after creating the OpenGL context, since the values obtained can differ from the requested ones. 

This means that setting the attribute is merely a request. So the test can not rely on set actually setting the value for get. Hrmmm... Any ideas? Maybe getting the value first, and then seeing if the get is in (original_value, set_value)?

**Review by illume — CHANGES_REQUESTED** [review]
Try doing the gets after a set_mode call. Try handling that sets are requests, and do not always set the requested value.

**Comment by aminouhammou** [comment]
Hi, I have taken your suggested changes into account and tried to update the unit test. I'm waiting on your feedback :)

**Review by illume — APPROVED** [review]
Thanks!

**Pull request merged**
