### PR TITLE
Add keyword arguments to rect module functions

### PR DESCRIPTION
**Pull request by thiagojobson**
Hey, I started some preliminary work on adding support to kwargs on Rect methods, but I need some insights from you, guys.

For example. what should be the signatures for:

- move
- move_ip
- inflate
- inflate_ip

Those methods expect both `x`  and `y` as args. I think that if we are going to add kwargs to them, they should have a default value, e.g:

```
Rect.move(x=0, y=0)

# so this will be valid
rect.move(x=1)
 
# or even
rect.move() 
```

I added some code on that, please let me know what you guys think :)

Edit: builds are all failing, I added this code just to discuss.

### CODE REVIEW

**Comment by charlesej** [comment]
Adding kwargs to the Rect methods will be very useful. I think, in most cases, defaulting to 0 is what a user would expect.

**Comment by illume** [comment]
- Agreed about 0 being a good default.
- x & y as the argument names are good.

**Comment by illume** [comment]
This is for issue: https://github.com/pygame/pygame/issues/808

**Comment by illume** [comment]
Merging this into a `rect-kwargs` branch to finish it off.

**Pull request merged**
