### PR TITLE
Add docs to the CI-generated wheels

### LINKED ISSUE #2690: Distribute local copy of pygame docs with installs
Currently, you can use the command `python -m pygame.docs` to launch the pygame.org/docs website.

It would be cool if pygame distributions came with their own documentation, and the command launched that instead.

This would help users with poor internet, or users programming without internet, mitigate the impact of website outages, and provide a canonical documentation version for every release.

We can't do this now (easily), because our docs build process only runs on Python 3.6 and above, but once py2.7 and py3.5 support is dropped, this will be possible

### PR DESCRIPTION
**Pull request by Starbuck5**
Closes #2690 

blubberquark said that he thought this used to work, and he's right! https://renesd.blogspot.com/2018/02/pygame-documentation-updates.html

Oh wow I hadn't seen #519. And the fact that local docs are documented in https://www.pygame.org/wiki/FrequentlyAskedQuestions.

### CODE REVIEW

**Review by ankith26 — APPROVED** [review]
This PR is looking good! Nice additions, local docs are sure really useful! 👍 

I went through CI generated wheels and sampled wheels from each configuration, and saw that indeed all wheels have generated html pages, except the sdist wheel which does not have those for some reason, so IG this would need fixing

Also it would be a good idea to have some sort of unit test for testing that the docs exist in the wheels, because we don't want a future regression removing docs in wheels going unnoticed again 😉

**Comment by illume** [comment]
Very good!

Eventually it'd be good to generate these something like how we will do with Cython. Then we could also pin the version of the sphinx dependency to the one that works for us.

**Review by ankith26 — APPROVED** [review]
👍 🥳

**Comment by Starbuck5** [comment]
Damn I messed up my squash and push when I amended the commit to add coauthor info.

Ankith, feel free to mess with it (the commit history) if you want.

**Review by MyreMylar — APPROVED** [review]
LGTM 👍

**Pull request merged**
