### PR TITLE
Tracking SSE2 Optimisations

### PR DESCRIPTION
**Pull request by PurityLake**
Refers to #3358 

- [x] Copy Starbuck's optimization into simd_blitters_sse2.c
- [x] Find a way to use SSE2 Blitters explicitly
- [x] Benchmark SS2E code

This PR will be to track progress in optimising SSE2 Blitters based on Starbuck's AVX optimisations.

Currently have implemented the optimisations for SSE2.

### CODE REVIEW

**Comment by Starbuck5** [comment]
I just tested how to use the SSE blitters on my recent PR. If you say `undef __AVX2__` at the top of simd_blitters_avx2.c, it will compile without the AVX ones so you can test the SSE ones.

**Comment by PurityLake** [comment]
Did some testing with blitting  a surface 10000 times using various `specialflags` when using `Surface.blit`. As mentioned by @Starbuck5  using `#undef __AVX2__` in `simd_blitters_avx2.c` disables AVX2 code and runs SSE2 in it's stread.

Here are the results

**SSE2 without optimisations:**
```
Testing BLEND_RGBA_ADD:
9.718885699985549
Testing BLEND_RGB_ADD:
9.687931499996921
Testing BLEND_RGBA_MULT:
22.63133849998121
Testing BLEND_RGB_MULT:
20.664427600015188
Testing BLEND_RGBA_SUB:
9.188310300000012
Testing BLEND_RGB_SUB:
9.442354999977397
Testing BLEND_RGBA_MAX:
8.739872300007846
Testing BLEND_RGB_MAX:
9.480382699985057
Testing BLEND_RGBA_MIN:
8.817215299990494
Testing BLEND_RGB_MIN:
9.041105799988145
```

**SSE2 with optimisations***
```
Testing BLEND_RGBA_ADD:
6.040507300000172
Testing BLEND_RGB_ADD:
6.040672200004337
Testing BLEND_RGBA_MULT:
6.910767900000792
Testing BLEND_RGB_MULT:
6.879146999999648
Testing BLEND_RGBA_SUB:
5.997558699978981
Testing BLEND_RGB_SUB:
6.124182700004894
Testing BLEND_RGBA_MAX:
6.010527999984333
Testing BLEND_RGB_MAX:
6.077654499997152
Testing BLEND_RGBA_MIN:
6.150629800016759
Testing BLEND_RGB_MIN:
6.141219600016484
```

Code used in testing:
```python
import pygame
from pygame.locals import *
from timeit import Timer
import random

def do_the_blits( item, positions):
    for pos in positions:
        screen.blit(surface, (50,50), special_flags=item)

pygame.init()

width = 800
height = 600

screen = pygame.display.set_mode((width,height))

surface = pygame.image.load("Pygame.png").convert_alpha()

blend_types = {
    "BLEND_RGBA_ADD": BLEND_RGBA_ADD,
    "BLEND_RGB_ADD":  BLEND_RGB_ADD,
    "BLEND_RGBA_MULT": BLEND_RGBA_MULT,
    "BLEND_RGB_MULT":  BLEND_RGB_MULT,
    "BLEND_RGBA_SUB": BLEND_RGBA_SUB,
    "BLEND_RGB_SUB":  BLEND_RGB_SUB,
    "BLEND_RGBA_MAX": BLEND_RGBA_MAX, 
    "BLEND_RGB_MAX":  BLEND_RGB_MAX,
    "BLEND_RGBA_MIN": BLEND_RGBA_MIN, 
    "BLEND_RGB_MIN":  BLEND_RGB_MIN,
}

BLITS_TO_DO = 100000

positions = [(random.randint(0,width-50), random.randint(0,height-50)) for _ in range(BLITS_TO_DO)]

def do_the_blits(item):
    for pos in positions:
        screen.blit(surface, (50,50), special_flags=item)

for key, value in blend_types.items():
    print(f"Testing {key}:")
    print(Timer(lambda: do_the_blits(value)).timeit(number=1))
```

**Comment by Starbuck5** [comment]
PurityLake's test numbers as percentage improvements:
```
Testing BLEND_RGBA_ADD:
46.6817%
Testing BLEND_RGB_ADD:
46.3774%
Testing BLEND_RGBA_MULT:
106.428%
Testing BLEND_RGB_MULT:
100.098%
Testing BLEND_RGBA_SUB:
42.0226%
Testing BLEND_RGB_SUB:
42.6321%
Testing BLEND_RGBA_MAX:
37.0071%
Testing BLEND_RGB_MAX:
44.7986%
Testing BLEND_RGBA_MIN:
35.6309%
Testing BLEND_RGB_MIN:
38.2008%
```

This is better than I was expecting. I'm especially suspicious of the MULT ones though, they seem too good to be true. I'll also see if I can replicate these testing numbers locally.

**Comment by Starbuck5** [comment]
**My Test Data**

I used a 460 x 261 image as my surface basis. 

<details>
<summary>Main (AVX)</summary>

```
Testing BLEND_RGBA_ADD:
1.2763061
Testing BLEND_RGB_ADD:
1.3237208999999996
Testing BLEND_RGBA_MULT:
2.0318178999999996
Testing BLEND_RGB_MULT:
2.0239459
Testing BLEND_RGBA_SUB:
1.2739619999999992
Testing BLEND_RGB_SUB:
1.3502557999999993
Testing BLEND_RGBA_MAX:
1.2691035
Testing BLEND_RGB_MAX:
1.3137679999999996
Testing BLEND_RGBA_MIN:
1.2735774000000006
Testing BLEND_RGB_MIN:
1.2812029000000003
```
</details>

<details>
<summary>Main (SSE)</summary>

```
Testing BLEND_RGBA_ADD:
2.1543634
Testing BLEND_RGB_ADD:
2.2162211999999997
Testing BLEND_RGBA_MULT:
5.3097915
Testing BLEND_RGB_MULT:
5.2853055000000015
Testing BLEND_RGBA_SUB:
2.1399480000000004
Testing BLEND_RGB_SUB:
2.2092721999999974
Testing BLEND_RGBA_MAX:
2.1506679999999996
Testing BLEND_RGB_MAX:
2.1953232000000007
Testing BLEND_RGBA_MIN:
2.1411617000000014
Testing BLEND_RGB_MIN:
2.1961531
```
</details>

<details>
<summary>This PR (SSE)</summary>

```
Testing BLEND_RGBA_ADD:
1.7535319
Testing BLEND_RGB_ADD:
1.8411389000000002
Testing BLEND_RGBA_MULT:
4.414888299999999
Testing BLEND_RGB_MULT:
4.397666000000001
Testing BLEND_RGBA_SUB:
1.7444793
Testing BLEND_RGB_SUB:
1.8644549999999995
Testing BLEND_RGBA_MAX:
1.7534880999999984
Testing BLEND_RGB_MAX:
1.8469790999999987
Testing BLEND_RGBA_MIN:
1.7324574999999989
Testing BLEND_RGB_MIN:
1.8187704999999994
```
</details>

<details>
<summary>Percent improvement in SSE blit mode performance in this PR over main</summary>

```
Testing BLEND_RGBA_ADD:
20.513932397318825%
Testing BLEND_RGB_ADD:
18.48898252831931%
Testing BLEND_RGBA_MULT:
18.40478490613132%
Testing BLEND_RGB_MULT:
18.334031035824083%
Testing BLEND_RGBA_SUB:
20.361750624088153%
Testing BLEND_RGB_SUB:
16.9288311696472%
Testing BLEND_RGBA_MAX:
20.34651739462986%
Testing BLEND_RGB_MAX:
17.234935645461356%
Testing BLEND_RGBA_MIN:
21.10192968890708%
Testing BLEND_RGB_MIN:
18.79899283762215%
```
</details>

In my testing, I see that this PR achieves a 15-20% performance improvement with these blit modes over main (when just using SSE), as expected. I believe @PurityLake forgot to turn AVX2 off for one of their tests.

**Review by Starbuck5 — APPROVED** [review]
This looks good to me, thanks!

**Review by MyreMylar — APPROVED** [review]
LGTM 👍

**Pull request merged**
