### PR TITLE
workaround for average_color due to bug in ppc gcc , update test+types

### PR DESCRIPTION
**Pull request by ankith26**
Tries to put up a workaround for #2875, this most likely a weird compiler bug

Also updates the test to use subtest, and fixes the typehints for the function

### CODE REVIEW

**Comment by stefanor** [comment]
The test still fails under gcc -O3 on ppc64el:
```
======================================================================
FAIL: test_average_color (__main__.TransformModuleTest) [Testing 24-bit surface]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/stefanor/pygame/build/lib.linux-ppc64le-3.9/pygame/tests/transform_test.py", line 951, in test_average_color
    self.assertEqual(pygame.transform.average_color(s), (5, 75, 150, 0))
AssertionError: Tuples differ: (0, 0, 0, 0) != (5, 75, 150, 0)

First differing element 0:
0
5

- (0, 0, 0, 0)
+ (5, 75, 150, 0)

----------------------------------------------------------------------
```

**Comment by ankith26** [comment]
Thanks for helping test this PR! I've skipped the test for now from running on PPC until the compiler bug is resolved :)

**Comment by ankith26** [comment]
Ok I took illume's suggestion from the linked issue to try to not optimise the function with -O3, and hopefully that should do the trick. @stefanor could you please test if this PR fixes the issue now?

**Comment by stefanor** [comment]
The test passes now, thanks!

**Comment by ankith26** [comment]
Haha yaay! Also, thanks to you too for reporting/testing this issue! I believe you are trying to get pygame2 into debian, which is indeed great! 🥳 🎉

**Review by illume — APPROVED** [review]
Thanks :)

**Review by Starbuck5 — APPROVED** [review]
The tests pass here and the tests pass there. Looks good to me.

**Pull request merged**
