### PR TITLE
Fixed rect collision with negative size and image.frombuffer not working with ARGB

### LINKED ISSUE #1198: Rect collision detection incorrect with negative sized rects
**Expected result:** Negative sized rects should detect collisions correctly.
**Actual result:** Negative sized rect collisions are not correctly detected in some cases.

---

```python
import pygame


def test_collisions(rect, other_rect):
    print('Collision testing: {} --> {}'.format(rect, other_rect))

    print('contains:', rect.contains(other_rect))
    print('colliderect:', rect.colliderect(other_rect))

    rect_list = [other_rect]
    print('collidelist:', rect.collidelist(rect_list))
    print('collidelistall:', rect.collidelistall(rect_list))

    rect_dict = {1 : other_rect}
    print('collidedict:', rect.collidedict(rect_dict, 1))
    print('collidedictall:', rect.collidedictall(rect_dict, 1))
    print()


print('-' * 75)
sized_rect = pygame.Rect(0, 0, 10, 10)
neg_rect = pygame.Rect(1, 1, -1, -1)
test_collisions(sized_rect, neg_rect)
test_collisions(neg_rect, sized_rect)

nor_rect = neg_rect.copy()
nor_rect.normalize()
print('normalized {} to {}:'.format(neg_rect, nor_rect))
test_collisions(sized_rect, nor_rect)
test_collisions(nor_rect, sized_rect)

print('-' * 75)
neg_rect = pygame.Rect(2, 2, -1, -1)
test_collisions(sized_rect, neg_rect)
test_collisions(neg_rect, sized_rect)

nor_rect = neg_rect.copy()
nor_rect.normalize()
print('normalized {} to {}:'.format(neg_rect, nor_rect))
test_collisions(sized_rect, nor_rect)
```

---

The above code produces the following output. The first example shows a `rect(1, 1, -1, -1)` not detecting collisions correctly. Once normalized the collisions are detected. The second example shows that the behavior is inconsistent as the `rect(2, 2, -1, -1)` detects collisions correctly.

```
pygame 2.0.0.dev3 (SDL 2.0.9, python 3.7.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
---------------------------------------------------------------------------
Collision testing: <rect(0, 0, 10, 10)> --> <rect(1, 1, -1, -1)>
contains: 1
colliderect: 0
collidelist: -1
collidelistall: []
collidedict: None
collidedictall: []

Collision testing: <rect(1, 1, -1, -1)> --> <rect(0, 0, 10, 10)>
contains: 0
colliderect: 0
collidelist: -1
collidelistall: []
collidedict: None
collidedictall: []

normalized <rect(1, 1, -1, -1)> to <rect(0, 0, 1, 1)>:
Collision testing: <rect(0, 0, 10, 10)> --> <rect(0, 0, 1, 1)>
contains: 1
colliderect: 1
collidelist: 0
collidelistall: [0]
collidedict: (1, <rect(0, 0, 1, 1)>)
collidedictall: [(1, <rect(0, 0, 1, 1)>)]

Collision testing: <rect(0, 0, 1, 1)> --> <rect(0, 0, 10, 10)>
contains: 0
colliderect: 1
collidelist: 0
collidelistall: [0]
collidedict: (1, <rect(0, 0, 10, 10)>)
collidedictall: [(1, <rect(0, 0, 10, 10)>)]

---------------------------------------------------------------------------
Collision testing: <rect(0, 0, 10, 10)> --> <rect(2, 2, -1, -1)>
contains: 1
colliderect: 1
collidelist: 0
collidelistall: [0]
collidedict: (1, <rect(2, 2, -1, -1)>)
collidedictall: [(1, <rect(2, 2, -1, -1)>)]

Collision testing: <rect(2, 2, -1, -1)> --> <rect(0, 0, 10, 10)>
contains: 0
colliderect: 1
collidelist: 0
collidelistall: [0]
collidedict: (1, <rect(0, 0, 10, 10)>)
collidedictall: [(1, <rect(0, 0, 10, 10)>)]

normalized <rect(2, 2, -1, -1)> to <rect(1, 1, 1, 1)>:
Collision testing: <rect(0, 0, 10, 10)> --> <rect(1, 1, 1, 1)>
contains: 1
colliderect: 1
collidelist: 0
collidelistall: [0]
collidedict: (1, <rect(1, 1, 1, 1)>)
collidedictall: [(1, <rect(1, 1, 1, 1)>)]

Collision testing: <rect(1, 1, 1, 1)> --> <rect(0, 0, 10, 10)>
contains: 0
colliderect: 1
collidelist: 0
collidelistall: [0]
collidedict: (1, <rect(0, 0, 10, 10)>)
collidedictall: [(1, <rect(0, 0, 10, 10)>)]

```

---

System details:
- os: windows 10 (64bit)
- python: 3.7.2 (64bit)
- pygame: 2.0.0.dev3 (SDL: 2.0.9) at c8c9e8236cb8ad4178594badb1f29e95ff0c0708

Related to issue #1197.

### LINKED ISSUE #1599: Pycairo demo raises pygame.error: Unknown pixel format
Running [the pygame demo](https://pycairo.readthedocs.io/en/latest/integration.html#pygame-imagesurface) raises `pygame.error: Unknown pixel format`. It seems to work if `"ARGB"` is changed to `"RGBA"` but then the channels are in the wrong order. [This seemed to be working in pygame 1.9.6.](https://github.com/pygobject/pycairo/issues/177)

### PR DESCRIPTION
**Pull request by MightyJosip**
This should fix #1198 (I modified collision function to compare "normalized" values of the rect).

This should also fix #1599 (I don't really know why does this work, but I just copied values from from fromstring method (and that method is working fine))

### CODE REVIEW

**Comment by illume** [comment]
This is the error...
```
======================================================================
FAIL: test_collidedictall__negative_sized_rects (pygame.tests.rect_test.RectTypeTest)
Ensures collidedictall works correctly with negative sized rects.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\pygame\tests\rect_test.py", line 1851, in test_collidedictall__negative_sized_rects
    self._assertCountEqual(collide_items, expected_items)
  File "C:\Python27\lib\site-packages\pygame\tests\rect_test.py", line 18, in _assertCountEqual
    self.assertItemsEqual(*args, **kwargs)
AssertionError: Element counts were not equal:
First has 1, Second has 0:  ('no collide 1', <rect(1, 1, 20, 20)>)
----------------------------------------------------------------------
Ran 139 tests in 0.008s
FAILED (failures=1)
```

**Comment by MightyJosip** [comment]
In my opinion this is the problem with the test (they should collide, but the test wants that they don't collide)

**Comment by charlesej** [comment]
Yes, there is a problem with the test. In `test_collidedictall__negative_sized_rects()`, the line:

`no_collide_item1 = ("no collide 1", Rect(1, 1, 20, 20))`

should be:

`no_collide_item1 = ("no collide 1", Rect(2, 2, 20, 20))`

**Comment by MightyJosip** [comment]
Shouldn't it also collide (because both Rects share pixel (2, 2)). I think that we should test with Rect(3, 3, 20, 20), because that is the first rect that shouldn't collide with Rect(2, 2, -2, -2)

**Comment by charlesej** [comment]
When `Rect(2, 2, -2, -2)` is normalized it becomes `Rect(0, 0, 2, 2)`, which covers (0, 0), (0, 1), (1, 0) and (1, 1).

**Pull request merged**
