### PR TITLE
Added time.get_ticks() tests & increase error deltas for other time module tests

### PR DESCRIPTION
**Pull request by Gogotchuri**
Implemented correct return-type assertion and ensuring correct time gaps for each call to get_ticks().

### CODE REVIEW

**Comment by MyreMylar** [comment]
Looks good to me. Though I think we may need to increase the delta for all these timing tests as we've had one build fail on appveyor here:

https://ci.appveyor.com/project/pygame/pygame/builds/33224276/job/2epwec92vadmopcm#L4046

with this output:

    ======================================================================
    FAIL: test_delay (pygame.tests.time_test.TimeModuleTest)
    Tests time.delay() function.
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "C:\Python35\lib\site-packages\pygame\tests\time_test.py", line 145, in test_delay
        self._wait_delay_check(pygame.time.delay, millis, iterations, delta)
      File "C:\Python35\lib\site-packages\pygame\tests\time_test.py", line 203, in _wait_delay_check
        self.assertAlmostEqual(wait_time, millis, delta=delta)
    AssertionError: 52 != 50 within 1 delta
    ======================================================================
    FAIL: test_wait (pygame.tests.time_test.TimeModuleTest)
    Tests time.wait() function.
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "C:\Python35\lib\site-packages\pygame\tests\time_test.py", line 186, in test_wait
        self._wait_delay_check(pygame.time.wait, millis, iterations, delta)
      File "C:\Python35\lib\site-packages\pygame\tests\time_test.py", line 203, in _wait_delay_check
        self.assertAlmostEqual(wait_time, millis, delta=delta)
    AssertionError: 75 != 50 within 5 delta
    ----------------------------------------------------------------------

Perhaps we should be assuming time.delay is under 5ms accuracy and time.wait() can be more like 50ms? Definitely useful information to find out! And each time the CI builds run we'll gather more data.

**Comment by illume** [comment]
I'm temporarily disabling the time tests in this PR for the release: https://github.com/pygame/pygame/pull/1882

**Comment by Gogotchuri** [comment]
So, I underestimated delta values. I will increase them to 50ms for time.wait() and to 5ms for time.delay(), as you suggested. I think those should be a big enough error margin to pass every test and also to make sure that functionality is correct. I will make another commit to this branch with changed values in all 3 tests. Really appreciate your feedback, thanks for helping.

**Comment by Gogotchuri** [comment]
Thanks for your approval. I hope, my contributions were helpful. Trying to get into open source and planning to contribute more.

**Comment by MyreMylar** [comment]
> Looks good. I think the new deltas should be enough that the tests won't fail, but I suppose we shall find out over time.

Hah, just saw one appveyor build fail with a difference of 88 milliseconds on the slow test so it looks like I was too optimistic as to that function's accuracy.

**Pull request merged**
