### PR TITLE
Fixed wrong kwargs types in sprite.pyi

### LINKED ISSUE #2650: Wrong kwargs typing
In some places such as
https://github.com/pygame/pygame/blob/94f906242d5bb5b2804cab9935b03af3d9357177/buildconfig/pygame-stubs/sprite.pyi#L81
the annotations for `kwargs` have the wrong types. They should be `Any` and not `Dict[str, Any]`, as the annotation should be of the elements of `kwargs` (see https://adamj.eu/tech/2021/05/11/python-type-hints-args-and-kwargs/).

### PR DESCRIPTION
**Pull request by sandipanpanda**
This pull request fixes #2650. Fixed wrong kwargs types in lines 81, 83, and 102 of [sprite.pyi](https://github.com/pygame/pygame/blob/main/buildconfig/pygame-stubs/sprite.pyi)

### CODE REVIEW

**Review by ankith26 — APPROVED** [review]
LGTM! 🥳 👍 
Thanks for your first PR!

**Comment by sandipanpanda** [comment]
Thank you @ankith26 for reviewing and approving my pull request. I am delighted to have contributed to pygame.
This was my first contribution to a open source project on python! :partying_face: I am super excited to contribute more to the community. :nerd_face:

**Review by Starbuck5 — APPROVED** [review]
Thanks.

The python 3.5 test failure seems like a random failure, especially since the only files changed were type stubs.

I poked around some of the code, and LayeredUpdates.add() only takes 1 kwarg, 'layer', and doesn't pass through the rest to anywhere else. So that should probably be turned into a default argument, rather than just leaving it "kwargs". But that's out of the scope of this PR, I think.

**Comment by ankith26** [comment]
Probably yea, out of scope for the PR. But this PR is good to go, and imma merge it now

**Pull request merged**
