### PR TITLE
Use custom SDL2_ttf on Windows

### PR DESCRIPTION
**Pull request by Starbuck5**
Potential solution for #3144 

I have built my own DLLs of SDL_ttf and uploaded them to Github for easy download. This eliminates the segfaulting seen in #3144.

Obviously we don't usually use versions of our dependencies between releases, but I say we should go for it this time. SDL_ttf 2.0.15 is very dated at this point, and it would be a pain to roll back the buildconfig changes I needed to make to upgrade to SDL_ttf 2.0.18.

### CODE REVIEW

**Review by ankith26 — APPROVED** [review]
Generally I'd be against using dev releases of our deps in a release, but I think it's fine for this time. Considering the bug this is fixing has a pretty large impact, this PR should definitely go by this release, or we should revert to 2.0.15 if any other reviewer does not like this PR (which might be tedious but oh well)

**Comment by ankith26** [comment]
On the topic of this PR... might be worth making this a unit test to test the fix for now, and also make sure it does not regress in the upcoming SDL stable versions

**Comment by illume** [comment]
I wonder how simple it is to build SDL_ttf on CI?

I'm a little uneasy releasing with new custom built libraries, and am thinking we maybe rollback until we automate the building of the custom SDL_ttf etc.

**Comment by Starbuck5** [comment]
I understand the concern about custom libraries.

It took me a long time to do this manually in Visual Studio, and there was no command line involved, so I'm not sure where to even start trying to automate this.

I don't want to rollback because of all the cool features I'd like to use from SDL_ttf 2.0.18 (harfbuzz font support for much better support for non-latin languages, support for setting font direction, a multiline text rendering API). Also much better emoji support, including full color emoji.

The SDL_ttf team fixed the issue on their end, it was a compiler bug in an older version of Mingw. (Yes, even their VS DLLs are made with Mingw apparently).

Anyways, I'd like to use this for the next pygame dev release, and we can see whether any problems pop up for our beta testers. I haven't had any problems locally with this, but it's always get to testing on lots of systems.

**Comment by illume** [comment]
Ah ok. I was afraid it would be complex.

Seems SDL folks are working on a new SDL_image release, and so I guess also a SDL_ttf will come in time too. Not sure if we should wait for those before a real release though(could be months). Yeah, ok... I guess a dev release can happen with this one.

**Comment by illume** [comment]
Would it be possible to add the test case, so we can make sure we're not regressing when the new SDL_ttf comes out?

**Comment by Starbuck5** [comment]
Done. Had to force push because I forgot to format.

**Comment by Starbuck5** [comment]
Ok, not the formatting one is failing on a piece of code I didn't touch at all. Did clang format change?

**Review by illume — APPROVED** [review]
Thanks for supplying the build, and also for adding the unit test too.

🎉🎈

**Pull request merged**
