### PR TITLE
Manylinux dependency upgrades, SDL 2.0.16 and more

### PR DESCRIPTION
**Pull request by illume**
Various dependency upgrades for manylinux, and new base images with all of them already compiled (including for arm64).

- [x] Add SDL 2.0.16 (see [SDL 2.0.16 post](https://discourse.libsdl.org/t/sdl-2-0-16-released/32471/2))
- [x] SDL_image, SDL_ttf, and SDL_mixer have not had releases, so no upgrades this time either. 
- [x] libogg-1.3.5, libvorbis-1.3.7
- [x] couldn't upgrade pulse audio, because of a build failure
- [x] new pypy "pypy2.7-v7.3.5-linux32" and "pypy3.7-v7.3.5-linux32". They dropped 3.6 support, which means we do too.
- [x] mpg123-1.28.2 (see [mpg123 news](https://www.mpg123.de/cgi-bin/news.cgi))
- [x] libwebp-1.2.1 from libwebp-1.1.0 (see [libwebp changelog](https://github.com/webmproject/libwebp/blob/master/ChangeLog))
- [x] freetype-2.11.0 from freetype-2.10.1 (see [free type release news](https://www.freetype.org/))
- [x] fluidsynth wasn't updated because of a lack of time. It's still on a 1.x release, and there have been MANY 2.x releases even. This would be a good one to upgrade later, but requires more testing.

### CODE REVIEW

**Comment by ankith26** [comment]
This PR looks good! 👍 
On another, related note, can we add 3.10rc1 into the manylinux build system, that would help with testing

**Comment by illume** [comment]
@ankith26 seems that python 3.10.0rc1 is broken in manylinux2010. I guess we'll have to wait until another python release candidate. Maybe in some weeks. https://github.com/pypa/manylinux/pull/1159

**Comment by ankith26** [comment]
Yeah, that should be fine

**Review by Starbuck5 — APPROVED** [review]
I'm certainly not an expert in this, but this looks good and straightforward to me, and the tests pass.

It's cool to see the march of technology in action with all the dependency updates. 😄

**Review by ankith26 — APPROVED** [review]
Looks good to go! 🥳 🎈 
Nice work on this! 👍

**Pull request merged**
