### PR TITLE
some wrong relative imports in cython code

### PR DESCRIPTION
**Pull request by pmp-p**
```
>>> pygame._sdl2.sdl2.error is pygame._sdl2.controller.error
True
```

but pygame._sdl2.error is an alias ( from sdl2 import * ) in  pygame._sdl2 package
```
>>> pygame._sdl2.error
<class 'pygame._sdl2.sdl2.error'>
```

### CODE REVIEW

**Review by ankith26 — COMMENTED** [review]
When making cython changes, you also need to push the generated c code you get after doing a `python3 setup.py cython`

**Comment by pmp-p** [comment]
thanks, yes i will but i think there are other circular imports around

**Comment by pmp-p** [comment]
@ankith26 should be ok now, in wasm I was able to do C multiphase init from the statically linked libraries. Maybe WebAssembly dynamic loading will be possible soon.

**Review by ankith26 — APPROVED** [review]
I've not tested this PR, but the code looks fine.

Thanks for the PR 🚀

**Review by MyreMylar — APPROVED** [review]
LGTM 👍

**Pull request merged**
