### PR TITLE
Added relative mouse motion support to video.Window

### PR DESCRIPTION
**Pull request by mcpalmer1980**
Added simple setter and getter to pygame.src_c/cython/pygame/_sdl2/video.pyx
The new property is pygame._sdl2.video.Window.relative_mouse
Simply calls SDL_GetRelativeMouseMode and SDL_SetRelativeMouseMode
Compiled to video.c

solves #2390

### CODE REVIEW

**Review by illume — APPROVED** [review]
👍 thanks!

**Comment by mcpalmer1980** [comment]
I don't understand anything in the LGTM C analysis details, and I'm not sure if the c changes should be included in PR or just the pyx changes.

**Comment by illume** [comment]
The LGTM failure seems to be a robot-brainfart on its part - nothing to worry about.

**Comment by illume** [comment]
Looking at this again, it's not really a Window feature. But more a mouse feature.

I'll merge it in to unblock you, but in time the API will change. Also, perhaps the display versions should be fixed to work with Window. Will leave the issue open so it can be investigated still.

**Pull request merged**
