### PR TITLE
Update and sync `SDL_mixer` and `SDL_ttf` to 2.6.2 and 2.20.1 respectively

### PR DESCRIPTION
**Pull request by ankith26**
for #3430

In this PR I'm taking on only two of the four things we have to update (to make reviewing easier)

The `SDL_ttf` bump is pretty straightforward on both windows and mac/manylinux, the bulk of this PR is for the `SDL_mixer`

I fixed the windows buildconfig to accomodate for the fact that `SDL_mixer` 2.6+ has lesser DLLs, and some of the DLLs have also moved into a nested `optional` directory. This means that #3287 introduces a regression in music loading for some music formats like opus and the many formats handled by modplug (which this PR fixes)

On the mac/manylinux front: 
`libflac`, `mpg123` and `ogg/vorbis` are not used directly by `SDL_mixer` by default anymore. `SDL_mixer` prefers vendored copies of alternate implementations.
I also noticed while testing that trying to load `opus` music fails on linux (but works on windows), and I realised this is because we missed a dependency `opusfile` even though we have `libopus` around. `opusfile` depends on `libopus` and also `libogg` for loading music from files.

### Testing

I tested this PR on Windows and Ubuntu (WSL), I used the `playmus` example to test start/stop/pause/rewind etc on as many music formats as I could easily find

- flac
- mp3
- ogg
- wav
- mid (midi file format, handled by fluidsynth, timidity or SDL "nativemidi")
- opus
- xm (one of the many formats handled by modplug)

On windows all of these work. On linux I got all of these except `mid` working out of the box. I later found out that midi needs more config from the user side, as the SDL_mixer docs mention:
> If you have built with FluidSynth support, you'll need to set the SDL_SOUNDFONTS environment variable to a Sound Font 2 (.sf2) file containing the musical instruments you want to use for MIDI playback. (On some Linux distributions you can install the fluid-soundfont-gm package)
> To play MIDI files using Timidity, you'll need to get a complete set of GUS patches from: [timidity.tar.gz](https://www.libsdl.org/projects/mixer/timidity/timidity.tar.gz) and unpack them in /usr/local/lib under UNIX, and C:\ under Win32.

Which I suppose is up to the user to choose which of these they want to use at runtime. This may need documenting and more testing, but is out of scope of this PR

I've also tested a few font examples and applications, and I did not see any regressions due to the `SDL_ttf` update.

I've not tested this PR on macs because of not having hardware, but I would appreciate it if this PR is reviewed and tested by a mac user too

### To discuss

The latest commit in this PR is put up for discussion, and can be reverted without breaking anything, if needed

- [x] Should we still be compiling `libflac`, `mpg123` and `vorbis`? **yes**
- [x] If yes, should we also use that backend instead of the `SDL_mixer` vendored alternate implementation? **yes**

### CODE REVIEW

**Comment by illume** [comment]
> Should we still be compiling libflac, mpg123 and vorbis?

The smallest change is to leave them in there for now. I think once we have some more experience with them keeping their vendored stuff up to date we can switch to the vendored libraries.

Can you remove that commit? 

(I reran the failing ubuntu job because it had unrelated apt-get issues.)

**Review by illume — APPROVED** [review]
🎉 thanks for doing this.

**Comment by ankith26** [comment]
> The smallest change is to leave them in there for now. I think once we have some more experience with them keeping their vendored stuff up to date we can switch to the vendored libraries.

I'm also fine with continuing to stick with the existing ones (considering libflac and libmpg123 are still being updated and maintained rn), but there's also the thing that these alternate libraries will be used on windows and this may be problematic for inter-platform consistency later. Music related bugs on windows would have a higher chance of not being reproducible on macs/linux, and vice-versa.

There's also an issue of the increasing wheelsize on manylinux due to all the recent updates, and doing this may slightly increase wheelsize (just a hunch, untested). However I've got another WIP branch with some promising results, if that works then the current increase would be quite insignificant even if it is a thing.

I will move the latest commit into a separate branch for archiving, and change the `configure` flags for `SDL_mixer` if the minor inter-platform inconsistency is okay.

**Comment by illume** [comment]
> I'm also fine with continuing to stick with the existing ones (considering libflac and libmpg123 are still being updated and maintained rn), but there's also the thing that these alternate libraries will be used on windows and this may be problematic for inter-platform consistency later. Music related bugs on windows would have a higher chance of not being reproducible on macs/linux, and vice-versa.

Good point. I wonder about cross version compatibility as well.

>I will move the latest commit into a separate branch for archiving, and change the configure flags for SDL_mixer if the minor inter-platform inconsistency is okay.

Ok, let's look into this later.

**Review by illume — APPROVED** [review]
🎉 thanks :)

**Pull request merged**
