### PR TITLE
Polygon large coordinate test cases for issue#3989

### PR DESCRIPTION
**Pull request by u7156704**
Issue: #3989 
I was unable to bug fix the large coordinate polygon issue, but was able to write test cases if someone wanted to fix this issue.
I also manage to narrow down the problem for large negative y-axis points for polygons are producing the bug.
I was unsure if this was a memory issue with the larger integers or something affecting the y-axis point value.
The test cases in draw_test.py should assist in fixing this issue.

### CODE REVIEW

**Comment by u7156704** [comment]
PyObject * Polygon (lines 775 – 890)
Draw_fillPoly (lines 2322 - 2428)

This functions in src_c/draw_c is a good starting place to fix this bug from my findings

**Comment by illume** [comment]
Nice one! 🎉

Some notes...

- You can mark the test with `@unittest.expectedFailure `  This way the test runners succeed. It means "we know this one will fail".
- There's something weird with the first commit. Maybe try creating a new branch from main and copy the code in? First delete your local branch, then create a new branch with the same name off main, finally copy your code in and make a new commit.

**Comment by u7156704** [comment]
I manage to change the test cases to include @unittest.expectedFailure, however I couldn't manage to fix the build. If someone could try fix it for me, I can create a new issue to extend based of the issue and this PR.

**Comment by illume** [comment]
Hi,

you can see the test failures on the github actions by clicking on the checks.
I've pasted the failure below.


It might be better to put just one expectedFailure decorator on the whole test.

```
@unittest.expectedFailure
def test_polygon_large_coords(self):
```



```
======================================================================
FAIL: test_polygon_large_coords (pygame.tests.draw_test.DrawPolygonTest.test_polygon_large_coords)
Ensures draw polygon works correctly with large points.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python312\Lib\site-packages\pygame\tests\draw_test.py", line 4339, in test_polygon_large_coords
    extreme_x_pass(self)
  File "C:\Python312\Lib\site-packages\pygame\tests\draw_test.py", line 4314, in extreme_x_pass
    self.assertEqual(surface.get_at((600, 600)), white)
AssertionError: (0, 255, 0, 255) != (0, 0, 0, 255)
----------------------------------------------------------------------
Ran 217 tests in 4.557s
```

**Comment by u7156704** [comment]
I can divide the larger test case into two separate but similar functions, one for expected passing tests and one for expecting failing tests. The way it was written to test different shapes to ensure the bug does occur and is properly fixed, leading to a larger quantity of tests, but I can try simplify it down or comment out some test cases.

**Comment by u7156704** [comment]
I've commented out of the tests, for a future issue

**Comment by illume** [comment]
Ok. Let me know if you want some help continuing this?

**Comment by u7156704** [comment]
I believe commenting out the code was the main solution, as the required checks pass now. This would probably be the best way at the moment while the bug exists. I recon if this PR get approved, I'll reference this PR and the previous issue in a new issue that addresses the bug more directly with the commented out code as test cases for it

**Comment by illume** [comment]
> I believe commenting out the code was the main solution

Good point.

**Review by illume — APPROVED** [review]
thanks 🎈🎉

**Pull request merged**
