### PR TITLE
Fixes scrap on Windows.

### PR DESCRIPTION
**Pull request by Starbuck5**
**Why was it broken?**

The way to grab a window HWND changed in SDL2.
Also I don't think the compiler liked that the HWND was named SDL_Window, which is now a type name.

Additionally, the order of the `#includes` at the top meant that PY_SSIZE_T_CLEAN wasn't defined properly before python was included, which meant every call to `scrap.put` was printing a deprecation warning. To fix this, I also changed `scraplen` in `scrap.c` to a `Py_ssize_t` as requested. I don't believe this will affect Python 2.7 compatibility because the PEP for this, 353, was implemented in 2.5.

**Other scrap stuff:**

I couldn't get scrap building on my mac, even for pygame 1.9.6. Whatever I do `pygame.scrap` is `MissingModule`.

### CODE REVIEW

**Comment by robertpfeiffer** [comment]
Does this PR actually link the platform-specific scrap module again on windows instead of the sdl2-based clipboard shim?

**Comment by Starbuck5** [comment]
Yes, it does. I changed the “if SDL2” to “if SDL2 and not Windows”

I wasn’t sure if I should though, because this will make it more inconsistent across platforms.

**Comment by Starbuck5** [comment]
I should also mention the main issue tracking scrap, #1178.

**Comment by robertpfeiffer** [comment]
Shouldn't your PR also touch the Setup_Win or Setup_SDL2 files?

**Comment by Starbuck5** [comment]
I don't think the Setup_Win file was changed when you added the SDL2 text compatibility shim. `scrap_win.c` just wasn't being included in `scrap.c`.

It seems like it should, but it built fine on my computer. I don't think the specific platform module being included needs to be explicitly set in one of the Setup files... it doesn't do that on mac either.

**Review by illume — APPROVED** [review]
👍 Nice one @Starbuck5

**Pull request merged**
