### PR TITLE
Added unit test for threads.tmap(), unsurfaced bug #1768

### PR DESCRIPTION
**Pull request by cruxicheiros**
**Issue:** #1768 

**Background:** `threads.tmap()` was missing unit tests, so I wrote a unit test to cover the situation where the optional parameter `stop_on_error` is set to `False`. The purpose of `stop_on_error` is to determine whether `tmap` should return a result or throw an error if one or more of the function calls it makes throw exceptions.

**Description:** As part of my unit test's setup, it calls `tmap` with the `stop_on_error` flag set to `False`. However, an exception is thrown by `tmap` during this process because the resulting `FuncResult`s don't have the `result` attribute they are expected to.

**Caveats:** The actual form of the unit test may need to change depending on how the issue preventing it from running is resolved. It needs to be determined what the actual correct result should be in order to write the unit test.

Finally, this is the **stack trace** I got before.
```
Error
Traceback (most recent call last):
  File "/home/clark/miniconda3/envs/pygamenv/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/home/clark/miniconda3/envs/pygamenv/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/home/clark/miniconda3/envs/pygamenv/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/clark/Dev/pygame/pygame/test/threads_test.py", line 136, in test_tmap
    tmapped2 = list(tmap(always_excepts, data2, stop_on_error=False))
  File "/home/clark/miniconda3/envs/pygamenv/lib/python3.8/site-packages/pygame/threads/__init__.py", line 308, in <lambda>
    return map(lambda x:x.result, results)
AttributeError: 'FuncResult' object has no attribute 'result'


Assertion failed

Assertion failed


Ran 1 test in 0.036s

FAILED (errors=1)
```

This is my first PR to this project, so let me know if I have made mistakes in formatting it or if you need more information. Thanks!

### CODE REVIEW

**Comment by cruxicheiros** [comment]
Looks like the same thing has happened in the travis build, which at least is good for reproducibility 

```
======================================================================

ERROR: test_tmap (pygame.tests.threads_test.ThreadsModuleTest)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/opt/python/cp38-cp38/lib/python3.8/site-packages/pygame/tests/threads_test.py", line 136, in test_tmap

    tmapped2 = list(tmap(always_excepts, data2, stop_on_error=False))

  File "/opt/python/cp38-cp38/lib/python3.8/site-packages/pygame/threads/__init__.py", line 308, in <lambda>

    return map(lambda x:x.result, results)

AttributeError: 'FuncResult' object has no attribute 'result'

----------------------------------------------------------------------

Ran 1478 tests in 22.190s

FAILED (errors=1)

Makefile:4: recipe for target
```

**Comment by MyreMylar** [comment]
I guess we need to resolve the issue with tmap before anything can be done with this unit test.

**Comment by cruxicheiros** [comment]
Yeah, that's what I think. Should I switch this to a draft and make a new issue?

**Comment by MyreMylar** [comment]
> Yeah, that's what I think. Should I switch this to a draft and make a new issue?

Sounds sensible to me.

**Comment by cruxicheiros** [comment]
@MyreMylar Here: #1985

**Comment by cruxicheiros** [comment]
Modified tmap per issue #1985

**Comment by MyreMylar** [comment]
Cool.

Are you intending to look at the unfinished unit test that starts with `todo` in this PR? This one:

https://github.com/pygame/pygame/blob/7d3900d5b04dc8102f218cc60f3fbf5e06dd8fa1/test/threads_test.py#L131-L143

No worries if you are not.

**Comment by cruxicheiros** [comment]
I actually hadn't noticed it and assumed that the main tmap test was the one that was unfinished. I wanted to add further tests to the main tmap test and I can have a look at the existing todo when I do that.

**Comment by illume** [comment]
I think we can merge this one in now. Further work on tmap tests can happen in other PRs.

**Review by illume — APPROVED** [review]
Thanks :)

**Pull request merged**
