### PR TITLE
fixed segfault

### PR DESCRIPTION
**Pull request by oddbookworm**
Fixes https://github.com/pygame/pygame/issues/3665 by raising a `ValueError` if the surface access is after closing the `PixelArray`

### CODE REVIEW

**Review by Matiiss — CHANGES_REQUESTED** [review]
I'm fairly certain it would be important to add this check to other places where it hasn't been added:
https://github.com/pygame/pygame/blob/25aac95a17ea925567046440e655f5e577d47506/src_c/pixelarray.c#L432-L438

and I'm not sure about this but if `shape` also gets set to NULL (even if that doesn't happen, I suppose these should then still check if `self->surface == NULL`):
https://github.com/pygame/pygame/blob/25aac95a17ea925567046440e655f5e577d47506/src_c/pixelarray.c#L443-L450
https://github.com/pygame/pygame/blob/25aac95a17ea925567046440e655f5e577d47506/src_c/pixelarray.c#L455-L462
https://github.com/pygame/pygame/blob/25aac95a17ea925567046440e655f5e577d47506/src_c/pixelarray.c#L467-L471

And I'm fairly certain there are a couple more functions that need this check, perhaps, also in `pixelarray_methods.c`

**Comment by MyreMylar** [comment]
From my testing these are the PixelArray public functions and members that segfault after a first call to `.close()`:

- `.surface`
- `.itemsize`
- `.close()` - a second call to it.
- `transpose()`

The others already say:

```
ValueError: Operation on closed PixelArray.
```

Or return some valid data. I didn't bother testing all the dunder methods because this is already a fairly dumb thing for somebody to be doing.

**Review by MyreMylar — CHANGES_REQUESTED** [review]
Please add a similar check to clear the other segfaults outlined above.

**Review by MyreMylar — APPROVED** [review]
LGTM 👍

**Comment by Starbuck5** [comment]
This looks reasonable to me, thanks Andrew!

**Review by Starbuck5 — APPROVED** [review]

**Pull request merged**
