### PR TITLE
Add deprecation warning when draw.aaline is called with blend=False

### PR DESCRIPTION
**Pull request by zoldalma999**
#592 [old pr](https://github.com/pygame/pygame/pull/2162)

### CODE REVIEW

**Comment by MyreMylar** [comment]
Should link the general discussion issue on these:

https://github.com/pygame/pygame/issues/2197

My final verdict on DeprecationWarnings is that we should start using them from 2.0.0 onwards, they don't spam, there are options to filter them if the user doesn't care at all and it is better for us to provide feedback before changing any APIs. Since the focus post 2.0.0 is slightly less on compatibility with the past, and more on useful features to catch pygame up with the modern world DeprecationWarnings seem like a useful tool in that box.

I won't approve this for now in case everyone else is against, but I'm for them in general and I think the way it's done in this PR is a good method.

**Review by Starbuck5 — APPROVED** [review]
Nobody seems to have come out against deprecation warnings, and it has been a while.
These changes look good to me.

**Comment by Starbuck5** [comment]
@illume - I think this is ready to merge.

After merging this I was thinking it would good to open an issue that reminds us to actually deprecate this and `set_system_cursor()` by 2.2.

**Review by illume — APPROVED** [review]
Thanks :)

**Comment by illume** [comment]
Thanks @Starbuck5 . I created an issue here: https://github.com/pygame/pygame/issues/2405 with the milestone 2.2.

**Pull request merged**
