### PR TITLE
[WIP] Android changes

### PR DESCRIPTION
**Pull request by robertpfeiffer**
EDIT: I tagged a version that worked well enough and pinned that in the kivy/pythonforandroid pygame build recipe.
In order to understand what's going on here, look at: 
https://github.com/pygame/python-for-android

### CODE REVIEW

**Comment by illume** [comment]
Very cool. I see you already made PRs for some bits of this like the keyboard events in https://github.com/pygame/pygame/pull/1584

**Comment by robertpfeiffer** [comment]
Yeah. Posting keyboard events is kind of crucial if you want to make your own on-screen keyboard.

**Comment by robertpfeiffer** [comment]
The snapshot I tagged is now part of the recipe that has been merged into the official kivy pythonforandroid.

To do (short-term): 
- [ ] merge master into this
- [ ] merge event handling code into master
- [ ] Update our fork of P4A to point back to this android development branch
- [ ] Add an example game with touch controls

**Comment by illume** [comment]
The setup.py stuff can be done in a separate PR. https://github.com/pygame/pygame/issues/727

**Pull request closed without merging**
