### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by Thunderborne**
Capitalized some proper names, e.g. "Pygame," "Python," and "GitHub" for consistency

### CODE REVIEW

**Comment by illume** [comment]
hi. I keep pygame as all lower because the package is lower case, and it's an error to `Import PyGame`.

**Comment by Thunderborne** [comment]
> hi. I keep pygame as all lower because the package is lower case, and it's an error to `Import PyGame`.

Oh I see. Thank you very much for the feedback!

**Comment by illume** [comment]
> Oh I see. Thank you very much for the feedback!

Thank you for your understanding. Do you want to update it with the other changes (GitHub and Python)?

**Comment by Thunderborne** [comment]
> Thank you for your understanding. Do you want to update it with the other changes (GitHub and Python)?

Definitely. Thank you. This is my first time trying to contribute to a FOSS project so thank you for the review. I went ahead and changed back "Pygame" to "pygame" in the README.rst.

**Review by illume — APPROVED** [review]
🎉🎈 great, thank you

**Pull request merged**
