### PR TITLE
added a FRect object

### PR DESCRIPTION
**Pull request by Emc2356**
created a new object that is similar to pygame.Rect but instead of using integers pygame.FRect uses floats

### CODE REVIEW

**Comment by Starbuck5** [comment]
This is related to #3007, but uses floats instead of python numbers.

It looks like there aren't any tests, so I'm not sure how compliant this is with the Rect api.

Perhaps it would be better to do FRect in a different C file, since there doesn't seem to be much code overlap. (So just save the future readers from ginormous files). Alternatively, is there a way to share more code between implementations? Like a bootleg C++ template system in C with macros or something?

If we're going to do it this way, I'd like it to be based on SDL_FRect. I know there aren't docs, but you can check the SDL source (Rect.h header would have it?). And if version added is a concern, you can use `#ifndef` right?

**Comment by novialriptide** [comment]
Any reason why Pygame.Rect isn't turned into FRect?

**Comment by Starbuck5** [comment]
> Any reason why pygame.Rect isn't turned into FRect?

Backwards compatibility.

**Comment by mcpalmer1980** [comment]
As I suggested earlier, I like this idea of a separate FRect that won't effect any legacy code. Users could either add FRects were necessary (sdl2.video drawing/scaling) and use Rects everywhere else. Or, if they prefer, they can add something like import FRect as Rect to make it global.

**Pull request closed without merging**
