### PR TITLE
Deletion of Group if Group has no references besides members

### PR DESCRIPTION
**Pull request by FirTreeMan**
Toggle behavior for new Groups with `AbstractGroup.terminate_if_unref` (defaults to disabled).

### CODE REVIEW

**Comment by illume** [comment]
Very cool.

ps. I wrote in the other PR... but will repeat some of it here in case you missed it.

In my humble opinion... we need to do two types of testing first before deciding if it should be optional:

1. add some unit tests
2. test with some older games to see if they're still working

**Comment by illume** [comment]
The test failure is saying it needs the `black` code formatter run on it.

```
python -m pip install black --user
python -m black src_py
```

**Comment by FirTreeMan** [comment]
New commit is black formatted.

**Comment by illume** [comment]
This https://github.com/pygame/pygame/issues/3763 is done now.

**Pull request closed without merging**
