### PR TITLE
Added unit test for the surface.lock() function

### PR DESCRIPTION
**Pull request by 41aaronb**
I added in a unit test for the surface.lock() function, I think it is good to go but review would be appreciated.

### CODE REVIEW

**Comment by robertpfeiffer** [comment]
Based on the current behaviour of SDL2, this test case does nothing except increasing metrics of coverage.

**Comment by robertpfeiffer** [comment]
On further reflection, we can go ahead and merge this, I'll open another issue for surface locking.

**Comment by 41aaronb** [comment]
Hey guys, wondering how we can actually get this merged, let me know if there's anything more I need to do!

**Comment by MyreMylar** [comment]
> Hey guys, wondering how we can actually get this merged, let me know if there's anything more I need to do!

Nothing more for you to do, we just generally leave issues open for a little while so everyone with an interest can have a chance to look at it and comment.

It's approved now so it'll probably get merged in a batch with a bunch of other issues in a few days.

Thanks again for the contribution!

**Pull request merged**
