### PR TITLE
Add upscaled logos to /docs, edit logos.html

### PR DESCRIPTION
**Pull request by Mega-JC**
PR for https://github.com/pygame/pygame/issues/2701.

The `logos.html` file was restructured to allow the new logos to be incorporated, with the legacy logos moved to the bottom.

### CODE REVIEW

**Comment by Starbuck5** [comment]
Thanks, this looks cool.

Some notes: 
- it would be good to get the logo in the README changed for higher quality as well. I made a test branch to play around with that: https://github.com/Starbuck5/pygame/tree/test-logo
- The docs README should probably use a relative path, instead of absolute. See https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-readmes#relative-links-and-image-paths-in-readme-files
- Rather than having two different sized images under the name `pygame_logo`, you could rename the new ones to `pygame_large`? It would fit the scheme of the other ones. Maybe `pygame_powered_large` for that one, and `pygame_colors` for the other one?
- pygame_logo2 and pygame_logo.svg/png both could be cropped tighter. I noticed the excess space on the bottom in the README changing test branch.

Also I have some doubts about whether the logo page gets included in the website in general, due to a change that put all the Sphinx generated in a folder named `generated/`, but that isn't your fault and is a fix for later.

**Comment by Just-JC** [comment]
Ah, I had overlooked the `README` but it should now be updated. I also managed to update some other things such as the `.ico` image shown in the browser.

**Review by ankith26 — APPROVED** [review]
The README and the docs html page looks neat after the upscale, nice work on the PR Mega! 👍 🥳

**Comment by Starbuck5** [comment]
More notes:

- The ico looks beautiful in finder, but I find it looks work in the actual browser environment. (Probably because it's so downscaled). I faced the same issue trying to make the pygame default window logo look better.
- pygame_tiny.png is your work, I think, it looks quite a bit better than pygame_tiny.gif. I don't like that they're easily confused. (It took me a while to track down all the moving parts). Maybe legacy logos should just be downloadable zip file containing the old ones, and you can show off your better looking ones (of all sizes) as the official logos? Or they could be named differently, like the changes I suggested earlier.

**Comment by Starbuck5** [comment]
Ok, I think this PR has gotten too large. I'd appreciate doing all the .ico stuff in a separate PR, so this one is easier to merge.

Because right now, it's just a docs thing, and with those changes, it touches PyInstaller builds, the website, the default pygame icon for every single window (will that respond differently on different OS?), etc.

Also do you want to add your version of pygame_tiny to the logos page as a first class logo?

**Comment by Mega-JC** [comment]
> Ok, I think this PR has gotten too large. I'd appreciate doing all the .ico stuff in a separate PR, so this one is easier to merge.
Alright, I will move those into a separate PR, I didn't mean to overwhelm the reviewers. :D

> Also do you want to add your version of pygame_tiny to the logos page as a first class logo?
I thought it might be good to update it as well, since I also noticed jagged edges and a white outline. However it can be left out if it is not noticable enough.

**Comment by Starbuck5** [comment]
> I thought it might be good to update it as well, since I also noticed jagged edges and a white outline. However it can be left out if it is not noticable enough.

I thought you already updated it. There were two different pygame_tiny variants, which were different sizes and proportions and everything.

**Comment by Mega-JC** [comment]
> > I thought it might be good to update it as well, since I also noticed jagged edges and a white outline. However it can be left out if it is not noticable enough.
> 
> I thought you already updated it. There were two different pygame_tiny variants, which were different sizes and proportions and everything.

Oh, yes I updated them, one was `pygame_tiny.gif`, which is now in `legacy_logos.zip` along with all the other `.gif` logos, like you suggested earlier. The current versions of `pygame_tiny` are both identical, and in `.png` format.

**Comment by Starbuck5** [comment]
This is really close to done! I was going to approve it, but I noticed it still has the new favicon .ico in the docs, which should be removed.

Also, I think it would be good to have pygame_tiny as an official logo in logos.html, but I'll merge without that.

**Comment by Mega-JC** [comment]
> This is really close to done! I was going to approve it, but I noticed it still has the new favicon .ico in the docs, which should be removed.
> 
> Also, I think it would be good to have pygame_tiny as an official logo in logos.html, but I'll merge without that.

All done and completed 👍

**Review by Starbuck5 — APPROVED** [review]
Thanks! The logo in the README looks gorgeous now. The pixelated holes in the controller on the old one were bothering me.

**Pull request merged**
