### PR TITLE
buildconfig: Bump SDL version to 2.24.0 on windows

### PR DESCRIPTION
**Pull request by illume**
For https://github.com/pygame/pygame/issues/3430

### CODE REVIEW

**Comment by ankith26** [comment]
I built this branch locally, and I could reproduce the CI segfault only when I set `SDL_VIDEODRIVER="dummy"` (like the CI)

Then I ran the tests with the python `-X dev` option which gave a traceback pointing me to the line in python code where it is happening, and it is this

https://github.com/pygame/pygame/blob/7e6f48306f624debac9cb2731bb9adc5a762a5c6/test/display_test.py#L563-L565

Turns out, the issue is because of the `pygame.SCALED` usage (if I remove it, there is no segfault on that line, but in a later line where again - `SCALED` is used)

**Comment by illume** [comment]
Thanks for tracking down the issue.

**shakes fist at SCALED**

What do you think about 2.1.3 without this SDL 2.24.0? There's undoubtedly bug fixes in it I guess. But we can always try again with 2.1.4... hopefully sooner. If we go with SDL 2.24.0, I'd like to do another dev release with it for at least another week. That's why I'm leaning towards going with what we have now.

**Comment by ankith26** [comment]
I'm fine with postponing this PR to 2.1.4 and not having to do more dev
releases. Also given our manylinux SDL situation (where we are still stuck
on 2.0.20), having windows on 2.0.22 seems fine for this release (too much
divergence is probably not good, but is one version difference acceptable?)

Been experimenting with compiling Wayland support in, but I doubt it could
help much for this specific issue, given sdl still defaults to x11 if it's
available (and xwayland usually is these days, when older xlib one is
missing)

**Comment by illume** [comment]
@ankith26 What's the issue with 2.0.22 on linux/macos? 

The tests seem to pass: PR for 2.0.22 on manylinux... https://github.com/pygame/pygame/pull/3475

ps. oops. I forgot we were still on 2.0.20 on manylinux. I think probably we should go with that on manylinux/macos.

**Comment by ankith26** [comment]
Oh, I had mentioned the issue I faced earlier on [here](https://github.com/pygame/pygame/issues/3430#issuecomment-1229813334)

I didn't see any failing tests locally either, but somehow runtime performance is massively impacted

**Comment by illume** [comment]
> runtime performance is massively impacted

I'm thinking we still do a 2.1.3.dev8 release with 2.0.22 on mac/linux. Probably we can have a note about known issues, and for people to use 2.1.3.dev6 in the meantime.

Then the following:
- [ ] make an SDL performance on WSL reduced issue
- [ ] make wayland issue, and try and get wayland working
- [ ] make a SCALED with 2.24.0 on windows issue

By the way, Wayland has always been at least 50% of the speed for me even without X involved. A lot is to do with them copying the image data twice. The rest is less optimized graphics drivers.

**Comment by ankith26** [comment]
> make wayland issue, and try and get wayland working

There is already an issue open for it here #2529

> I'm thinking we still do a 2.1.3.dev8 release with 2.0.22 on mac/linux. Probably we can have a note about known issues, and for people to use 2.1.3.dev6 in the meantime.

Yeah, this seems like a good idea. I just found out (thanks @avaxar for testing this) that 2.0.22 works aight on a real linux machine (running latest linux mint) and is infact, faster that 2.1.2 by a significiant margin (tested the `testsprite` example)

*screams at WSL* 😩

**Comment by ankith26** [comment]
Hrmmm, this PR fixes one known issue to me already. BTW I have tracked down the test fail from here and made an SDL bug report (this bug is already fixed on `main` and set to make its way to SDL 2.26.0, and if the SDL devs agree this fix may also be backported to a 2.24.2)

**Pull request merged**
