### PR TITLE
Add srcrect NULL check to pgSurface_Blit

### PR DESCRIPTION
**Pull request by MyreMylar**
For @itzpr3d4t0r to cherry pick.

### CODE REVIEW

**Comment by ankith26** [comment]
What do we do about this PR?
Can we merge this one into main?

**Comment by MyreMylar** [comment]
> What do we do about this PR? Can we merge this one into main?

Sure. I think it's pretty harmless. 

Basically `SDL_BlitSurface()` and `pygame_Blit()` let srcrect be NULL happily but a helper function (surface_do_overlap()) used as an old optimisation in this wrapper around those two functions is assuming `srcrect` is a valid dereferenceable pointer always. With this change if `srcrect` is NULL we don't go down that branch so `pgSurface_Blit()` also becomes safe to call with `srcrect` as NULL.

**Review by ankith26 — APPROVED** [review]
I did not test this locally, but the logic and explanation seems clear and simple. Thanks for the PR 🎉

**Review by zoldalma999 — APPROVED** [review]
Thanks!

**Pull request merged**
