### PR TITLE
SDL2: Compile on Windows

### PR DESCRIPTION
**Pull request by dlon**
Had to make this change to compile (using MSVC) with SDL2. I also had to replace the #warning directives, but I'm not sure whether I should add that patch.

### CODE REVIEW

**Comment by illume** [comment]
Cool, thanks :)

I guess we'll need to:
- use a portable warning macro. https://stackoverflow.com/questions/171435/portability-of-warning-preprocessor-directive
- or, comment out those warnings.

I think it's more important to have windows compiling than have the warnings appear at the moment.

So... let's comment out the warnings until someone has time to make a warning macro?

**Comment by illume** [comment]
There's a section on the wiki for how to compile ubuntu and mac with sdl2.

So probably we also need to add a section on the wiki with instructions here:
https://www.pygame.org/wiki/CompileWindows

**Comment by dlon** [comment]
Maybe [this](https://stackoverflow.com/a/11244789/1239986) for the warning macro?

```c
#define PG_STRINGIZE_HELPER(x) #x
#define PG_STRINGIZE(x) PG_STRINGIZE_HELPER(x)
#define PG_WARN(desc) message(__FILE__ "(" PG_STRINGIZE(__LINE__) "): WARNING: " #desc)
```

**Comment by illume** [comment]
Nice one :)

**Pull request merged**
