### PR TITLE
Update stars.py

### PR DESCRIPTION
**Pull request by jonozw**
add pg.quit() to exit gracefully

### CODE REVIEW

**Review by zaphodikus — APPROVED** [review]
font_viewer example could do with the same cleanliness fix if someone does not mind fixing other places with the same omission.

**Review by ankith26 — APPROVED** [review]
Well technically `pg.quit()` is redundant, because python automatically calls it on exit conditions.
But an explicit `pg.quit()` is also fine
So this PR has no problems it may be merged 👍

**Comment by ankith26** [comment]
Close and open to restart CI

**Review by Starbuck5 — APPROVED** [review]
As @zaphodikus says, there are others that are missing the pg.quit(), which is mainly important for IDLE-friendliness.

Maybe those can be compiled in an issue, which would be a good first issue.

But this is a good contribution, that's been waiting since April, so let's merge it.

**Comment by AnudeepGunukula** [comment]
Hi i have made a pull request #2643 which will solve this freezing issue, 
i have added pg.quit() to the examples in necessary places for idle friendliness
I have tested in python IDLE and visual studio as well, its working perfect now.
Please review my pr guys, thanks in advance.

**Pull request merged**
