### PR TITLE
Fix playmus.py example (broken in 2.0.1)

### PR DESCRIPTION
**Pull request by rethanon**
This PR is to fix an issue with the bundled example file playmus.py which stopped working correctly as of pygame 2.0.1 due to a change in returning False for `pygame.mixer.music.get_busy()` when music is paused (previously returned True).

Also tidied up the wording a little bit and fixed a typo.

Issue was raised [#2734 ](https://github.com/pygame/pygame/issues/2734)

### CODE REVIEW

**Review by Starbuck5 — APPROVED** [review]
Thanks, this is great! 

Think it would be prettier with some different colors? The blue on white isn't the prettiest on the eyes.

**Comment by Starbuck5** [comment]
If I play a .wav I can't rewind, but if I play a .mp3 I can?

Also another thing I've found that isn't ideal- you can't close the window when in a paused state.

**Comment by rethanon** [comment]
Thanks I'll resubmit with updated color scheme and I've fixed the being able to quit when a track is paused. I'll have a look at not being able to rewind a wav but I'm getting the same, could be a deeper issue causing that one.

**Comment by rethanon** [comment]
@Starbuck5 I checked the SDL_Mixer docs and it states rewind only works for MOD, OGG, MP3, and Native MIDI. Their website seems to indicate the latest version of SDL_Mixer is version 2.0.4 yet the docs don't appear to have been updated since 2009 (they refer to SDL_mixer version 1.2.10, dated November 2009!)

**Comment by Starbuck5** [comment]
Thanks for all the investigation! The SDL_Mixer docs are old but it has a very stable interface throughout the years. However, sometimes you have to dig into the SDL_Mixer source directly to see how things fit together. Maybe we should add a note that WAV doesn't support rewind to the mixer.music docs.

**Comment by rethanon** [comment]
@Starbuck5 I've fixed this so that playmus.py will use rewind for MOD, MP3 and WAV files, and for anything else will restart (using `pygame.mixer.music.play()`. SDL_mixer docs say Native MIDI files are supported but I can't seem to find what this means. I tested with a standard `.mid` file and rewind wasn't working for that so I thought it better to just use rewind for the 3 main file types.

I had a go at updating the docs for `pygame.musix.mixer.rewind()` but I still have that issue where I can't build the docs locally to test them so could you check them as well please?

**Comment by Starbuck5** [comment]
> I still have that issue where I can't build the docs locally to test them so could you check them as well please?

That's because you're using an old version of main, from like August.

**Comment by rethanon** [comment]
> > I still have that issue where I can't build the docs locally to test them so could you check them as well please?
> 
> That's because you're using an old version of main, from like August.

Ah yeah, I was able to check the docs built correctly on my Mac machine instead.

**Comment by rethanon** [comment]
Closing this so I can rebase code and will then raise a new PR

**Pull request closed without merging**
