### PR TITLE
Adding unit test to iconify

### PR DESCRIPTION
**Pull request by zoldalma999**
#1749

### CODE REVIEW

**Comment by zoldalma999** [comment]
Im sorry it took me so long. I made the changes.
Is there a way to test sdl 1 versions? I tried looking for it but couldnt find one.
Also should i open an issue about the event/docs?

**Comment by MyreMylar** [comment]
> Im sorry it took me so long. I made the changes.

No worries at all, we probably wouldn't notice unless you vanished for longer than a month :)

> Is there a way to test sdl 1 versions? I tried looking for it but couldn't find one.

Yes. There is an SDL 1 build that runs on Travis which should now be labelled as such, but if I recall this test only runs locally so you would need to build pygame with the SDL 1 build configuration. For me the process of switching SDL versions goes something like this:

```
python setup.py clean --all
python -m buildconfig -sdl1
python setup.py install
pip install . -U
```

But the exact commands you use may depend on how you build python modules/pygame normally and your platform (if you've not built pygame from source yet you may also want to have a look at the [wiki documentation for different platforms](https://www.pygame.org/wiki/Compilation) e.g. here are the windows instructions: https://www.pygame.org/wiki/CompileWindows - which I know from experience can be tricky )

> Also should i open an issue about the event/docs?

You can if you like, or I'll do it myself at some point when this PR gets wrapped up.

**Comment by MyreMylar** [comment]
Remaining work for me:

- [ ] Add issue to add WINDOWEVENT_MINIMIZED as a constant to pygame in the same way we have WINDOWEVENT_CLOSE.
- [ ]  Add issue to update the documentation for pygame 2 to indicate the event now generated by iconify()/minimizing in general under SDL2.
- [ ] double check this test works locally on windows & raspberry pi.

**Review by illume — APPROVED** [review]
Thanks. 🎉  

I think we can merge this in now. I moved the TODO list to the issue.

**Pull request merged**
