### PR TITLE
Close a ``subprocess.Popen`` automatically by using a context (and other pylint 2.9 lint fixes)

### PR DESCRIPTION
**Pull request by Pierre-Sassoulas**
The main thing is the with used with subprocess, which help make sure the subprocess is closed, I included a number of small fixes too as to not open 5 obnoxious merge requests.

### CODE REVIEW

**Comment by Pierre-Sassoulas** [comment]
Turn out popen is not a context manager in all target python version, so it was a false positive.

**Review by ankith26 — APPROVED** [review]
LGTM! Thanks 👍 🥳

**Review by Starbuck5 — APPROVED** [review]
Looks good to me as well. I hope we will actually be able to merge, now that Travis is down (it's still marked as required).

**Comment by Pierre-Sassoulas** [comment]
If you have no more check to do on Travis, you can remove Travis from the required status check in Github's settings / branches / then click "edit" on the "main" branch's protection rules. I had this problem when removing Travis and Appveyor a month or so ago. I had to do 10 mn of research right now for this comment even though I knew it was possible to do, and approximately where 😄

**Pull request merged**
