### PR TITLE
_sdl2: Regenerate cython c files with 3.0.0.rc2

### PR DESCRIPTION
**Pull request by illume**

### CODE REVIEW

**Comment by illume** [comment]
Reported the pypy 3.9 on cython issue here: https://github.com/cython/cython/issues/5529

**Comment by mattip** [comment]
Cibuildwheel build is using an old version of PyPy 3.9, from more than a year ago. See also https://foss.heptapod.net/pypy/pypy/-/issues/3955. Can you update cibuildwheel to a newer version?

**Comment by illume** [comment]
Thanks mattip. Using a newer manylinux image works fine.

**Comment by mattip** [comment]
Cool. Although I don't see where it got changed, I am glad it is now working. Please feel free to ping me directly for PyPy problems.

**Comment by illume** [comment]
> Cool. Although I don't see where it got changed, I am glad it is now working. 

We’re using a manylinux container image with some things on top that ci build wheel pulls. The base layer hadn’t been updated in a while though. So now we have the new base layer and up to date pypy.

> Please feel free to ping me directly for PyPy problems.

Will do. Thanks again.

**Pull request merged**
