### PR TITLE
Remove unittest skip from freetype_Font_render_to_mono

### LINKED ISSUE #859: SDL2: freetype test failures
```
..............F...F.........F..............
======================================================================
FAIL: test_freetype_Font_render_mono (test.freetype_test.FreeTypeFontTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\David\Documents\dev\pygame\test\freetype_test.py", line 744, in test_freetype_Font_render_mono
    self.assertEqual(surf.get_alpha(), translucent_color.a)
AssertionError: None != 55

======================================================================
FAIL: test_freetype_Font_render_to_mono (test.freetype_test.FreeTypeFontTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\David\Documents\dev\pygame\test\freetype_test.py", line 804, in test_freetype_Font_render_to_mono
    self.assertEqual(surf.get_at(bottomright), r_fg_color)
AssertionError: (30, 23, 50, 255) != (30, 22, 49, 253)

======================================================================
FAIL: test_issue_144 (test.freetype_test.FreeTypeFontTest)
Issue #144: unable to render text
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\David\Documents\dev\pygame\test\freetype_test.py", line 1273, in test_issue_144
    self.assertRaises(pygame.error, font.render, s, (0, 0, 0))
AssertionError: error not raised by render

----------------------------------------------------------------------
Ran 43 tests in 3.325s

FAILED (failures=3)
```

**Related Docs:** 

https://www.pygame.org/docs/ref/freetype.html
https://www.pygame.org/docs/ref/surface.html#pygame.Surface.blit

### PR DESCRIPTION
**Pull request by zoldalma999**
Either this should pass or #864 should be reopened. Also if this passes then it should fix #859

### CODE REVIEW

**Review by illume — APPROVED** [review]
Oh good! Thanks 👍

**Comment by zoldalma999** [comment]
Since Freetype tests dont run on CI i will run the tests locally on windows with multiple python versions(probably tomorrow).

**Comment by MyreMylar** [comment]
> Since Freetype tests don't run on CI I will run the tests locally on windows with multiple python versions(probably tomorrow).

I ran the blending test locally (on windows with python 3.9) and it passed, though bizarrely a refcounting one fails:

```
======================================================================
FAIL: test_garbage_collection (__main__.FreeTypeFontTest)
Check reference counting on returned new references
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\dan\Programming\pygame\test\freetype_test.py", line 1654, in test_garbage_collection
    self.assertEqual(getrefcount(item), 2, "refcount fail for item %d" % i)
AssertionError: 4 != 2 : refcount fail for item 0

----------------------------------------------------------------------
```

Dunno what that is about (not connected to this PR).

**Comment by zoldalma999** [comment]
Running it on 2.7.17, 3.5.4, 3.6.8 and 3.7.7 got the same results as MyreMylar (test_garbage_collection fails, everything else passes)

**Comment by illume** [comment]
I'll merge this one in (thanks!) and create an issue for this refcounting thingo :)

**Pull request merged**
