### PR TITLE
WIP: Try and get unicode field working for keydown.

### PR DESCRIPTION
**Pull request by illume**
For https://github.com/pygame/pygame/issues/621

test case:

See if the keydown event has the appropriate text in the `unicode` field(Also try modifiers like shift). If a key on the keyboard is pressed then there should be an `a` in the `unicode` field of the keydown event.
```
python3 -m pygame.examples.eventlist
```

TODO: does `unicode` field work on?
- [x]  Linux X11
- [x] Windows

(Also removes a compiler warning: https://github.com/pygame/pygame/issues/1316)

### CODE REVIEW

**Comment by dlon** [comment]
Is it safe to assume that SDL_TEXTINPUT will be filtered before SDL_KEYDOWN is processed?

**Comment by illume** [comment]
Have you seen this happen? On my Mac I bashed at my keyboard, and couldn't get this happening.
I haven't tried on Windows, Ubuntu, etc yet.

**Comment by illume** [comment]
Ah, I think I understand now. I guess you can get KEYBOARD events separately from TEXTINPUT events from the queue too. This would mess things up as well.

**Comment by MyreMylar** [comment]
I'm seeing sporadic blank unicode fields on KEYDOWN events in 2.0.0.dev4 on Windows. Sample output of me pounding the 'h' key a handful of times:

`Key code h unicode type: <class 'str'> contents: h
Key code h unicode type: <class 'str'> contents: 
Key code h unicode type: <class 'str'> contents: h
Key code h unicode type: <class 'str'> contents: 
Key code h unicode type: <class 'str'> contents: 
Key code h unicode type: <class 'str'> contents: 
Key code h unicode type: <class 'str'> contents: 
Key code h unicode type: <class 'str'> contents: h`

I didn't get this before in Windows on dev3.

**Pull request merged**
