### PR TITLE
Fixed inconsistency in `tp_name`s, changed all to `pygame.module.Type`

### PR DESCRIPTION
**Pull request by Matiiss**
May fix https://github.com/pygame/pygame/issues/3483

### CODE REVIEW

**Review by ankith26 — COMMENTED** [review]
This is definitely improving things, thanks!

But you didn't cover all places, there's `freetype.Font`, some bufferproxy and newbuffer code too that needs changes like this.

**Comment by Matiiss** [comment]
@ankith26 About those some places, they seem to have some constants in place, for example, in `bufferproxy.c` there's `PROXY_TYPE_FULLNAME`(https://github.com/pygame/pygame/blob/main/src_c/bufferproxy.c#L528), would I just replace that with `"pygame.bufferproxy.BufferProxy"` or rather change the definition of `PROXY_TYPE_FULLNAME` (to the previously mentioned string (guess it's an array in C)): https://github.com/pygame/pygame/blob/main/src_c/bufferproxy.c#L48?

Such constants are also in place for `key.c`, `newbuffer.c` and `_freetype.c`
image

**Comment by ankith26** [comment]
I think for consistency, it's better if we use strings directly everywhere. There's no need to have a macro constant that is only used in one place

**Comment by Matiiss** [comment]
So, should I remove all `FULLNAME` constants (their definitions) from the code too?

**Comment by Matiiss** [comment]
Should I use `"pygame._freetype.Font"` or `"pygame.freetype.Font"` because it's in `_freetype.c` but from a practical standpoint I don't think anyone's going to search for that module using an underscore

**Comment by ankith26** [comment]
> So, should I remove all `FULLNAME` constants (their definitions) from the code too?

If nothing else needs it, I'd say yes; go ahead.

> Should I use "pygame._freetype.Font" or "pygame.freetype.Font" because it's in _freetype.c but from a practical standpoint I don't think anyone's going to search for that module using an underscore

Hmm, that's a tough one and TBH I'm not sure either. This is not just limited to freetype, but also things like `Surface` (where most people generally use the `pygame.Surface` alias but the actual implementation is in `pygame.surface.Surface`)

**Comment by Matiiss** [comment]
Well, `pydoc` seems able to find the docs for `Surface` in both cases: `pydoc pygame.Surface` and `pygame.surface.Surface`

**Comment by Matiiss** [comment]
And I will need to revert that commit, right?

**Comment by Starbuck5** [comment]
The build failure is fixed on main now, so you can pull that change in by rebasing or merging main back into your branch.

**Comment by MyreMylar** [comment]
Looks like the type checking CI is failing here:

```
error: pygame.event.EventType is not present in stub
Stub: in file /home/runner/work/pygame/pygame/buildconfig/stubs/pygame/event.pyi
MISSING
Runtime:
<class 'pygame.event.Event'>

error: pygame.rect.RectType is not present in stub
Stub: in file /home/runner/work/pygame/pygame/buildconfig/stubs/pygame/rect.pyi
MISSING
Runtime:
<class 'pygame.rect.Rect'>

Found 2 errors (checked [21](https://github.com/pygame/pygame/actions/runs/3359828731/jobs/5568287362#step:6:22)1 modules)
```

I assume it is related to these type name changes.

**Comment by Matiiss** [comment]
@MyreMylar I noticed it failing but wasn't (still am not) sure what to do exactly, since it didn't fail anywhere else. So, do I just also change the type stub files to include the full names?

**Comment by MyreMylar** [comment]
> @MyreMylar I noticed it failing but wasn't (still am not) sure what to do exactly, since it didn't fail anywhere else. So, do I just also change the type stub files to include the full names? At least in those two files.

That particular CI build is specifically for checking the type stubs so it always tends to fail on its own when something is messed up with the stubs.

If you look at the bottom of `surface.pyi` here:

https://github.com/pygame/pygame/blob/9532f679c8563c952f009d8be4f7fc0483a7cc35/buildconfig/stubs/pygame/surface.pyi#L148

I believe that is the approach you'll need to take for Event and Rect. Could be wrong though.

**Review by MyreMylar — APPROVED** [review]
LGTM 👍

**Review by Starbuck5 — APPROVED** [review]

**Comment by Starbuck5** [comment]
Thanks Matt!

**Pull request merged**
