### PR TITLE
Run the teyit lint tool on our unittests for consistency + latest black version linting updates

### PR DESCRIPTION
**Pull request by ankith26**
While scrolling through the python 3.12 notes I came across a mention of this tool that helps make unit tests more consistent. By making use of `unittest` API instead of pure python equivalents, we get better error reports for failing tests.

### CODE REVIEW

**Comment by MyreMylar** [comment]
This is failing because teyit requires python 3.9 and the version of ubuntu out linter CI uses is on python 3.8.

**Comment by ankith26** [comment]
Good catch. I'm now wondering whether teyit should be a part of `setup.py lint/format` or if it should be an external standalone thing.

Probably updating this teyit test to run on ubuntu 22.04 instead of 20.04 will fix the CI fail

**Comment by MyreMylar** [comment]
> Good catch. I'm now wondering whether teyit should be a part of `setup.py lint/format` or if it should be an external standalone thing.
> 
> Probably updating this teyit test to run on ubuntu 22.04 instead of 20.04 will fix the CI fail

I think we should just update the linting test runner to ubuntu 22.04. I'll make a simple PR for that.

**Comment by MyreMylar** [comment]
Related:
https://github.com/pygame/pygame/pull/3689

**Comment by MyreMylar** [comment]
Toggling this to re-run teyint with maybe upgraded main? May need to merge this branch with main to actually pick up that update.

**Comment by MyreMylar** [comment]
Hooray, looks like this worked. 

Now we just need to fix all the issues with the tests.

**Review by MyreMylar — APPROVED** [review]
OK. All changes I added here are just from running the latest black & pylint on the code and now teyit works too 👍

**Pull request closed without merging**
