### PR TITLE
Fix Solarwolf menu and RLE bug.

### PR DESCRIPTION
**Pull request by dlon**
See: #721.

This makes Solarwolf look right, but it disables RLE in too many cases. I think it should also be available if Amask=0 and a color key is set, but this screws up the blitting.

How to test it: In Solarwolf, press enter for any menu item, then go back. The buttons will be rendered incorrectly.

Edit: It's probably worth figuring out why it fails.

### CODE REVIEW

**Comment by illume** [comment]
Yeah, I think this needs a unit test so we can check it's fixed on different platforms. I guess based off the code @dlon wrote in https://github.com/pygame/pygame/issues/721#issuecomment-459548722

**Comment by illume** [comment]
Hrmm... it doesn't seem to fix it for me.

**Comment by dlon** [comment]
Disabling RLE entirely probably fixes it, but I guess that's no solution.

**Comment by illume** [comment]
Closing this to keep our PR list tidy.

**Pull request closed without merging**
