### PR TITLE
colordict.py is missing a few CSS standard colors #2850

### PR DESCRIPTION
**Pull request by GustavoQuintero99**
Added the missing css colors requested on the #2850 also added them into the color_list_rst (can undo if needed)

### CODE REVIEW

**Comment by Starbuck5** [comment]
Thanks for this.

I don’t think purple should be changed though, because it would change the output of people’s existing programs.

**Comment by GustavoQuintero99** [comment]
Sure, it was suggested on the issue, that's why I changed it, should I put back the original color?

**Comment by Starbuck5** [comment]
Yes, please put back the original color.

**Review by ankith26 — APPROVED** [review]
LGTM! Thanks for the PR! 🎉 

PS: It might be worth adding a note somewhere in the docs stating that these new colours were added in pygame version `2.1.1`

**Review by Starbuck5 — APPROVED** [review]
LGTM, thanks.

I'm not sure how this would get a note in the docs, but it should be okay without, it's pretty minor. Definitely a note in the release notes though.

**Pull request merged**
