### PR TITLE
2.1.3

### PR DESCRIPTION
**Pull request by illume**
2.1.4.dev1 has started (see https://github.com/pygame/pygame/pull/3514)

### CODE REVIEW

**Comment by MyreMylar** [comment]
The trove classifier for 3.11 just needs adding under here:

https://github.com/pygame/pygame/blob/9532f679c8563c952f009d8be4f7fc0483a7cc35/setup.py#L46

Also grabbing that memory leak fix in #3532 might be nice.

**Comment by Starbuck5** [comment]
Sorry y'all, I tried to fix a merge conflict so that CI on this branch would continue building, so we could get wheels with high priority changes (classifier fix, memory leak fix).

I didn't think through that fixing the merge conflict through the web interface meant merging main back into this branch. And it doesn't look like reverting the merge commit got rid of the changes :/

2.1.3 being in an unreleased state puts us in a very difficult position
- Because to continue adding to this branch it needs to continue to be merge conflict free against main, or the build will fail
- We can't target this PR to another branch or else CI won't run at all

@illume The best option right now looks like releasing the wheels as generated at the beginning of this branch, in the 2.1.3 PR.

**Comment by Starbuck5** [comment]
Oh! This is actually fine.

The diff expanded because merging this PR into the current main would overwrite the new changes in main, which makes perfect sense.

**Comment by illume** [comment]
Nobody please don't touch this branch again. I'll handle it. Thanks.

**Comment by oddbookworm** [comment]
As more and more people start using Python 3.11, more and more people are having trouble installing it because they don't know about installing prereleases. Any update on the 2.1.3 release?

**Comment by yudonglin** [comment]
> As more and more people start using Python 3.11, more and more people are having trouble installing pygame because they don't know about installing prereleases. Any update on the 2.1.3 release?

https://github.com/deepmind/mujoco/issues/607#issuecomment-1334572028

**Comment by oddbookworm** [comment]
> [deepmind/mujoco#607 (comment)](https://github.com/deepmind/mujoco/issues/607#issuecomment-1334572028)

I'm not quite sure what this has to do with my question? I was asking about the pygame 2.1.3 release, not the mujoco 2.3.1 release

**Comment by yudonglin** [comment]
> > [deepmind/mujoco#607 (comment)](https://github.com/deepmind/mujoco/issues/607#issuecomment-1334572028)
> 
> I'm not quite sure what this has to do with my question? I was asking about the pygame 2.1.3 release, not the mujoco 2.3.1 release

shoot my bad, but as #71 has been merged, I assume they are waiting for python 3.11.1, as some stuff may often break after the first major patch.

**Comment by Darqon96** [comment]
Hello, does anyone know approximate release date for 2.1.3? Will it support Python 3.11?

**Comment by MyreMylar** [comment]
> Hello, does anyone know approximate release date for 2.1.3? Will it support Python 3.11?

You can get a 3.11 supporting pygame right now using 2.1.3.dev8. Install it from pip with `pip install pygame --pre --U`

**Comment by Darqon96** [comment]
> > Hello, does anyone know approximate release date for 2.1.3? Will it support Python 3.11?
> 
> You can get a 3.11 supporting pygame right now using 2.1.3.dev8. Install it from pip with `pip install pygame --pre --U`

I meant stable release supporting Python 3.11, not pre-release

**Comment by 07maxi** [comment]
Are there any updates on the progress of this release?
Will 2.1.3 ever be released or will it be skipped?

Beginners (just installed the latest python and don't know about prereleases) who want to try pygame might be put off from using it, because they just can't get it to work. Therefore, I think that having a stable release which is compatible with the latest python is a reasonable goal.

**Comment by nextlevelgamer** [comment]
@07maxi I was wondering that too until I took a look at the pygame community discord server. Apparently the maintainer of pygame (the author of this very pull request) has taken some extreme actions and has banned the entire pygame team due to some disagreements over some political opinions (as far as I can tell from skimming the drama- very fun to read IMO). Those who are banned have their commits disassociated with their GitHub accounts. 

## Screenshots
List of individuals that are banned (probably more)
image

The disrespect that has been treated to the contributors
image
image
image

**Comment by Mega-JC** [comment]
@nextlevelgamer I'm not speaking for anyone in particular here, but I don't think this is the right place to discuss matters regarding the Pygame Community Discord server, which you weren't involved in, or that you should stir this PR off-topic and cause drama.

Based on my observation, a 2.1.3 release is still planned, but there might still be development releases made before that, according to https://github.com/pygame/pygame/pull/3609#issuecomment-1425116368 .

**Comment by illume** [comment]
Closing this so CI scripts can pick it up in a new PR.

**Pull request closed without merging**
