### PR TITLE
Add unit test: display.gl_set_attribute() #1748

### PR DESCRIPTION
**Pull request by anesantos**

### CODE REVIEW

**Review by MightyJosip — CHANGES_REQUESTED** [review]
You must remove the venv files you included.

**Review by MightyJosip — APPROVED** [review]

**Comment by MyreMylar** [comment]
Trying a close and reopen on this one to run the modern test suite on it.

**Comment by MyreMylar** [comment]
So this needs a:

```
black test/display_test.py
```

run on it with the latest version of black. Are you still up for working on this @anesantos ?

Plus it looks like we need @Starbuck5 to restart appveyor for us.

**Review by MyreMylar — CHANGES_REQUESTED** [review]
Please run black on this file to pass the formatting check.

**Comment by MyreMylar** [comment]
I think we need someone to take this over and run black on it at this point.

I'll have a go myself.

**Pull request closed without merging**
