### PR TITLE
less strict type checking for AbstractGroup.add

### PR DESCRIPTION
**Pull request by nathanielconroy**
For https://github.com/pygame/pygame/issues/2642

### CODE REVIEW

**Review by illume — APPROVED** [review]
👍 Thanks! 🎈

**Comment by nathanielconroy** [comment]
@illume thanks for the review!

**Review by MightyJosip — CHANGES_REQUESTED** [review]
OK, after checking your https://github.com/pygame/pygame/issues/2642#issuecomment-883827605 I can agree solution without allowing type hints to accept classes that have add_internal method is correct. However I would just require a small extra change. You didn't cover the 
`group.add((group, group))`
 possibility. So I would go with something like
`def add(self, *sprites: Union[Sprite, AbstractGroup, Iterable[Union[Sprite, AbstractGroup]]]) -> None: ...`
Then I think it is ok.

And thank for your work on this 👍

**Comment by nathanielconroy** [comment]
@MightyJosip , I agree. I amended my change. Thanks!

**Review by ankith26 — APPROVED** [review]
LGTM! 👍 🥳 
Thanks for the PR!

**Review by MightyJosip — APPROVED** [review]
👍

**Pull request merged**
