### PR TITLE
Fixed docs for math.Vector2.cross()

### PR DESCRIPTION
**Pull request by Vicky-Vicky27**
Changed the type hint for the returned value from Vector2 to float.
image

### CODE REVIEW

**Comment by Starbuck5** [comment]
Closes #3282

**Comment by Starbuck5** [comment]
Thanks for the PR!

Good job including the generated changes to math_doc.h.

You've got the docs, but that's not the type hint. These are the type hints: https://github.com/pygame/pygame/blob/main/buildconfig/stubs/pygame/math.pyi

**Review by MyreMylar — CHANGES_REQUESTED** [review]
As @Starbuck5 says just change this line:

https://github.com/pygame/pygame/blob/8be7ea8e9dd19c554f68afc0da5c6b76a821a690/buildconfig/stubs/pygame/math.pyi#L168

And this looks good to go

**Comment by Vicky-Vicky27** [comment]
The type hint should be changed now.
[`    def cross(self, other: _SupportsVector2) -> float: ...`](https://github.com/Vicky-Vicky27/pygame-contributions/blob/15bd4d0a8f016947c90c57674f332bff3ed09535/buildconfig/stubs/pygame/math.pyi#L168)

**Review by ankith26 — APPROVED** [review]
LGTM! Thanks for contributing to pygame 🚀 😎

**Review by MyreMylar — APPROVED** [review]

**Pull request merged**
