### PR TITLE
make set_alpha behave like in 1.9.6

### PR DESCRIPTION
**Pull request by robertpfeiffer**
set_alpha(255) should disable blending. get_alpha() should return 255 instead of None.

### CODE REVIEW

**Comment by MightyJosip** [comment]
This should fix crashing reported in #742

**Comment by robertpfeiffer** [comment]
Appveyor is actually succeeding all tests, except one build had a connection timeout.

**Comment by robertpfeiffer** [comment]
As for the travis CI, it the same tests work on my Linux machine!

**Comment by illume** [comment]
This is the failing test on travis CI:
```
FAIL: test_overlap_check (pygame.tests.surface_test.SurfaceSelfBlitTest)
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages/pygame-2.0.0.dev7-py2.7-linux-x86_64.egg/pygame/tests/surface_test.py", line 2419, in test_overlap_check

    self.assertEqual(surf.get_at(test_posn), rectc_right)

AssertionError: (128, 64, 32, 255) != (255, 255, 255, 255)
```

Note that in the test there is a `surf.set_alpha(255)`.

**Comment by MyreMylar** [comment]
This test also passes locally for me on windows with the PR, not sure what is different specifically about the travis builds. I did 'unroll' the test though which might be helpful in debugging if we run this version through Travis:

    def test_overlap_check_unrolled(self):

        surf = pygame.Surface((100, 100), 0, 32)
        surf.set_alpha(255)

        # iteration 1
        surf.fill((0, 0, 0, 255))
        surf.fill((255, 255, 255, 255), (25, 0, 25, 50))
        surf.fill((128, 64, 32, 255), (0, 0, 25, 50))
        surf.blit(surf, (1, 0), pygame.Rect(0, 0, 50, 50))
        self.assertEqual(surf.get_at((50, 0)), (255, 255, 255, 255))

        # iteration 2
        surf.fill((0, 0, 0, 255))
        surf.fill((255, 255, 255, 255), (25, 0, 25, 50))
        surf.fill((128, 64, 32, 255), (0, 0, 25, 50))
        surf.blit(surf, (49, 1), pygame.Rect(0, 0, 50, 50))
        self.assertEqual(surf.get_at((98, 2)), (255, 255, 255, 255))

        # iteration 3
        surf.fill((0, 0, 0, 255))
        surf.fill((255, 255, 255, 255), (25, 0, 25, 50))
        surf.fill((128, 64, 32, 255), (0, 0, 25, 50))
        surf.blit(surf, (49, 49), pygame.Rect(0, 0, 50, 50))
        self.assertEqual(surf.get_at((98, 98)), (255, 255, 255, 255))

        # iteration 4
        surf.fill((0, 0, 0, 255))
        surf.fill((255, 255, 255, 255), (25, 0, 25, 50))
        surf.fill((128, 64, 32, 255), (0, 0, 25, 50))
        surf.blit(surf, (0, 1), pygame.Rect(49, 0, 50, 50))
        self.assertEqual(surf.get_at((0, 2)), (255, 255, 255, 255))

        # iteration 5
        surf.fill((0, 0, 0, 255))
        surf.fill((255, 255, 255, 255), (25, 0, 25, 50))
        surf.fill((128, 64, 32, 255), (0, 0, 25, 50))
        surf.blit(surf, (0, 49), pygame.Rect(49, 0, 50, 50))
        self.assertEqual(surf.get_at((0, 98)), (255, 255, 255, 255))

**Comment by MyreMylar** [comment]
Looks like the unrolled test fails here:

    FAIL: test_overlap_check_unrolled (pygame.tests.surface_test.SurfaceSelfBlitTest)
    
    Traceback (most recent call last):
      File "/home/travis/virtualenv/python3.8.0/lib/python3.8/site-packages/pygame-2.0.0.dev9-py3.8-linux-x86_64.egg/pygame/tests/surface_test.py", line 2633, in test_overlap_check_unrolled
        self.assertEqual(surf.get_at((98, 2)), (255, 255, 255, 255))
    AssertionError: (128, 64, 32, 255) != (255, 255, 255, 255)

that's the last line here: https://github.com/pygame/pygame/blob/c69789bd12634f33bbaf2ef64b7bff2381316db9/test/surface_test.py#L2618-L2633

**Comment by MyreMylar** [comment]
The test logic seems correct. It seems like the clipping rectangle isn't working for fill after set_alpha() is called.

**Comment by illume** [comment]
I'm going to merge this into a `setalpha-compat2` branch on pygame repo so we can collaborate more easily.

**Pull request merged**
