### PR TITLE
Cleaning up example - eventlist.py

### PR DESCRIPTION
**Pull request by Starbuck5**
Removed the from pygame import * in favor of import pygame as pg and from pygame.locals import *. Also made the program quit when the user presses the close button in the top right.

In response to #1423

### CODE REVIEW

**Comment by illume** [comment]
Thanks!

Let me know if you want to continue on this example? If so here are some things...

- Looks like the constants like QUIT need to be pg.QUIT
- Once that is done from pygame.locals import * can be removed.
- I'm not sure why it's saying every line changed? What code editor are you using?

Otherwise we can merge your changes in, and someone else can continue it later.

**Comment by Starbuck5** [comment]
I'll change the constants to be in terms of pygame.

Yeah the every line changed thing is weird. I just copy pasted the file from github into IDLE, messed with it, and then committed it on the github site to replace the existing one. Maybe it's because I copy pasted instead of downloading?

**Comment by illume** [comment]
It might help to run the code through the [black](https://github.com/psf/black) code formatter.

```bash
pip install black
python -m black examples/eventlist.py
```

**Comment by Starbuck5** [comment]
Alright, I'll fix the issues and submit another pull request that hopefully doesn't say every line is replaced.

**Pull request closed without merging**
