### PR TITLE
Fix pyinstaller issue with default font

### LINKED ISSUE #2603: PyInstaller + pygame default font
I thought it would be handy to have an issue to track this.

I had heard people talking about how pygame default font crashes when a game is packaged with PyInstaller, and they're right, sadly.

This is something we should be able to fix in the pygame pyinstaller hook right?

Here's a small test script:
```py
import pygame

pygame.init()

screen = pygame.display.set_mode((400,240))
font = pygame.font.Font(None, 80)
#font = pygame.font.Font("freesansbold.ttf", 80)
#font = pygame.font.SysFont(None, 80)
text = font.render("PYGAME", True, (255,255,255))

clock = pygame.time.Clock()

while True:
    screen.fill("purple")
    screen.blit(text, (10,10))
    
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            raise SystemExit

    pygame.display.flip()
    clock.tick(144)
```

Test procedure:
```
Terminal: PyInstaller testfont.py
Terminal: run generated exe
```

When frozen, the Font based ones emit:
```
Traceback (most recent call last):
  File "testfont.py", line 6, in <module>
    font = pygame.font.Font(None, 80)
TypeError: expected str, bytes or os.PathLike object, not _io.BytesIO
```

And the SysFont one emits:
```
Traceback (most recent call last):
  File "testfont.py", line 8, in <module>
    font = pygame.font.SysFont(None, 80)
  File "pygame\sysfont.py", line 428, in SysFont
  File "pygame\sysfont.py", line 346, in font_constructor
TypeError: expected str, bytes or os.PathLike object, not _io.BytesIO
```

Interestingly, when you go into the `pygame` folder in `dist`, and remove `freesansbold.ttf`, it emits:
```
Traceback (most recent call last):
  File "testfont.py", line 6, in <module>
  File "pygame\pkgdata.py", line 84, in getResource
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Starbuck\\Desktop\\ftest\\dist\\testfont\\pygame\\freesansbold.ttf'
```

@ankith26 Got any ideas?

### PR DESCRIPTION
**Pull request by ankith26**
Quickfix, closes #2603 
Please ignore the formatting changes, my editor does that automatically :/

### CODE REVIEW

**Comment by Starbuck5** [comment]
I tested this locally, and it fixes the issue, good job 👍

**Comment by robertpfeiffer** [comment]
> Please ignore the formatting changes, my editor does that automatically :/

then use `git add -p` in the future, or run clang-format. Doing this automatically messes with merges and git blame, and makes it hard to see what was actually changed.

**Comment by robertpfeiffer** [comment]
Can you explain what you did here and what the problem was a bit more?

**Comment by ankith26** [comment]
Yea sure!
Basically I changed only a small part of the code in the constructor for the `Font` object, the old code used to look like this 
```c
if (obj == Py_None) {
    Py_DECREF(obj);
    obj = font_resource(font_defaultname);
    if (obj == NULL) {
        if (PyErr_Occurred() == NULL) {
            PyErr_Format(PyExc_RuntimeError,
                            "default font '%.1024s' not found",
                            font_defaultname);
        }
        goto error;
    }
    fontsize = (int)(fontsize * .6875);
    if (fontsize <= 1) {
        fontsize = 1;
    }

    oencoded = obj;
    Py_INCREF(oencoded);
    filename = Bytes_AS_STRING(oencoded);
} else {
    /* SDL accepts UTF8 */
    oencoded = pg_EncodeString(obj, "UTF8", NULL, NULL);
    if (!oencoded || oencoded == Py_None) {
        Py_XDECREF(oencoded);
        oencoded = NULL;
        PyErr_Clear();
        goto fileobject;
    }
    filename = Bytes_AS_STRING(oencoded);
}
```
The line `obj = font_resource(font_defaultname);` is supposed to load the default font by the name, into `PyObject`, `obj`, which is expected to be a bytes object. But for some reason, in the pyinstaller case, the function started returning a BytesIO object, a file-like object. Naturally, this would cause problems, because this case is not handled (but file-like objects are handled in the else block). So I simply made the else-part run on all cases (even when `obj` is None), so that all kinds of input from the font resource loading functions are handles normally

**Comment by robertpfeiffer** [comment]
Are you sure the refcounting still works the way it should? Was the refcounting broken before? I think this needs to be commented/refactored a bit more, because font loading is very brittle.

**Comment by ankith26** [comment]
In the bit of code I dealt with, I am pretty sure I did not break refcounts. But overall, font module is a bit complicated, and needs simplification. We also need more uniform default resource loading functions

**Comment by Starbuck5** [comment]
> Py_INCREF(oencoded);

This is the suspect line about ref counting.

But it's weird, because why increase the ref count of oencoded right before it gets encoded into a filename?

**Comment by ankith26** [comment]
I checked that, and yea, `oencoded` gets decref'd later in the function. This incref is required to compensate for that decref

**Review by illume — APPROVED** [review]
👍 thanks!

**Review by Starbuck5 — APPROVED** [review]
Alright, I finally feel that I understand this enough to approve it.

The condition that checks for file objects was only run when the argument was a non default font. This just changes it so it runs regardless.

**Pull request merged**
