### PR TITLE
Keep all window events in SDL2

### PR DESCRIPTION
**Pull request by robertpfeiffer**
generate *additional* compatibility events instead of mangling.
This should help with #1720 on Linux, make pygame's usage of the SDL2 API "more correct", more future-proof, and make behaviour more consistent across platforms.

Especially when minimising and maximising, additional videoexpose events are generated, which are needed for SCALED to work correctly.

@xandark, does this work for you?

### CODE REVIEW

**Comment by illume** [comment]
To reproduce:
- linux (X11 or wayland?), pygame with SDL2
- python3 -m pygame.examples.aliens
- bring another window in front (quick before aliens get you)
- see garbage in aliens window

https://github.com/pygame/pygame/issues/1720#issuecomment-637094351

**Comment by xandark** [comment]
@robertpfeiffer looking at your description, that sounds good to me

@illume sorry, forgot to say it was X11 that I reported the original issue upon, but yes, those steps to reproduce are correct

**Comment by MyreMylar** [comment]
> @robertpfeiffer looking at your description, that sounds good to me
> 

I think robert was hoping you would be able to test his fix to see if it worked. To do this you would need to download the zip of his branch from here:

https://github.com/robertpfeiffer/pygame/tree/keep-window-expose-events

unzip it and name the directory pygame, and then build and install it by navigating to the directory of the unzipped zip running something like:

    python -m buildconfig -sdl2
    python setup.py install
    pip install . -U

Unless you already did that and I misunderstood?

**Comment by xandark** [comment]
@MyreMylar ah, thank you, I didn't know the protocol, I'll follow your instructions tomorrow

**Comment by illume** [comment]
There's a way to install via a commit:
```bash
python -m pip install git+git://github.com/robertpfeiffer/pygame.git@3a3c8a8b1399890e429730f5040d3755ecc31cde --user
```

Or install via a branch:
```bash
python -m pip install https://github.com/robertpfeiffer/pygame/archive/keep-window-expose-events.zip --user
```

**Comment by xandark** [comment]
Okay, I managed to build the special dev11 branch via the `python -m pip install https://github.com/robertpfeiffer/pygame/archive/keep-window-expose-events.zip --user` command, thank you, that worked great for me.

But the issue remains when testing on X11; it didn't fix it. In other words, bringing another window in front of the Aliens example and then bringing Aliens to the front again does not cause Aliens' window to repaint.

**Comment by MyreMylar** [comment]
This seems more correct to me, even if it doesn't resolve the multi-monitor mac issue so I'm going to approve it on general principles.

**Comment by illume** [comment]
> even if it doesn't resolve the multi-monitor mac issue so I'm going to approve it on general principles.

Was this tested by someone as well? I saw xandark above tested on X11.

**Comment by MyreMylar** [comment]
> > even if it doesn't resolve the multi-monitor mac issue so I'm going to approve it on general principles.
> 
> Was this tested by someone as well? I saw xandark above tested on X11.

Nope, I'm just getting my bugs confused because Xandark posted about the issue in that issue thread here:
https://github.com/pygame/pygame/issues/1720

Sadly, I have only one monitor and 0 macs so I can neither confirm or deny that this PR does anything for them.

**Comment by robertpfeiffer** [comment]
I think @xandark might be having a different problem altogether - neither this one, *nor* #1720 on mac. As long as pygame.examples.setmodescale works on KDE neon (with the white circle moving), we can merge this. It works on Linux on my machines.

**Pull request merged**
