### PR TITLE
Update build config + don't link to libpng or libjpeg for SDL2 + config SDL2 prebuilts for Windows

### PR DESCRIPTION
**Pull request by dlon**
The binaries (development libraries) for SDL 2, mixer, etc. work. Also updated it so that the config can be run with `python -m buildconfig -sdl2`.

Still need to:

- [x] Make it work for the remaining DLLs.
- [x] Add FreeType.
- [ ] Write instructions? https://www.pygame.org/wiki/CompileWindows
- [x] imageext: IMG_SaveJPG() and IMG_SavePNG()? Don't link directly.
- [x] Copy all required DLLs.

### Other build configs

- [ ] Update to not look link directly to libpng and libjpeg.

### CODE REVIEW

**Comment by illume** [comment]
This is very nice :) Thank you for doing this.

I started on some instructions... Is this about right?
```
- Get the appropriate Visual C compiler for python 3.7 or python 2.7. (see http://doc.pypy.org/en/latest/windows.html)
- Download SDL2 libs from libsdl.org
    - https://www.libsdl.org/download-2.0.php
    - https://www.libsdl.org/projects/SDL_image/
    - https://www.libsdl.org/projects/SDL_ttf/

- Download other libraries libpng, portmidi ( from here? Or elsewhere? https://bitbucket.org/llindstrom/pygame/downloads/ )
- put the files into your pygame repo checkout. `prebuilt` folder
- `python -m buildconfig -sdl2`
- `python setup.py install --user`
```


There are some people *very-very* interested in a .whl file as part of the community game.
https://www.pygame.org/news/2018/11/the-first-pygame-2-community-game
https://github.com/pygame/stuntcat
When this is ready I'll make one :)

**Comment by dlon** [comment]
I think you only need Visual Studio Community or Express and Python.

This installs everything except FreeType and pypm (portmidi, porttime):

- Download the development libraries:

https://www.libsdl.org/download-2.0.php
https://www.libsdl.org/projects/SDL_ttf/
https://www.libsdl.org/projects/SDL_image/
https://www.libsdl.org/projects/SDL_mixer/

- Extract them in ./prebuilt-x64 (or ./prebuilt-x86).

- `python -m buildconfig -sdl2 -prebuilt`

- `python setup.py install`

FreeType could be linked to at runtime, as the DLL is included with SDL_ttf. Not sure if binaries for portmidi or porttime are maintained anywhere.

**Comment by dlon** [comment]
It worked for Python 2.7 as well.

**Comment by illume** [comment]
Cool, thanks for that. 
I'm working on a "download_prebuilts()" function now.
I guess the portmidi from the older prebuilts can be used (I don't think that library has been updated in quite a while).

(I'm looking forward to the day the conan.io C/C++ package manager gets good enough to use everywhere)

**Comment by illume** [comment]
@dlon I made some download code for prebuilts.
https://github.com/pygame/pygame/pull/651

It can be called like this for now.
```python
python buildconfig/config_win.py --download
```

**Comment by dlon** [comment]
I guess the new instructions are:
```
python -m buildconfig -sdl2
python setup.py install
```
Seems to work using the old libraries, so I think it can be merged.

**Comment by illume** [comment]
Looks like appveyor got stuck. I'm trying a fix now.

**Comment by illume** [comment]
Here is the appveyor test with some SDL2 builds happening.
https://ci.appveyor.com/project/pygame/pygame/builds/20668536

There's a freetype dll error loading on SDL2, and a number of test failures.
So, I've commented out the SDL2 builds now, and they can be fixed in further PRs.

Here is the build I did which disabled the tests on SDL2 so that it can upload wheels.
https://ci.appveyor.com/project/pygame/pygame/builds/20668626

**Pull request merged**
