### PR TITLE
Cythonized sprite module

### PR DESCRIPTION
**Pull request by dlon**
Re: #1068 

This replaces src_py/sprite.py with src_c/sprite.pyx.

## Comparison (drawing)

| Version                                     | C renderer, average time (s) | Cython renderer, average time (s) |
|---------------------------------------------|------------------------------|-----------------------------------|
| sprite.py                                   | 0.9766                       | 1.04                              |
| sprite.pyx (no changes)                     | 0.8083                       | 0.88                              |
| Sprite extension type Any Sprite.rect type  | 0.7894                       |                                   |
| Sprite extension type Rect-type Sprite.rect | 0.7384                       | 0.883 (maybe a fluke)             |
| AbstractGroup extension type                | 0.6853                       | 0.805                             |
| Update sprite.pyx                           |                              | 0.795                             |
| Optimize sprite rendering                           |                              | 0.565                             |

"C renderer" was based on the branch `sdl2-video-c` (#1066). "Cython renderer" is compared to master.

<details> <summary>Test used. I averaged about five measurements for each version.</summary>

```python3
import pygame
import os
data_dir = os.path.join(os.path.split(os.path.abspath(__file__))[0],
                        'data')

from pygame._sdl2 import (
    Window,
    Texture,
    Image,
    Renderer
)

def load_img(file):
    return pygame.image.load(os.path.join(data_dir, file))

pygame.display.init()
pygame.key.set_repeat(10, 10)

win = Window('asdf', resizable=True)
renderer = Renderer(win)
tex = Texture.from_surface(renderer, load_img('alien1.gif'))

class Something(pygame.sprite.Sprite):
    def __init__(self, img):
        pygame.sprite.Sprite.__init__(self)

        self.rect = img.get_rect()
        self.image = img

        self.rect.w *= 5
        self.rect.h *= 5

        if isinstance(img, Image):
            img.origin = self.rect.w / 2, self.rect.h / 2

group = pygame.sprite.Group()

for i in range(20000):
    #sprite = Something(Image(tex))
    sprite = Something(tex)
    sprite.rect.x = 10 * i % win.size[0]
    sprite.rect.w /= 2
    sprite.rect.h /= 2
    sprite.rect.y = sprite.rect.h / 2 * (10 * i // win.size[0])
    group.add(sprite)

import timeit
print('time:', timeit.timeit(lambda: group.draw(renderer), number=100))
```

</details>

100k objects in a group (same texture) are rendered at 30 FPS. It would likely be improved further by calling `Renderer.blit()` directly, as mentioned below.

## Issues

* sprite.rect can only be assigned a `Rect` now. That might cause issues in case someone's using a tuple.
* Probably a lot of stuff could be improved.
* Collision detection: Could it be sped up using quadtrees or some other method? Runtime for testing every pair is currently n^2.
- [ ] `Renderer.blit()` could be declared with `cdef` or `cpdef` and called directly in `sprite.AbstractGroup`, to avoid using `PyObject_CallFunctionObjArgs` for every iteration.
*I tried this*: It brought down the interval to 0.421 s, but there are issues using cimport when the root is src_c.
- [x] sprite.pyx -> _sprite.pyx
- [ ] Update other group types.

### CODE REVIEW

**Comment by illume** [comment]
Very interesting results indeed!

I wonder what the issues with src_c are?

Collision detection can definitely be done in faster ways. Especially in game specific ways. A grid in a platformer for example is very good for dynamically updating and checking collisions for things that are on screen. Then there are more complex collision detection systems like pymunk. Perhaps a spatial hash can be dropped in there for the cases when there is a large Number of sprites to check.

The Layered group uses a heuristic to guess at an optimal way to draw, either full screen updates or dirty rect updates. Maybe this will need some investigation adjustment in a SDL2/sprite.pyx world.

The sprite code doesn't have the best test coverage, but there are quite a few users of it. So those could be used as some sort of test.

Having it as a _sprite.pyx might be a good idea. This would allow it to coexist with sprite.py until 

There's a benchmark written by the pyarcade author that might be useful:
http://arcade.academy/performance_tips.html#drawing-stationary-performance

**Comment by illume** [comment]
The test appveyor failure is that annoying one the intermittently fails.
```
  File "C:\Python27-x64\lib\site-packages\pygame\tests\mixer_test.py", line 139, in test_sound_args
    self.assertEqual(get_bytes(mixer.Sound(wave_path)), snd_bytes)
```

**Comment by dlon** [comment]
`Renderer` speed is disappointing:



I should compare .py to .pyx as well.

Renderer stress test: https://gist.github.com/dlon/85be7654d0781a1a70b14cc0f815ac33
(Somewhat unfair because it doesn't draw any text.)

**Comment by dlon** [comment]
I accidentally loaded a texture for each coin in the last comment. It looks better with batching:

**Comment by illume** [comment]
Nice one :) 

Is this with SDL 2.0.9?

**Comment by dlon** [comment]
Yes. And here's using the OpenGL backend (the default is Direct3D):

**Comment by illume** [comment]
Cool.

SDL 2.0.10 has batching, and is supposed to improve performance a lot.
> So, even on those desktop PCs with the forgiving GPUs, performance went up, across all backends, by 2x to 5x. 20,000 smileys on Direct3D 11 went from 70fps to 240. OpenGL went from 40fps to 120. Metal went from 80 to 190. And so on.

So with your work, I'm guessing it will be close to using OpenGL display lists(like how pyarcade does).

**Comment by dlon** [comment]
Ah, I assumed it had it already. Probably VBOs are even faster than display lists too?

**Comment by dlon** [comment]
I think squash and merge this if it's fine. More updates can come in separate PRs

**Pull request merged**
