### PR TITLE
Edit setup.cfg to reflect 3.10 support

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by ankith26 — APPROVED** [review]
Thanks for the PR 👍 🥳

**Comment by Pycryptor10** [comment]
Note: I can't build in a private repo on 3.10 windows

**Comment by Pycryptor10** [comment]
https://pastebin.com/YiRtEc1r

**Comment by ankith26** [comment]
nice to hear that it did work :) and merging this PR in now

**Pull request merged**
