### PR TITLE
Travis CI: Test Py38 on Ubuntu Bionic

### PR DESCRIPTION
**Pull request by cclauss**
Related to #1429

1. `sudo apt-get install musescore-soundfont-gm` fails on Ubuntu 20.04 so replace with `timgm6mb-soundfont`

2. /usr/lib/gcc/x86_64-linux-gnu/9/include-fixed/bits/statx.h:38:25: error: missing binary operator before token "("  https://travis-ci.org/github/pygame/pygame/jobs/688841921#L1375

### CODE REVIEW

**Comment by illume** [comment]
Thanks.

It would be good to have one builder using the new ubuntu. This way we can test with different versions of dependencies (like libsdl and such). Keeping other python versions in there lets us test with those older python versions too.

The builds for python 3.8 for pygame 1.9.6 could be made, but that would have to be done manually by someone - not with our travis CI config. I guess pygame 2 will still take a while to do, and more and more people are encountering issues building from source. So we should probably do that.

I'll squash-merge this into another branch, and do some more modifications on it in another PR.

**Comment by nthykier** [comment]
@illume Any news on the branch you were talking about or should we go ahead and merge this one after it was squashed and rebased by @cclauss ?

**Comment by illume** [comment]
I'll have a look at this again after I push a release out in the next days :)

**Comment by nthykier** [comment]
> I'll have a look at this again after I push a release out in the next days :)

Ping?

**Comment by illume** [comment]
Thanks for the ping.

**Review by illume — CHANGES_REQUESTED** [review]
- Giving us good coverage of different systems and dependencies should be a goal for the CI. It seems Xenial reaches end of support next year in April 2021. https://wiki.ubuntu.com/Releases It would be good to cover these supported versions: (16.4, 18.4, 20.4, 20.10/Xenial, Bionic, Focal, Groovy). Keeping the older builds is required (because it helps us test with old versions of dependencies compared to dev machines which are often running on the latest). Running that ARM build on Xenial was required (maybe it still is). Because it would otherwise run on x86.

- I haven't tested the config change at the bottom of the travis.yml (near deploy). What is the reason for the change?

**Comment by cclauss** [comment]
That change was made to fix a Travis Build Config Validation issue...
[Config - Build #3704 - pygamepygame - Travis CI.pdf](https://github.com/pygame/pygame/files/5178017/Config.-.Build.3704.-.pygamepygame.-.Travis.CI.pdf)

**Comment by illume** [comment]
Makes sense, thanks :)

**Comment by illume** [comment]
`skip_cleanup: true` can be removed now since [cleanup: false is the default](https://blog.travis-ci.com/2019-08-27-deployment-tooling-dpl-v2-preview-release).

**Review by illume — APPROVED** [review]
👍 thanks

**Comment by cclauss** [comment]
> skip_cleanup: true can be removed now since cleanup: false is the default.

The merge to master undid that.
https://travis-ci.org/github/pygame/pygame/builds/725473713/config Click `Build config validation`

**Pull request merged**
