### PR TITLE
Added unit test for display.set_gamma_ramp()

### PR DESCRIPTION
**Pull request by anguye13**
[#1751 ](https://github.com/pygame/pygame/issues/1751)

### CODE REVIEW

**Comment by MyreMylar** [comment]
I feel like this test doesn't provide a great example of what setting the gamma ramp actually does. My intuition is that you set a look up table for each channel (e.g. red[50] now equals 60 instead of 50) and then that is applied to the display surface somehow. I assume it happens as some sort of final step when you `.flip()/.update()` the screen but having that show in a test somehow would be useful even if it is in a separate test that will only run locally. If it is a post .update()/flip() change to the display surface change that is tricky to test in the standard way by examining the pixels of the surface (as they will still be the same).

So, failing any other good ideas coming to mind, my thought is that you could keep the current test but add a local interactive test that has a couple of dramatic gamma shifts displayed (e.g. start with a black screen shift blue[0] to 255) and ask users to confirm via the console that the window contents are blue/red/green or whatever ramp is set. Does that make sense?

You can see examples of interactive tests in the cdrom or joystick test modules. They are basically a special type of test that only runs when the tests are run locally on a users machine and prompt for feedback.

**Comment by anguye13** [comment]
Yea that makes sense, I’ll try and make the changes when I get a chance 👍

**Comment by illume** [comment]
I think this test provides value, and that we can merge it in. I've added the extra test requirements into the #1751 issue (which we can leave open).

**Review by illume — APPROVED** [review]
Thanks :)

**Pull request merged**
