### PR TITLE
Added a unit test for display.flip()

### PR DESCRIPTION
**Pull request by amipy**
This is a unit test for display.flip().
I was unable to come up with a method to test the last error condition in the code, because that condition involves SDL giving an error not caught by pygame, and I do no know how to do that.

### CODE REVIEW

**Comment by amipy** [comment]
Here is the issue I wrote this for.
#1742

**Comment by MightyJosip** [comment]
This unit test should be part of [this file](https://github.com/pygame/pygame/blob/master/test/display_test.py#L51-L66)

**Comment by amipy** [comment]
Alright, I moved it to the display_test file.

**Comment by amipy** [comment]
There was an error in my test, so I fixed it.

**Review by illume — APPROVED** [review]
Thanks 🎉

**Pull request merged**
