### PR TITLE
adding BGRA format for pycairo compatibility

### PR DESCRIPTION
**Pull request by rlatowicz**

### CODE REVIEW

**Review by MyreMylar — CHANGES_REQUESTED** [review]
Code looks good 👍 

But we need to add the new format string to the list in the docs. And a version added note in the docs saying it was added in 2.1.3. A quick unit test would probably be good as well (test/image_test.py)

Docs will be in image.rst

**Comment by rlatowicz** [comment]
Updated the note in docs and the test.

**Review by MyreMylar — APPROVED** [review]

**Comment by MyreMylar** [comment]
To pass that `python3 setup.py lint / format-lint-code-check` CI test runner you need to run clang format on your .c file changes. It'll probably just add and remove a few spaces here and there. 

clang is pretty easy to get going on mac and linux, and a little more tricky on windows.

**Comment by rlatowicz** [comment]
Need to get Clang installed.

This is going to take a bit of time :)
Sorry.

**Review by ankith26 — CHANGES_REQUESTED** [review]
Hello, thanks for contributing to pygame! 🥳 

I noticed that this is only being added to `frombuffer` in this PR, is there any particular reason it's not added to `fromstring`/`tostring`?

Also, you should update the typestubs in [this file](https://github.com/pygame/pygame/blob/main/buildconfig/stubs/pygame/image.pyi).
Basically, you need to add `"BGRA"` into the list of accepted literals for the functions you are adding code support for

**Comment by rlatowicz** [comment]
"BGRA" was added to allow pygame to directly use a buffer created with pycairo's "ARGB32" format.

No reason not to add it elsewhere.

**Comment by Starbuck5** [comment]
I don't know how you ended up installing clang. I do it through a VS code plugin, which was convenient to install and use.

> I noticed that this is only being added to frombuffer in this PR, is there any particular reason it's not added to fromstring/tostring?

> No reason not to add it elsewhere if there is a use case.

I would also like it to be added to `fromstring/tostring`, however there's no need to do it all in this PR, that can be a follow up, if you'd like to do it 😄.

**Review by Starbuck5 — APPROVED** [review]
Looks good!

**Comment by rlatowicz** [comment]
I grabbed clang via Msys2 using pacman.
That was thankfully fast and uneventful.

**Review by ankith26 — APPROVED** [review]
Thanks again👍 🎉

**Comment by rlatowicz** [comment]
Hi,
I just noticed that **BGRA** format is also compatible with [skia-python](https://kyamagu.github.io/skia-python/)

2024-02-16 16_54_08-pygame_skia

using the example here [More drawings](https://kyamagu.github.io/skia-python/tutorial/overview.html#more-drawings)

```
import pygame
import skia

width, height = 256, 256

# Draw to a skia surface
surface = skia.Surface(width, height)

with surface as canvas:
    rect = skia.Rect(50, 50, 90, 110)
    paint = skia.Paint(
        AntiAlias=True,
        Style=skia.Paint.kStroke_Style,
        StrokeWidth=4,
        Color=skia.ColorRED,
    )

    canvas.drawColor(skia.ColorWHITE)
    canvas.drawRect(rect, paint)

    oval = skia.RRect.MakeOval(rect)
    oval.offset(40, 60)
    paint.setColor(skia.ColorBLUE)
    canvas.drawRRect(oval, paint)

    paint.setColor(skia.ColorCYAN)
    canvas.drawCircle(180, 50, 25, paint)

    rect.offset(80, 0)
    paint.setColor(skia.ColorYELLOW)
    canvas.drawRoundRect(rect, 10, 10, paint)

    path = skia.Path()
    path.cubicTo(768, 0, -512, 256, 256, 256)
    paint.setColor(skia.ColorGREEN)
    canvas.drawPath(path, paint)
    
    image = skia.Image.open('color_wheel.png')
    canvas.drawImage(image, 128, 128)

    rect2 = skia.Rect(40, 60)
    canvas.drawImageRect(image, rect2)

    paint2 = skia.Paint()
    text = skia.TextBlob(
        'Hello, Skia!',
        skia.Font(skia.Typeface('Arial', skia.FontStyle.Bold()), 18))
    canvas.drawTextBlob(text, 50, 25, paint2)

skia_data=surface.toarray()

# Init PyGame
pygame.display.init()
screen = pygame.display.set_mode((width, height), 0, 32)
pygame.display.set_caption("pygame/skia")

# Create PyGame surface from the skia surface buffer - BGRA
pygame_surface = pygame.image.frombuffer(skia_data, (width, height), 'BGRA')

# Show PyGame surface
screen.blit(pygame_surface, (0, 0))
pygame.display.flip()
    
clock = pygame.time.Clock()
while not pygame.QUIT in [e.type for e in pygame.event.get()]:
    clock.tick(30)    
```

**Pull request merged**
