### PR TITLE
Add new module pygame._time

### PR DESCRIPTION
**Pull request by ankith26**
continued from #2271 

Related issues: #304 #2177 
**To summerise**
This adds a new experimental module ``pygame._time``, based on ``pygame.time`` with clocks of much better accuracy.

**Internal changes**
It uses the new time-related functions of SDL2 (yup, `SDL_GetPerformanceCounter`), using the extended accuracy provided to give float-millisecond accuracy to the functions in the time module.
This clock uses the most accurate clock available on the system. On most windows platforms, this has microsecond precision and on most Unix-based platforms (Linux, Mac, etc) this gives nanosecond precision (fallback to microsecond precision in rare cases). In worst cases (extremely rare) it may fall back to using millisecond accuracy.

**Usage changes**
1) The function `pygame._time.wait()` now accepts the millisecond argument as an int or float(previously it was only int) and also returns a float, the function is made much more accurate by making it such that it sleeps the processor for some time and does a busy loop to delay for the time requested by the user.
2) The function `pygame._time.delay()` is made an alias to the function `pygame._time.wait()`, now that the function `pygame._time.wait()` is accurate.
3) The `pygame._time.Clock` object now is much more accurate in the method for `tick()` which now uses the time module to do its busy loop to give sub-millisecond accuracy, this means that the game will run at (almost) exactly the FPS you want, rather than rounding it to some arbitrary FPS. The `tick_busy_loop` method is aliased to `tick()` now that it’s accurate.
4) The methods `get_time()` and `get_rawtime()` now return floats, for extended accuracy

**Other Changes**
1) The Unit tests for this new time module are revamped to be more CI friendly, they are also sped up to take half of the original time to run, and they are strictly checking stuff at the same time. 
This is mainly due to the fact that now, if a test fails, it will re-run, just to eliminate any errors due to OS scheduling and CI VM's. Don't worry, the test wont run forever on failure, after a particular point, it gives up and fails
The tests are still blocked from being run on Mac VM, though

### CODE REVIEW

**Comment by ankith26** [comment]
How do we proceed further on this one? The only reason I created _time to be separate from time, is because it should be easier for people to test stuff, and merge this into the time module later on (in some version like 2.1) 

Is this a good idea? Many on discord think that introducing a new module in pygame might not be a good idea, and I sort of agree. What else can we do about this?

**Comment by mcpalmer1980** [comment]
I would like to see this come in ASAP no matter the form. I don't mind having a _time module that I can import as time. On the other hand, replacing the existing time module with a more precise method of delay would be great too, as long as anything that may adversely effect performance or compatibility are optional.

**Option 1**
```py
try:
    from pygame import _time as time
except:
    from pygame import time
```
**Option 2**
- The existing time module uses the new more precise method introduced by ankith without any sort of performance chewing or change of return values.
- tick_busy_loop() and similar functions are updated to use the new more precise method introduced by ankith, including a busy loop near the end of the delay and any other code that adversely effects performance.
- A float=False parameter is added to any time methods that can return floats. They continue returning ints by default unless the float=True parameter is set.

**Comment by ankith26** [comment]
IMHO, this PR is the easiest to merge in it’s current form, as a seperate experimental module. So maybe _time is the right way to proceed on this

**Comment by mcpalmer1980** [comment]
I would love to see a Clock.get_ticks() method that returns the total number of ticks it has performed. This would be useful if your game objects hold a clock reference and need to know if it is time to update its state. For instance, if your sprite class (or the one in renderpy) can be drawn as an image as many times as you want but only call update() if Clock.get_ticks() has incremented.

Even if you could just expose the current fps_count variable it would sort of work, but a total frame counter would be better that just 1-10. Most pygame users probably store total_frames in a variable and are forced to pass either the frame counter or a time delta all around their program. The clock probably should have had a frame counter included from the beginning.

Any thoughts?

**Comment by ankith26** [comment]
The idea sure sounds good, but I’m not sure of all it’s usecases. In how many situations will this feature be used?

**Comment by mcpalmer1980** [comment]
Well I certainly can't say how many people would use it or in what situations, but I can speak for places I would have used it.

All of my games have a frames variable incremented in the game loop. 
- I use it for determine time played (it isn't incremented during pauses, menu screens, or dialogue)
```py
	def ShowScore(self):
		if not self.mapdb.last_time:
			return
		time = self.frames * (1000 / 30.0)
```
- I use it for character and item flashing 
I prefer to do blinking  a little differently:
  ```py
    if frames % 30 < 20:
      character.draw()

    if self.player.gloves > 0 and self.frames % 10 < 6:
      self.s_icons.DrawAt(x,y,8)
  ```

These uses require me to set frames as an attribute of my game class, make the class available to all other classes, and manually increment the count during each counted frame. Since renderpyg needs to be design agnostic with minimal assumptions, I have to think differently. My sprite class has an update() method that animates it based on a time delta. Then it is drawn with a separate draw() call.

I would like to offer a way to allow sprites to self animate and be drawn just like a Texture or Image. In order to facilitate this you must assign a reference to your game's clock. Then the sprite will update() whenever draw() is called if that clock reference exists, and the sprite may be passed as an image to a menu class. The menu will then automagically animate the image without any knowledge of the sprite class. But an Image may be drawn() several times throughout the menu, and you don't want it too animate faster for each time it gets drawn, so I need a way to determine if the clock has ticked since the last draw() call.

Here is the code for my current use case:
```py
    def draw(self, dstrect=None):
        """
        Render the sprite at its current position or at the postion of dstrect
        Use set_pos() and set_frame() modify where and how to draw it
    
        Sprites will animate if Sprite.clock references a time.Clock object
        This allows the sprite to be drawn as a normal Image without the caller's
        knowlege of animation
        """
        if self.clock and self.clock.get_ticks() > self.last_update:
             self.last_update = self.clock.get_ticks()
             self.update(self.clock.get_time())
        
        if dstrect:
            self.image.draw(dstrect=dstrect)
        else:
            self.image.draw(self.dest_rect)
```

**Comment by ankith26** [comment]
Interesting ideas. It shouldn’t be hard to implement this one, so I am for it. 
Maybe get suggestions of more people, as it’s bit of an API change. I (or anyone else, if interested) could also do it in a separate PR, after this one has been merged

**Review by Starbuck5 — APPROVED** [review]
I say we merge this, on the principle that it doesn't do any harm.

This can be another experimental module like the _sdl2 modules, allowing power users to play with it and hopefully find any issues, should they exist.

I've tested it locally and it works. 
I don't know how to test it against an objective timer, or test relative CPU usage: so "it works" is the best I can do.

The backwards compatibility problems with returning `float` rather than int are only for python 2, because in python 3 float division is the default. So perhaps when we drop python 2 support this module could become the main time module.

Of course its been a while since the PR was introduced, so there are some small changes that are needed to be fully ready for merge, like changing "new in 2.0.1" to "new in 2.0.2."

**Comment by Starbuck5** [comment]
Now that we're on Python 3 we could do some of this stuff incrementally?

Change some return values to floats? Change around some internal arithmetic to round better, without even having to leave the old sleep methods?

**Pull request closed without merging**
