### PR TITLE
Hopefully fix segfault in event post

### PR DESCRIPTION
**Pull request by ankith26**
Just testing out some changes, to hopefully fix segfaults.

### CODE REVIEW

**Comment by mgedmin** [comment]
This fails to build for me:

```
mg@blynas: ~/src/pyspacewar [git:master $=] $ .tox/py38/bin/pip install ~/src/pygame
Processing /home/mg/src/pygame
Building wheels for collected packages: pygame
  Building wheel for pygame (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/mg/src/pyspacewar/.tox/py38/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-2hwssek1/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-2hwssek1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-0vuzy6sk
       cwd: /tmp/pip-req-build-2hwssek1/
  Complete output (243 lines):
  running bdist_wheel
  running build
  running build_py
  copying src_py/freetype.py -> build/lib.linux-x86_64-3.8/pygame
  copying src_py/_numpysurfarray.py -> build/lib.linux-x86_64-3.8/pygame
  copying src_py/locals.py -> build/lib.linux-x86_64-3.8/pygame
  copying src_py/__init__.py -> build/lib.linux-x86_64-3.8/pygame
  copying src_py/macosx.py -> build/lib.linux-x86_64-3.8/pygame
  copying src_py/cursors.py -> build/lib.linux-x86_64-3.8/pygame
  copying src_py/_dummybackend.py -> build/lib.linux-x86_64-3.8/pygame
  copying src_py/sndarray.py -> build/lib.linux-x86_64-3.8/pygame
  copying src_py/surfarray.py -> build/lib.linux-x86_64-3.8/pygame
  copying src_py/colordict.py -> build/lib.linux-x86_64-3.8/pygame
  copying src_py/draw_py.py -> build/lib.linux-x86_64-3.8/pygame
  copying src_py/sprite.py -> build/lib.linux-x86_64-3.8/pygame
  copying src_py/camera.py -> build/lib.linux-x86_64-3.8/pygame
  copying src_py/compat.py -> build/lib.linux-x86_64-3.8/pygame
  copying src_py/_numpysndarray.py -> build/lib.linux-x86_64-3.8/pygame
  copying src_py/version.py -> build/lib.linux-x86_64-3.8/pygame
  copying src_py/_camera_vidcapture.py -> build/lib.linux-x86_64-3.8/pygame
  copying src_py/pkgdata.py -> build/lib.linux-x86_64-3.8/pygame
  copying src_py/sysfont.py -> build/lib.linux-x86_64-3.8/pygame
  copying src_py/_camera_opencv_highgui.py -> build/lib.linux-x86_64-3.8/pygame
  copying src_py/midi.py -> build/lib.linux-x86_64-3.8/pygame
  copying src_py/ftfont.py -> build/lib.linux-x86_64-3.8/pygame
  creating build/lib.linux-x86_64-3.8/pygame/threads
  copying src_py/threads/__init__.py -> build/lib.linux-x86_64-3.8/pygame/threads
  copying src_py/_sdl2/__init__.py -> build/lib.linux-x86_64-3.8/pygame/_sdl2
  creating build/lib.linux-x86_64-3.8/pygame/tests
  copying test/font_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/image_tags.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/__main__.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/freetype_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/ftfont_tags.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/image_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/color_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/scrap_tags.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/surfarray_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/ftfont_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/transform_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/compat_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/rwobject_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/pixelarray_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/pixelcopy_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/sysfont_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/surflock_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/fastevent_tags.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/__init__.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/rect_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/font_tags.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/key_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/scrap_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/image__save_gl_surface_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/mixer_music_tags.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/touch_tags.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/time_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/sndarray_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/sndarray_tags.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/mixer_tags.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/gfxdraw_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/bufferproxy_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/overlay_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/cdrom_tags.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/display_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/midi_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/cursors_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/imageext_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/draw_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/mouse_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/math_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/test_test_.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/cdrom_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/touch_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/fastevent_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/imageext_tags.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/base_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/mixer_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/mixer_music_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/threads_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/joystick_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/video_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/overlay_tags.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/freetype_tags.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/mask_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/surfarray_tags.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/sprite_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/camera_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/event_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/surface_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/constants_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/version_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  copying test/blit_test.py -> build/lib.linux-x86_64-3.8/pygame/tests
  creating build/lib.linux-x86_64-3.8/pygame/tests/test_utils
  copying test/test_utils/png.py -> build/lib.linux-x86_64-3.8/pygame/tests/test_utils
  copying test/test_utils/test_machinery.py -> build/lib.linux-x86_64-3.8/pygame/tests/test_utils
  copying test/test_utils/endian.py -> build/lib.linux-x86_64-3.8/pygame/tests/test_utils
  copying test/test_utils/__init__.py -> build/lib.linux-x86_64-3.8/pygame/tests/test_utils
  copying test/test_utils/test_runner.py -> build/lib.linux-x86_64-3.8/pygame/tests/test_utils
  copying test/test_utils/buftools.py -> build/lib.linux-x86_64-3.8/pygame/tests/test_utils
  copying test/test_utils/arrinter.py -> build/lib.linux-x86_64-3.8/pygame/tests/test_utils
  copying test/test_utils/run_tests.py -> build/lib.linux-x86_64-3.8/pygame/tests/test_utils
  copying test/test_utils/async_sub.py -> build/lib.linux-x86_64-3.8/pygame/tests/test_utils
  creating build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests
  copying test/run_tests__tests/__init__.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests
  copying test/run_tests__tests/run_tests__test.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests
  creating build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/all_ok
  copying test/run_tests__tests/all_ok/no_assertions__ret_code_of_1__test.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/all_ok
  copying test/run_tests__tests/all_ok/fake_4_test.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/all_ok
  copying test/run_tests__tests/all_ok/fake_6_test.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/all_ok
  copying test/run_tests__tests/all_ok/__init__.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/all_ok
  copying test/run_tests__tests/all_ok/fake_5_test.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/all_ok
  copying test/run_tests__tests/all_ok/fake_3_test.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/all_ok
  copying test/run_tests__tests/all_ok/fake_2_test.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/all_ok
  copying test/run_tests__tests/all_ok/zero_tests_test.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/all_ok
  creating build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/failures1
  copying test/run_tests__tests/failures1/fake_4_test.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/failures1
  copying test/run_tests__tests/failures1/__init__.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/failures1
  copying test/run_tests__tests/failures1/fake_3_test.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/failures1
  copying test/run_tests__tests/failures1/fake_2_test.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/failures1
  creating build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/incomplete
  copying test/run_tests__tests/incomplete/__init__.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/incomplete
  copying test/run_tests__tests/incomplete/fake_3_test.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/incomplete
  copying test/run_tests__tests/incomplete/fake_2_test.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/incomplete
  creating build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/infinite_loop
  copying test/run_tests__tests/infinite_loop/fake_1_test.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/infinite_loop
  copying test/run_tests__tests/infinite_loop/__init__.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/infinite_loop
  copying test/run_tests__tests/infinite_loop/fake_2_test.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/infinite_loop
  creating build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/print_stderr
  copying test/run_tests__tests/print_stderr/fake_4_test.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/print_stderr
  copying test/run_tests__tests/print_stderr/__init__.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/print_stderr
  copying test/run_tests__tests/print_stderr/fake_3_test.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/print_stderr
  copying test/run_tests__tests/print_stderr/fake_2_test.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/print_stderr
  creating build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/print_stdout
  copying test/run_tests__tests/print_stdout/fake_4_test.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/print_stdout
  copying test/run_tests__tests/print_stdout/__init__.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/print_stdout
  copying test/run_tests__tests/print_stdout/fake_3_test.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/print_stdout
  copying test/run_tests__tests/print_stdout/fake_2_test.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/print_stdout
  creating build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/incomplete_todo
  copying test/run_tests__tests/incomplete_todo/__init__.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/incomplete_todo
  copying test/run_tests__tests/incomplete_todo/fake_3_test.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/incomplete_todo
  copying test/run_tests__tests/incomplete_todo/fake_2_test.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/incomplete_todo
  creating build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/exclude
  copying test/run_tests__tests/exclude/__init__.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/exclude
  copying test/run_tests__tests/exclude/magic_tag_test.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/exclude
  copying test/run_tests__tests/exclude/invisible_tag_test.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/exclude
  copying test/run_tests__tests/exclude/fake_2_test.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/exclude
  creating build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/timeout
  copying test/run_tests__tests/timeout/__init__.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/timeout
  copying test/run_tests__tests/timeout/fake_2_test.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/timeout
  copying test/run_tests__tests/timeout/sleep_test.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/timeout
  creating build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/everything
  copying test/run_tests__tests/everything/incomplete_todo_test.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/everything
  copying test/run_tests__tests/everything/__init__.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/everything
  copying test/run_tests__tests/everything/magic_tag_test.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/everything
  copying test/run_tests__tests/everything/fake_2_test.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/everything
  copying test/run_tests__tests/everything/sleep_test.py -> build/lib.linux-x86_64-3.8/pygame/tests/run_tests__tests/everything
  creating build/lib.linux-x86_64-3.8/pygame/docs
  copying docs/__main__.py -> build/lib.linux-x86_64-3.8/pygame/docs
  copying docs/__init__.py -> build/lib.linux-x86_64-3.8/pygame/docs
  creating build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/fastevents.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/prevent_display_stretching.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/sound_array_demos.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/glcube.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/music_drop_fade.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/overlay.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/fonty.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/moveit.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/stars.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/scroll.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/__init__.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/testsprite.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/cursors.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/headless_no_windows_needed.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/font_viewer.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/aacircle.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/video.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/mask.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/scrap_clipboard.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/vgrade.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/chimp.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/playmus.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/camera.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/pixelarray.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/setmodescale.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/sound.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/eventlist.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/audiocapture.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/liquid.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/scaletest.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/aliens.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/resizing_new.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/arraydemo.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/sprite_texture.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/blit_blends.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/blend_fill.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/textinput.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/midi.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/dropevent.py -> build/lib.linux-x86_64-3.8/pygame/examples
  copying examples/freetype_misc.py -> build/lib.linux-x86_64-3.8/pygame/examples
  creating build/lib.linux-x86_64-3.8/pygame/__pyinstaller
  copying src_py/__pyinstaller/hook-pygame.py -> build/lib.linux-x86_64-3.8/pygame/__pyinstaller
  copying src_py/__pyinstaller/__init__.py -> build/lib.linux-x86_64-3.8/pygame/__pyinstaller
  running build_ext
  building 'pygame.pypm' extension
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -D_REENTRANT -I/usr/X11R6/include -I/usr/include/SDL2 -I/usr/include -I/usr/include -I/home/mg/src/pyspacewar/.tox/py38/include -I/usr/include/python3.8 -c src_c/pypm.c -o build/temp.linux-x86_64-3.8/src_c/pypm.o
  x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.8/src_c/pypm.o -lSDL2 -lportmidi -lporttime -o build/lib.linux-x86_64-3.8/pygame/pypm.cpython-38-x86_64-linux-gnu.so
  building 'pygame.event' extension
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -D_REENTRANT -I/usr/X11R6/include -I/usr/include/SDL2 -I/home/mg/src/pyspacewar/.tox/py38/include -I/usr/include/python3.8 -c src_c/event.c -o build/temp.linux-x86_64-3.8/src_c/event.o
  src_c/event.c: In function ‘pg_event_filter’:
  src_c/event.c:223: warning: ignoring #pragma PG_WARN  [-Wunknown-pragmas]
    223 | #pragma PG_WARN(Add event blocking here.)
        |
  In file included from src_c/pygame.h:30,
                   from src_c/event.c:28:
  src_c/event.c: In function ‘pg_event_post’:
  src_c/event.c:1922:22: error: ‘PgExc_SDLError’ undeclared (first use in this function); did you mean ‘pgExc_SDLError’?
   1922 |         return RAISE(PgExc_SDLError, "the type attribute exceeded its limit");
        |                      ^~~~~~~~~~~~~~
  src_c/_pygame.h:157:39: note: in definition of macro ‘RAISE’
    157 | #define RAISE(x, y) (PyErr_SetString((x), (y)), (PyObject *)NULL)
        |                                       ^
  src_c/event.c:1922:22: note: each undeclared identifier is reported only once for each function it appears in
   1922 |         return RAISE(PgExc_SDLError, "the type attribute exceeded its limit");
        |                      ^~~~~~~~~~~~~~
  src_c/_pygame.h:157:39: note: in definition of macro ‘RAISE’
    157 | #define RAISE(x, y) (PyErr_SetString((x), (y)), (PyObject *)NULL)
        |                                       ^
  src_c/_pygame.h:157:47: warning: left-hand operand of comma expression has no effect [-Wunused-value]
    157 | #define RAISE(x, y) (PyErr_SetString((x), (y)), (PyObject *)NULL)
        |                                               ^
  src_c/event.c:1922:16: note: in expansion of macro ‘RAISE’
   1922 |         return RAISE(PgExc_SDLError, "the type attribute exceeded its limit");
        |                ^~~~~
  
  ---
  For help with compilation see:
      https://www.pygame.org/wiki/Compilation
  To contribute to pygame development see:
      https://www.pygame.org/contribute.html
  ---
  
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pygame
  Running setup.py clean for pygame
Failed to build pygame
```

**Comment by ankith26** [comment]
Oops it’s  a typo in my code, I’ll fix it now. 
Anyways, I’m not sure wether this PR really fixes your issue, I’m just trying stuff

**Comment by ankith26** [comment]
Fixed that typo, now you can test it if you want to :)

**Comment by illume** [comment]
I guess we need a unittest that triggers the segfault.

**Comment by ankith26** [comment]
Yeah that would be good, what I will do is I will open a separate PR for that, and let those run against master, then merge that PR into this one to test this out

**Comment by mgedmin** [comment]
It builds now, but 93de2c17 still has the segfault.

**Comment by ankith26** [comment]
After a bit of testing, I can confirm that this PR DOES NOT fix the segfaults in event.post QUIT (which is an issue reported by @mgedmin that I could not reproduce) and event.post KEYDOWN (which i could reproduce)

Wrote unit tests to cover for both (and merged them into this PR).
The only thing this PR probably fixes is a minor bug in one of those else if conditions

**Comment by ankith26** [comment]
Since this PR does not fix stuff, im dropping it

**Pull request closed without merging**
