### PR TITLE
setup.py: fix user+deprecation warnings on 3.11+

### PR DESCRIPTION
**Pull request by pmp-p**
should fix both
```
setup.py:71: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils
```
```
_distutils_hack/__init__.py:17: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.
```

### CODE REVIEW

**Review by ankith26 — COMMENTED** [review]
distutils should be fully removed and we should be migrating to setuptools (related issue: #2724)

**Review by cclauss — APPROVED** [review]
> distutils should be fully removed and we should be migrating to setuptools

Let's land this PR as is because it already solves the issues in the PR title.

You can open a separate PR to do the complete migration away from distutils.

**Comment by ankith26** [comment]
I have a WIP distutils port branch that I've been working on already (not much progress and no ETA)
It would be hard to do this considering the amount of distutils specific hacks we have, that (afaik) has no convenient setuptools stable API to accomplish (except from directly using the patched distutils that setuptools uses)

That being said, I did not request any change on this PR, my first comment was more of an FYI
I will approve this once I learn more about the implications (this might not be as straightforward as it looks, because setuptools patches its own distutils and we've been using this patch unknowingly for a while)
CI passes on this PR so maybe this PR is not as risky as I think

**Review by MyreMylar — APPROVED** [review]
Tested this a bunch locally and pygame still compiles and runs fine on windows with the order of includes swapped.

**Review by nthykier — APPROVED** [review]

**Pull request merged**
