### PR TITLE
Deprecate gamma and _sdl2 window brightness functionality

### LINKED ISSUE #3600: Deprecate gamma functionality
SDL has removed it in SDL3 development already-- https://github.com/libsdl-org/SDL/pull/6617

We have stuff in display.c using `SDL_SetWindowGammaRamp`, those methods should be changed to emit deprecation warnings.

We have things using `SDL_SetWindowBrightness` and `SDL_GetWindowBrightness` in _sdl2.video, those should be removed.

### PR DESCRIPTION
**Pull request by SSS-Says-Snek**
Fixes #3600

### CODE REVIEW

**Review by Starbuck5 — COMMENTED** [review]
You also need to remove from the video types and docs.

**Comment by SSS-Says-Snek** [comment]
oops, I forgot, lemme do those things real quick

**Comment by Starbuck5** [comment]
The lint is complaining that the docs changes caused a header file to generate differently.

Run `python setup.py docs` and commit the changes.

**Review by Starbuck5 — APPROVED** [review]
Thanks!

**Review by MyreMylar — APPROVED** [review]
LGTM. 

I don't image many people are using per application gamma control anymore anyway. From what I recall it doesn't work very well in SDL2 either.

EDIT: reading the linked SDL issue it seems like the only option these days is to change the gamma for the whole system - so it is no longer per application at the moment anyway.

**Pull request merged**
