### PR TITLE
Updated docker vagrant install instructions for manylinux build.

### PR DESCRIPTION
**Pull request by illume**
Updating instructions for manylinux build as I go. So far docker instructions changed since last year.
- [x] freetype pkg-config does not work, fallback to freetype-config.
- [x] update docker install instructions on vagrant.
- [x] upgrade manylinux to have python3.7 (cp37-cp37m)

re: https://github.com/pygame/pygame/issues/390

### CODE REVIEW

**Comment by illume** [comment]
Looks like this freetype pkg-config change broke the manylinux build: https://github.com/pygame/pygame/pull/442
```
    WARNING: "pkg-config freetype2" failed!
```

**Comment by illume** [comment]
@takluyver do you remember how to upload an updated image to the docker hub? I had to do a `make pull` for the manylinux python 3.7

**Comment by takluyver** [comment]
There's a `make push` target in the makefile which should do it. The actual commands it uses look like `docker push pygame/manylinux1_base_x86_64` .

**Comment by illume** [comment]
Ah ha! Thanks. I also had to do `docker login`, and the `make push` ran. Looks like https://hub.docker.com/u/pygame/ has the new images now.

**Pull request merged**
