### PR TITLE
SDL 2.0.20

### PR DESCRIPTION
**Pull request by illume**

### CODE REVIEW

**Comment by Starbuck5** [comment]
We had some event test failing on SDL 2.0.18, which you put in a skip for. I believe that's fixed now, so we can take that out.

**Comment by illume** [comment]
The skips were added in this PR for SDL 2.0.18 https://github.com/pygame/pygame/pull/2939

**Comment by ankith26** [comment]
SDL 2.0.20 has been released, this PR should move to that and not use the pre-release anymore now

**Comment by illume** [comment]
I left tests skipping, as apparently they are still broken on windows.

**Comment by illume** [comment]
Note, the manylinux images have been push with 2.0.20, and the tests here ran to completion with them.

**Review by ankith26 — APPROVED** [review]
LGTM! 🎉 Thanks! 👍

**Comment by Starbuck5** [comment]
> I left tests skipping, as apparently they are still broken on windows.

They are, I re checked. But it's bizarre, if I run the module test individually, it passes. But if I run them through the complete test suite they fail.

**Review by Starbuck5 — APPROVED** [review]
Thanks!

I've tested locally on Windows.

**Pull request merged**
