### PR TITLE
Additions to "examples" folder

### PR DESCRIPTION
**Pull request by Boinga15**
- Added a new example "trackers.py" to showcase Object-Oriented-Programming in Pygame.
- Did some grammar checking on the first comment in testsprite.py.

### CODE REVIEW

**Comment by MyreMylar** [comment]
I suspect this is going to fail one of the linters as I noticed some CamelCase where python prefers snake_case in the variable names. If it fails the linter CI - just put it through `black`.

Also, the linter CI is failing on everything at the minute, so we'll have to wait until the new-black-version-fixes PR goes through as well.

**Comment by novialriptide** [comment]
The grammar mistake should be a separate PR imo, but not a big deal.

About object oriented programming, isn't the examples directory supposed to just show what pygame is capable of? Object oriented programming is too general as many other examples already showcase this.

**Comment by Boinga15** [comment]
I didn't realize object oriented programming was used in other files (perhaps I didn't search hard enough through the already shown examples). I'll probably try create another PR with the grammar fixes as well. As for my program, I'll look through the current list of examples and see if it brings anything new to the table in regards to what Pygame is capable of. If not, I won't add it to the examples folder.

**Comment by illume** [comment]
> I didn't realize object oriented programming was used in other files (perhaps I didn't search hard enough through the already shown examples). I'll probably try create another PR with the grammar fixes as well. As for my program, I'll look through the current list of examples and see if it brings anything new to the table in regards to what Pygame is capable of. If not, I won't add it to the examples folder.

Ok, cool. I’ll close this PR to tidy things up.

An object oriented tutorial could be good. See the existing tutorials in the documentation with sprites… maybe the subject is already covered enough for you in those tutorials already. Or maybe not.

**Pull request closed without merging**
