### PR TITLE
Fix for python3+

### PR DESCRIPTION
**Pull request by penggrin12**
Old version was not working for python3+
It was because of print function

Old has that feature "print 'text'"
New one does not.
Now code look like this "print('text')"

### CODE REVIEW

**Comment by Starbuck5** [comment]
Hey, thanks for the spot.

I don't think adding your name as an editor is necessary though, other people have edited in the past without doing that.

**Review by MyreMylar — CHANGES_REQUESTED** [review]
There is a missed python 2 style print on line 84.

I would also change the credit to 'Updated code to Python 3: Akim Sidorov' if we are going to have it so it's clear what was changed.

**Comment by Starbuck5** [comment]
@novialriptide Can you take this over?

I.e. go through the tutorials in the docs and make sure things are using Python 3 syntax (like the print function)

**Comment by Starbuck5** [comment]
Fixed in #2984

**Pull request closed without merging**
