### PR TITLE
Update __init__.py with different code reformatting

### PR DESCRIPTION
**Pull request by SmashedFrenzy16**
This commit reformats the print statements and reformats them, making it easier to read.

### CODE REVIEW

**Comment by oddbookworm** [comment]
You've got the `.format` on the wrong part of the statement. Also, f-strings are generally the "easier" way to read, rather than trying to parse the older `str.format` syntax. f-strings are also far faster than `str.format` (or any other string formatting/concatenation technique). Because pygame's minimal supported version also supports f-strings, I think this reversion to an antiquated, slower format is unnecessary.

**Comment by SmashedFrenzy16** [comment]
Oh ok, thanks for the feedback @oddbookworm.

**Comment by SmashedFrenzy16** [comment]
I have updated the .format() to be on the right side of the print statement now.

**Comment by oddbookworm** [comment]
What I said still stands about using `str.format` rather than f-strings. I still am of the belief that going back to using the older, slower `str.format` syntax is not the appropriate move to make. It's generally harder to read, and it's slower than f-strings.

**Comment by MyreMylar** [comment]
Agreed. This change would be a backwards step.

**Pull request closed without merging**
