### PR TITLE
Fix FreeType SDL_RWops leak

### LINKED ISSUE #572: On windows os, this file handle will never be closed, this may cause python "IOError: [Errno 24] Too many open files" if fonts are created multiple times.
https://github.com/pygame/pygame/blob/f85590933bfa986300a2b38bd300eb42c05496df/src_py/freetype.py#L58

### PR DESCRIPTION
**Pull request by dlon**
Fixes #572. Not sure whether the first or second commit is cleaner. Added 2nd as the user may not expect pygame to close a stream that they passed to it? At least in CPython, files normally close when the ref count hits 0, so either works.

### CODE REVIEW

**Comment by illume** [comment]
Is adding a unit test for this possible?

**Comment by illume** [comment]
I guess your second commit would be better? Because it cleans up all the resources, whereas closing the file will just make sure the file is closed but will leave the objects around?

**Comment by illume** [comment]
@dlon thanks. So, do you think this is ok to merge now?

I guess that test will fail with pypy.

**Comment by dlon** [comment]
Yes

**Pull request merged**
