### PR TITLE
pygame.h is in _sdl2 parent directory

### PR DESCRIPTION
**Pull request by pmp-p**
this should be harmless but helps fixing static build for https://github.com/pygame/pygame/issues/718.

### CODE REVIEW

**Review by ankith26 — CHANGES_REQUESTED** [review]
Since this is a cython change, a cython files regen is needed in this PR. After installing cython with pip, run `python3 setup.py cython`

**Comment by pmp-p** [comment]
@ankith26 then it's probably better to postpone that one until cpython 3.11 + cython 3 is out 
as it only has sense for static build with webassembly.

**Review by MyreMylar — APPROVED** [review]
LGTM 👍 Just got to wait for 3.11

**Comment by Starbuck5** [comment]
I'd still rather regenerate the files, or just controller.c, just to keep the cython code and the generated code on the same page. It's no problem to have a huge diff because of it.

**Review by illume — APPROVED** [review]
👍 thanks

**Pull request merged**
