### PR TITLE
Event refactor docs/types

### PR DESCRIPTION
**Pull request by ankith26**
This is a WIP PR to do all docs and types for event-refactor PR stuff

### CODE REVIEW

**Comment by ankith26** [comment]
The only things left to do are
1. Docs and types for pygame.time.set_timer after we finalize it’s a API details
2. Make any changes if required to WINDOWEVENT docs, after it gets an API review

**Comment by illume** [comment]
Is there a behaviour change with event.post() returning a bool?

**Comment by ankith26** [comment]
There is no behavior change as such. Places where the function returns None, I have just made it to return True/False wherever appropriate. It’s a useful little addition, if you ask me. Because now people can know that the event did not get posted (because it was blocked)

And where the function used to raise errors before, that one has not been changed

**Comment by illume** [comment]
Very good. Thanks for the clarification.

**Review by illume — APPROVED** [review]
👍

**Pull request merged**
