### PR TITLE
Update ftfont.py to fix circular dependency

### PR DESCRIPTION
**Pull request by nelsonlove**
Moving the pygame.sysfont import to immediately before the SysFont function fixes the circular dependency issue with the font module on my M1 Mac. See https://github.com/pygame/pygame/issues/2500 for details.

### CODE REVIEW

**Comment by illume** [comment]
I don't understand this one... is someone able to explain how this fixes what it fixes?

**Review by llindstrom — APPROVED** [review]
The pull request has been tested on linux with python 3.9 and python 2.7. It solves the circular import problem when the SDL2_ttf based **pygame.font** extension module was not built, but the **pygame.freetype** module is available.

In this case, the font extension module is replaced with font.py, a copy of ftfont.py, as **pygame.ftfont** is designed as a **pygame.freetype** based backwards compatible alternative to **pygame.font**. The replacement module font.py imports **sysfont**, which in turn imports Font from font.py. If the Font class is not already present in the partially instantiated font.py an ImportError is raised with the potential circular import message.

**Comment by Starbuck5** [comment]
@nelsonlove It looks like you added some commits to this PR unintentionally.

**Comment by illume** [comment]
Yeah, It would be good to just include commits up to 0f86c84 in this PR.

**Comment by ubertao** [comment]
@nelsonlove Homebrew can be configured to install to locations other than `/opt/homebrew`.

Can we use the output of `brew config` to get the homebrew prefix dir instead of hardcode it as `/opt/homebrew`?

**Comment by andrewdstrain** [comment]
This patch fixes the circular dependency with regards to fonts on my M1 MacBook Air. The `pygame.examples.aliens` app works as expected.

In other news, `pygame.tests` still does not pass 100% - but that should probably be put as another issue once this one has been fixed.

**Comment by andrewdstrain** [comment]
This pull request does work... please read the comments I made in issue #2452.

Thank you!

**Comment by Starbuck5** [comment]
I believe the problem this patch solves was solved more simply in #2636 , so I'm going to close this.

**Comment by lemon-sh** [comment]
I know this is ancient, but this fixed the issue on my RPi, so maybe the issue is not really fixed?
```
>>> from pygame.font import Font
pygame 2.1.3.dev8 (SDL 2.26.1, Python 3.9.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
>>> Font
<class 'pygame.font.Font'>
```

**Pull request closed without merging**
