### PR TITLE
Add /analyze flag to appveyor build and fix some reported warnings

### PR DESCRIPTION
**Pull request by MyreMylar**
Related to this:
https://docs.microsoft.com/en-us/cpp/build/reference/analyze-code-analysis?view=vs-2019

and this issue:
https://github.com/pygame/pygame/issues/1328

Lets see if it runs on appveyor... (It does though you need to click through to see the interesting output)

Here is a dump of the output from running it locally:
[msvc_analyze_output.txt](https://github.com/pygame/pygame/files/4651633/msvc_analyze_output.txt)

### CODE REVIEW

**Comment by MyreMylar** [comment]
Though I might as well try and fix a few of the outputted warnings while I was doing this.

First up, a change to a macro that was spewing:

`warning C6246: Local declaration of '_module' hides declaration of the same name in outer scope.` over many places in the code base.

**Comment by MyreMylar** [comment]
Noticed that we had `INT_CHECK(x)` defined in multiple places in the code so moved it to  pgcompat.h and made sure we were using it in all the places that were previously doing a `PyLong_Check(x) || PyInt_Check(x)`

This was generating an Appveyor warning about both sides of an or being equal to the same thing (which they previously were on python 3).

**Comment by MyreMylar** [comment]
Don't want to make too many changes across too many files in one PR so I'll stop fiddling here I think and revisit with batches of fixes over time.

**Comment by MyreMylar** [comment]
Looks like the /external flags were only added midway through the life of MSVC 2017 and python only updated to MSVC 2019 after Python 3.8.3, so I added an extra appveyor build using 3.8.3 to see if that would take the /external flags (as my build does locally)

Related:
https://devblogs.microsoft.com/cppblog/broken-warnings-theory/
https://bugs.python.org/issue39789

**Comment by MyreMylar** [comment]
I've asked a query about why the 'experimental:external' flags generate warnings on appveyor here:

https://help.appveyor.com/discussions/problems/27377-command-line-warning-d9002-ignoring-unknown-option-experimentalexternal

**Comment by illume** [comment]
So the tests can run, I'm going to merge master in (which runs SDL1 tests too).

**Pull request merged**
