### PR TITLE
Fix draw.arc

### LINKED ISSUE #1663: Arcs with width values greater than 1 being drawn with tiny holes/gaps
Arcs drawn with width values greater than 1 may contain tiny holes/gaps. This is shown by the following code as the resulting arc contains tiny gaps where it should be a solid color.

    import pygame
    import time

    pygame.display.init()
    screen = pygame.display.set_mode((100, 100))
    rect = pygame.Rect((0, 0), (80, 70))
    rect.center = screen.get_rect().center

    pygame.draw.arc(screen, pygame.Color('yellow'), rect, 1, 2, 35)
    pygame.display.flip()

    time.sleep(10)
    pygame.display.quit()

Resulting arc with tiny gaps.

image

System details:

    os: windows 10 (64bit)
    python: 3.7.4 (64bit)
    pygame: 2.0.0.dev7 (SDL: 2.0.12)

**Related docs:** https://www.pygame.org/docs/ref/draw.html#pygame.draw.arc

### PR DESCRIPTION
**Pull request by MightyJosip**
This should fix #1663

### CODE REVIEW

**Comment by dr0id** [comment]
I really would like to review it but without any pointers it will take me forever to figure out what is actually done on each line. Could you provide some hints as how it works? 
From what I see it looks like there is some stepping algorithm used and many different cases and conditions.

**Comment by dr0id** [comment]
Looking for some hints I found this document: http://members.chello.at/~easyfilter/Bresenham.pdf

**Comment by dr0id** [comment]
It seems to work:
image

source see  #3020

**Comment by dr0id** [comment]
Spoken too early: There are some artefacts:
image

**Comment by MyreMylar** [comment]
Currently failing on windows due to these:

```
src_c/draw.c(1667): error C2220: warning treated as error - no 'object' file generated
src_c/draw.c(1667): warning C4244: '=': conversion from 'double' to 'int', possible loss of data
src_c/draw.c(1668): warning C4244: '=': conversion from 'double' to 'int', possible loss of data
src_c/draw.c(1669): warning C4244: '=': conversion from 'double' to 'int', possible loss of data
src_c/draw.c(1670): warning C4244: '=': conversion from 'double' to 'int', possible loss of data
src_c/draw.c(1673): warning C4244: '=': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1674): warning C4244: '=': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1675): warning C4244: '=': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1676): warning C4244: '=': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1689): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1693): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1703): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1705): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1719): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1731): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1744): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1755): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1757): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1768): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1772): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1784): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1793): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1795): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1808): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1811): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1826): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1830): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1850): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1853): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1858): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1863): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1877): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1883): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1895): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1901): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1921): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1934): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1936): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1945): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1947): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1961): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1972): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1975): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1994): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1996): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2002): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2007): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2020): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2022): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2033): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2041): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2043): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2057): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2068): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2073): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2087): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2096): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2098): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2117): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2119): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2131): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2145): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2164): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2169): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2186): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2202): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2208): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2219): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2225): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2226): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2228): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2242): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2254): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2267): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2269): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2311): warning C4244: '=': conversion from 'double' to 'int', possible loss of data
src_c/draw.c(2312): warning C4244: '=': conversion from 'double' to 'int', possible loss of data
src_c/draw.c(2313): warning C4244: '=': conversion from 'double' to 'int', possible loss of data
src_c/draw.c(2314): warning C4244: '=': conversion from 'double' to 'int', possible loss of data
src_c/draw.c(2317): warning C4244: '=': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2318): warning C4244: '=': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2319): warning C4244: '=': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2320): warning C4244: '=': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2333): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2337): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2347): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2349): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2363): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2375): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2388): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2399): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2401): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2412): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2416): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2428): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2437): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2439): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2452): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2455): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2470): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2474): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2494): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2497): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2502): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2507): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2521): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2527): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2539): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2545): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2565): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2578): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2580): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2589): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2591): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2605): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2616): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2619): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2638): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2640): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2646): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2651): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2664): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2666): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2677): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2685): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2687): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2701): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2[712](https://ci.appveyor.com/project/pygame/pygame/build/job/bcl1286i3kig2g4k#L712)): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2[717](https://ci.appveyor.com/project/pygame/pygame/build/job/bcl1286i3kig2g4k#L717)): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2[731](https://ci.appveyor.com/project/pygame/pygame/build/job/bcl1286i3kig2g4k#L731)): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2[740](https://ci.appveyor.com/project/pygame/pygame/build/job/bcl1286i3kig2g4k#L740)): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2[742](https://ci.appveyor.com/project/pygame/pygame/build/job/bcl1286i3kig2g4k#L742)): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2[761](https://ci.appveyor.com/project/pygame/pygame/build/job/bcl1286i3kig2g4k#L761)): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2[763](https://ci.appveyor.com/project/pygame/pygame/build/job/bcl1286i3kig2g4k#L763)): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2[775](https://ci.appveyor.com/project/pygame/pygame/build/job/bcl1286i3kig2g4k#L775)): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2[789](https://ci.appveyor.com/project/pygame/pygame/build/job/bcl1286i3kig2g4k#L789)): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2[808](https://ci.appveyor.com/project/pygame/pygame/build/job/bcl1286i3kig2g4k#L808)): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2[813](https://ci.appveyor.com/project/pygame/pygame/build/job/bcl1286i3kig2g4k#L813)): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2[830](https://ci.appveyor.com/project/pygame/pygame/build/job/bcl1286i3kig2g4k#L830)): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2[846](https://ci.appveyor.com/project/pygame/pygame/build/job/bcl1286i3kig2g4k#L846)): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2[852](https://ci.appveyor.com/project/pygame/pygame/build/job/bcl1286i3kig2g4k#L852)): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2863): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2869): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2870): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2872): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2886): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2898): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2911): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(2913): warning C4244: 'function': conversion from '__int64' to 'int', possible loss of data
src_c/draw.c(1654): warning C4244: 'initializing': conversion from '__int64' to 'double', possible loss of data
src_c/draw.c(1655): warning C4244: 'initializing': conversion from '__int64' to 'double', possible loss of data
src_c/draw.c(1657): warning C4244: 'initializing': conversion from '__int64' to 'double', possible loss of data
src_c/draw.c(1658): warning C4244: 'initializing': conversion from '__int64' to 'double', possible loss of dat
```

**Pull request closed without merging**
