### PR TITLE
Move threads.py out of its directory (minor update)

### PR DESCRIPTION
**Pull request by ankith26**

### CODE REVIEW

**Comment by ankith26** [comment]
The Import that LGTM is complaining about, is a required import

**Comment by illume** [comment]
It doesn't look like `Empty` is used to me. I think LGTM is correct.

**Comment by ankith26** [comment]
It is not used in the file, but is used when some other file does
from pygame.threads import Empty

Which is why I included the import again

**Comment by ankith26** [comment]
Ahh, just realised. 
Moving the file to the base directory will not work because threads module want some to import pythons time module, and pygame has it’s own time module, so it’s not going to import stuff correctly.
I’m gonna have to drop this PR

**Pull request closed without merging**
