### PR TITLE
Adding windowevent constants

### PR DESCRIPTION
**Pull request by ankith26**
This PR is adding the new SDL WINDOWEVENT constants

### CODE REVIEW

**Comment by ankith26** [comment]
I will add docs for these changes as part of #2149

**Review by MyreMylar — APPROVED** [review]
Thanks for the contribution. 

I suspect later we may need to document and test these events, assuming they are all generated & working on the pygame side, but this is a good change that'll make it easier to do those things.

👍 🎉

**Comment by ankith26** [comment]
Yes, I have seen that WINOWEVENT events are consistently being generated, and the event attribute is always set to the respective integer, which I see why I have opened the PR to add these constants.

I’m aldready working on docs for these, and maybe we can add a few unittests for these too

**Review by illume — APPROVED** [review]
👍 thanks. Nice improvement.

I agree, docs and tests can come later in further PRs.

**Pull request merged**
