### PR TITLE
Add pygame logo to README

### PR DESCRIPTION
**Pull request by ayushbisht2001**

### CODE REVIEW

**Review by ankith26 — APPROVED** [review]
The readme has the logo now.
This PR is looking good
Thanks 👍

**Comment by ayushbisht2001** [comment]
It's my pleasure to contribute  here....

**Comment by ayushbisht2001** [comment]
how long would it take to get merged with the main branch...... 
Have I missed  something  or made something wrong ?

**Comment by ankith26** [comment]
No, You have done it correctly.
Just waiting for others to give some reviews too before merging
(Since this is not a code change, this should get merged relatively quickly)

**Comment by ayushbisht2001** [comment]
ok ,  that's fine .... 
Thanks for your kind responses....

**Comment by zoldalma999** [comment]
Thanks for contributing to pygame!

I am not a hundred percent sure but this might not show up on other sites (like pypi). Can you try using [this](https://raw.githubusercontent.com/pygame/pygame/main/docs/pygame_logo.gif) link instead?

**Comment by MyreMylar** [comment]
See this link for more details on what @zoldalma999 is referring to:
https://stackoverflow.com/questions/41983209/how-do-i-add-images-to-a-pypi-readme-that-works-on-github

**Comment by ayushbisht2001** [comment]
thanks for suggestions ..... I have edited the image path .I  Hope it might works.....

**Review by zoldalma999 — APPROVED** [review]
Looks good to me! 👍

**Review by ankith26 — APPROVED** [review]
Nice, I guess I can merge this one now :)

**Pull request merged**
