### PR TITLE
Unit test for image.save_extended()

### PR DESCRIPTION
**Pull request by anguye13**
Checking to see if image.save_extended() works as intended

### CODE REVIEW

**Comment by anguye13** [comment]
save_extend seems to raise "pygame.error: Unrecognized image type" for all image types that aren't .jpg or .png

**Comment by MyreMylar** [comment]
Looking at the [docs ](https://www.pygame.org/docs/ref/image.html#pygame.image.save)for `.save()` which I assume calls `save_extended()` pygame supports saving in these formats:

- BMP
- TGA
- PNG
- JPEG

It's possible that bmp saving is taken care of inside `save()` and not `save_extended()` as I think this is how it happens for load. I'm not sure about TGA files. Pygame definitely doesn't support saving in all of the types listed in your test so we should probably scope the testing correctly first.

**Comment by anguye13** [comment]
Updated the error file types to only include .bmp and .tga and added tests to show save_extended() successfully work on .jpg and .png

**Comment by MyreMylar** [comment]
I double checked the C code and indeed the regular 'save' function of the image module loads both .bmp and .tga file types by itself only passing .jpg (and .jpeg) or .png file types to save_extended().

**Review by MyreMylar — APPROVED** [review]
Approving this test 🎉 👍

**Pull request merged**
