### PR TITLE
Fixing docs for `pygame.MOUSEBUTTONDOWN` and `pygame.MOUSEBUTTONUP` events

### LINKED ISSUE #3612: `pygame.MOUSEBUTTONUP` and `pygame.MOUSEBUTTONDOWN` docs don't fully describe the behavior of those events when the mouse wheel is scrolled
Discovered by @lucysir\#3139 (https://github.com/kadir014) in discord. When the mouse wheel is scrolled fast, the docs only say this:

> The mouse wheel will generate pygame.MOUSEBUTTONDOWN and pygame.MOUSEBUTTONUP events when rolled. The button will be set to 4 when the wheel is rolled up, and to button 5 when the wheel is rolled down.

If the wheel is scrolled quickly enough, multiple events are created, and each one has an `event.button` attribute that is 2 higher than the previous.

sample code:
```
import pygame

pygame.init()

screen = pygame.display.set_mode((500, 500))

running = True
while running:
    print("===")
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

        if event.type == pygame.MOUSEBUTTONUP:
            print(event.button)

    pygame.time.delay(100)
```
sample output
```
===
4
6
===
4
6
===
4
===
===
===
===
===
===
4
===
4
6
8
10
12
===
```

I plan on making a PR soon to update the documentation.
(ignore that github automatically linked something in the tag for sirlucy. That was not intentional)

### PR DESCRIPTION
**Pull request by oddbookworm**
This is a PR to fix #3612

### CODE REVIEW

**Comment by ankith26** [comment]
Uhhhh, I'm not sure whether this is intended behaviour. It could be a bug

**Comment by oddbookworm** [comment]
> Uhhhh, I'm not sure whether this is intended behaviour. It could be a bug

I thought the same, but the behavior is present as far back as `2.0.3`, so I was figuring that at this point fixing it might break someone's project. So I thought "let's at least document it"

**Comment by oddbookworm** [comment]
Plus, with `pygame.MOUSEWHEEL` a thing now, isn't this functionality only being kept around for compat?

**Comment by MyreMylar** [comment]
Should we close this now in favour of the fix?

**Comment by oddbookworm** [comment]
> Should we close this now in favour of the fix?

I think so, so I'll close it now

**Comment by oddbookworm** [comment]
Relevant fix https://github.com/pygame/pygame/pull/3642

**Pull request closed without merging**
