### PR TITLE
overview.rst -> 개요.rst

### PR DESCRIPTION
**Pull request by novialriptide**

### CODE REVIEW

**Review by illume — APPROVED** [review]
Thanks.

(google translate agrees)

**Review by ankith26 — APPROVED** [review]
Thanks! 🍨 🎉

**Review by Starbuck5 — CHANGES_REQUESTED** [review]
This breaks the link from the homepage to this tutorial, wouldn't it?

**Comment by novialriptide** [comment]
Oof

**Comment by novialriptide** [comment]
@Starbuck5 Could you link which link this PR would break?

**Comment by novialriptide** [comment]
Should this PR stay open?

**Review by Starbuck5 — APPROVED** [review]

**Pull request merged**
