### PR TITLE
Add kwarg support for event.c, display.c, color.c, font.c, and rect.c

### PR DESCRIPTION
**Pull request by jonotassia**
In reference to issue https://github.com/pygame/pygame/issues/808, I've added kwargs to the below files where relevant. Take a look and let me know if this needs any changes before being approved. Updates made affected the following functions:

Event.c

-  pg_event_init(pgEventObject *self, PyObject *args, PyObject *kwargs)

Display.c

- pg_gl_set_attribute(PyObject *self, PyObject *arg, PyObject *kwarg)
- pg_gl_get_attribute(PyObject *self, PyObject *arg, PyObject *kwarg)
- pg_set_palette(PyObject *self, PyObject *args, PyObject *kwargs)
- pg_set_gamma(PyObject *self, PyObject *arg, PyObject *kwarg) - Noticed after the fact that this was actually deprecated. I can remove if desired!
- pg_set_gamma_ramp(PyObject *self, PyObject *arg, PyObject *kwarg) - Noticed after the fact that this was actually deprecated. I can remove if desired!
- pg_set_caption(PyObject *self, PyObject *arg)

Color.c

- _color_correct_gamma(pgColorObject *color, PyObject *args, PyObject *kwargs) 
- _color_set_length(pgColorObject *color, PyObject *args, PyObject *kwargs) - Deprecated, can remove changes if desired

Font.c

- No changes made - The only function that appears to take args is get_ttf_version, which is already accounted for

Rect.c
- Modified
  - pg_rect_clipline(pgRectObject *self, PyObject *args, PyObject *kwargs)
  - pg_rect_scale_by(pgRectObject *self, PyObject *args, PyObject *kwargs)
  - pg_rect_scale_by_ip(pgRectObject *self, PyObject *args, PyObject *kwargs)
  - pg_rect_unionall(pgRectObject *self, PyObject *args,  PyObject *kwargs)
  - pg_rect_unionall_ip(pgRectObject *self, PyObject *args,  PyObject *kwargs)
  - pg_rect_collidelist(pgRectObject *self, PyObject *args,  PyObject *kwargs)
  - pg_rect_collidelistall(pgRectObject *self, PyObject *args, PyObject *kwargs)
  - pg_rect_collidedict(pgRectObject *self, PyObject *args,  PyObject *kwargs)
  - pg_rect_collidedictall(pgRectObject *self, PyObject *args, PyObject *kwargs)
- Did not modify since it calls pgRect_FromObject rather than PyArg_ParseTupleAndKeywords
  - pg_rect_clip(pgRectObject *self, PyObject *args) 
  - pg_rect_clamp(pgRectObject *self, PyObject *args)
  - pg_rect_fit(pgRectObject *self, PyObject *args)
  - pg_rect_clamp_ip(pgRectObject *self, PyObject *args)
  - pg_rect_update(pgRectObject *self, PyObject *args)
  - pg_rect_union(pgRectObject *self, PyObject *args)
  - pg_rect_union_ip(pgRectObject *self, PyObject *args)
  - pg_rect_colliderect(pgRectObject *self, PyObject *const *args, Py_ssize_t nargs)
  - _pg_rect_contains(pgRectObject *self, PyObject *arg)
- Did not modify since it calls pg_TwoIntsFromObj rather than PyArg_ParseTupleAndKeywords
  - pg_rect_move(pgRectObject *self, PyObject *args)
  - pg_rect_move_ip(pgRectObject *self, PyObject *args)
  - pg_rect_inflate(pgRectObject *self, PyObject *args)
  - pg_rect_inflate_ip(pgRectObject *self, PyObject *args)
  - pg_rect_collidepoint(pgRectObject *self, PyObject *args)

Associated documentation in display.rst and event.rst have been updated as well.

For the rect.c kwarg support, I'm happy to take a pass at updating the ones I called out as unmodified if that's necessary following the approach in #1219. I am unfamiliar with pgRect_FromObject and pg_TwoIntsFromObj functions so didn't want to make any assumptions that this was necessary given that the changes from 1219 did not end up getting incorporated with main.

### CODE REVIEW

**Review by ankit-gautam23 — APPROVED** [review]
LGTM

**Comment by narilee2006** [comment]
> LGTM

@ankit-gautam23 lol
image

**Comment by illume** [comment]
Hello! 

Very cool, this is a nice improvement.

There's an issue here with color.c, where warnings are treated as errors on CI.

https://github.com/pygame/pygame/actions/runs/4741926090/jobs/8475778557?pr=3805#step:4:2296

```c
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -D_REENTRANT -I/usr/X11R6/include -I/usr/include/SDL2 -I/usr/include/python3.8 -c src_c/color.c -o build/temp.linux-x86_64-3.8/src_c/color.o -Wall -Wno-error=unknown-pragmas -Werror
    src_c/color.c:759:1: error: conflicting types for ‘_color_correct_gamma’
      759 | _color_correct_gamma(pgColorObject *color, PyObject *args, PyObject *kwargs)
          | ^~~~~~~~~~~~~~~~~~~~
    src_c/color.c:90:1: note: previous declaration of ‘_color_correct_gamma’ was here
       90 | _color_correct_gamma(pgColorObject *, PyObject *);
          | ^~~~~~~~~~~~~~~~~~~~
    src_c/color.c: In function ‘_color_correct_gamma’:
    src_c/color.c:767:33: error: passing argument 2 of ‘_PyArg_ParseTuple_SizeT’ from incompatible pointer type [-Werror=incompatible-pointer-types]
      767 |     if (!PyArg_ParseTuple(args, kwargs, "d", keywords, &_gamma)) {
          |                                 ^~~~~~
          |                                 |
          |                                 PyObject * {aka struct _object *}
    In file included from /usr/include/python3.8/Python.h:137,
                     from src_c/_pygame.h:35,
                     from src_c/pygame.h:30,
                     from src_c/color.c:44:
    /usr/include/python3.8/modsupport.h:40:46: note: expected ‘const char *’ but argument is of type ‘PyObject *’ {aka ‘struct _object *’}
       40 | PyAPI_FUNC(int) PyArg_ParseTuple(PyObject *, const char *, ...);
          |                                              ^~~~~~~~~~~~
    src_c/color.c: At top level:
    src_c/color.c:1701:1: error: conflicting types for ‘_color_set_length’
     1701 | _color_set_length(pgColorObject *color, PyObject *args, PyObject *kwargs)
          | ^~~~~~~~~~~~~~~~~
    src_c/color.c:92:1: note: previous declaration of ‘_color_set_length’ was here
       92 | _color_set_length(pgColorObject *, PyObject *);
          | ^~~~~~~~~~~~~~~~~
    src_c/color.c: In function ‘_color_set_length’:
    src_c/color.c:1713:33: error: passing argument 2 of ‘_PyArg_ParseTuple_SizeT’ from incompatible pointer type [-Werror=incompatible-pointer-types]
     1713 |     if (!PyArg_ParseTuple(args, kwargs, "i", keywords, &clength)) {
          |                                 ^~~~~~
          |                                 |
          |                                 PyObject * {aka struct _object *}
    In file included from /usr/include/python3.8/Python.h:137,
                     from src_c/_pygame.h:35,
                     from src_c/pygame.h:30,
                     from src_c/color.c:44:
    /usr/include/python3.8/modsupport.h:40:46: note: expected ‘const char *’ but argument is of type ‘PyObject *’ {aka ‘struct _object *’}
       40 | PyAPI_FUNC(int) PyArg_ParseTuple(PyObject *, const char *, ...);
          |                                              ^~~~~~~~~~~~
    src_c/color.c: At top level:
    src_c/color.c:90:1: error: ‘_color_correct_gamma’ used but never defined [-Werror]
       90 | _color_correct_gamma(pgColorObject *, PyObject *);
          | ^~~~~~~~~~~~~~~~~~~~
    src_c/color.c:92:1: error: ‘_color_set_length’ used but never defined [-Werror]
       92 | _color_set_length(pgColorObject *, PyObject *);
          | ^~~~~~~~~~~~~~~~~
    src_c/color.c:1701:1: error: ‘_color_set_length’ defined but not used [-Werror=unused-function]
     1701 | _color_set_length(pgColorObject *color, PyObject *args, PyObject *kwargs)
          | ^~~~~~~~~~~~~~~~~
    src_c/color.c:759:1: error: ‘_color_correct_gamma’ defined but not used [-Werror=unused-function]
      759 | _color_correct_gamma(pgColorObject *color, PyObject *args, PyObject *kwargs)
          | ^~~~~~~~~~~~~~~~~~~~
    cc1: all warnings being treated as errors
```

**Comment by jonotassia** [comment]
Thanks for taking a look. Based on the error message above, looks like it is just caused by the incongruency between parameters in the declaration and definition of the _color_correct_gamma and _color_set_length.

Declaration:

`_color_correct_gamma(pgColorObject *, PyObject *);` - Line 90
`_color_set_length(pgColorObject *, PyObject *);` - Line 92

Definition:
`_color_correct_gamma(pgColorObject *color, PyObject *args, PyObject *kwargs)` - Line 759
`_color_set_length(pgColorObject *color, PyObject *args, PyObject *kwargs)` - Line 1701

I took a look at draw.c and the file is structured a little different from color.c, so wasn't able to follow the exact same solution as was used there. I went ahead and updated the declarations to include the third parameter and pushed again. Let me know if you foresee any issues with this.

**Comment by illume** [comment]
Hey hey. 

thanks for that. It seems like it's having some more issues:

- The code needs formatting with clang-format. If you run `python setup.py format` it should format it for you. If you have clang-format installed.
- color.c is erroring out still because of the warnings...


```c
  src_c/color.c: In function ‘_color_correct_gamma’:
  src_c/color.c:767:33: error: passing argument 2 of ‘_PyArg_ParseTuple_SizeT’ from incompatible pointer type [-Werror=incompatible-pointer-types]
    767 |     if (!PyArg_ParseTuple(args, kwargs, "d", keywords, &_gamma)) {
        |                                 ^~~~~~
        |                                 |
        |                                 PyObject * {aka struct _object *}
  In file included from /usr/include/python3.10/Python.h:126,
                   from src_c/_pygame.h:35,
                   from src_c/pygame.h:30,
                   from src_c/color.c:44:
  /usr/include/python3.10/modsupport.h:40:46: note: expected ‘const char *’ but argument is of type ‘PyObject *’ {aka ‘struct _object *’}
     40 | PyAPI_FUNC(int) PyArg_ParseTuple(PyObject *, const char *, ...);
        |                                              ^~~~~~~~~~~~
  src_c/color.c: In function ‘_color_set_length’:
  src_c/color.c:1713:33: error: passing argument 2 of ‘_PyArg_ParseTuple_SizeT’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   1713 |     if (!PyArg_ParseTuple(args, kwargs, "i", keywords, &clength)) {
        |                                 ^~~~~~
        |                                 |
        |                                 PyObject * {aka struct _object *}
  In file included from /usr/include/python3.10/Python.h:126,
                   from src_c/_pygame.h:35,
                   from src_c/pygame.h:30,
                   from src_c/color.c:44:
  /usr/include/python3.10/modsupport.h:40:46: note: expected ‘const char *’ but argument is of type ‘PyObject *’ {aka ‘struct _object *’}
     40 | PyAPI_FUNC(int) PyArg_ParseTuple(PyObject *, const char *, ...);
        |                                              ^~~~~~~~~~~~
  cc1: all warnings being treated as errors
```

```c
src_c/color.c(767): error C2220: warning treated as error - no 'object' file generated
src_c/color.c(767): warning C4133: 'function': incompatible types - from 'PyObject *' to 'const char *'
src_c/color.c(1713): warning C4133: 'function': incompatible types - from 'PyObject *' to 'const char *'
```

**Comment by illume** [comment]
The new arguments also added to the type stubs, and docs. We also need to add tests for them all.

It's quite a lot of work... If you want to continue on it let me know? Otherwise we can also pass it on to someone else to do these other parts.

**Comment by jonotassia** [comment]
Thanks for the feedback, it is much appreciated. 

Apologies for missing the steps about running setup.py. I should have caught that on the contribution wiki.

Additionally, I think I've caught the bug in color.c, which was just that it was using `PyArg_ParseTuple` rather than `PyArg_ParseTupleAndKeywords`.

My local version is struggling a bit today, so I'm going to get it fixed as soon as possible and then I will run `python setup.py format` and make sure everything looks good before I push again.

I'm definitely happy to keep working on this as much as I can. Based on your sugestions above, I just want to make sure that I'm hitting the correct things:

1. Updating stubs for affected files:
    1. I'm not super familiar with stub types, but based on some research, it sounds like this is essentially a static typing equivalent for Python much like a header file in C++. I was looking a some other .pyi files as references, but it didn't seem like kwargs were explicitly called out and typed in any of the others. I did see [PEP 692](https://peps.python.org/pep-0692/) outlines a means to type hint kwargs if it was something we needed to do. Let me know and I'm happy to give it a go.
2. Updating docs:
     1. I used the draw.rst docs as an example and added `.. versionchanged:: 2.3.1 Added support for keyword arguments.` to each affected function. Anything else you would expect to see there?
3. Updating tests:
     1. I imagine this will take a bit of time, but more than happy to work through it over the next week or two. I think there are some good test cases to use as reference in draw_test (ie `test_polygon__kwarg_invalid_name`) for how to kwargify the test cases, so I'll plan to use those for reference.

Once everything looks good with this pull request, I'll create a separate checklist outlining the proposed changes so we have a tracking mechanism, then I'll link that out in a post in #808, if that works.

**Comment by jonotassia** [comment]
Also, perhaps unrelated but wanted to flag it: it looks like there is an issue when I run the test cases for mixer. It didn't seem related to any of the changes I made, so I wanted to flag it in case this was a bug in main. Let me know if you want me to put in an issue for it if you think it is an actual issue and I can do that.

```
======================================================================
FAIL: test_get_init__returns_exact_values_used_for_init (test.mixer_test.MixerModuleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\jtass\source\repos\pygame\test\mixer_test.py", line 100, in test_get_init__returns_exact_values_used_for_init
    self.assertEqual(tuple(init_conf.values()), mixer_conf)
AssertionError: Tuples differ: (11025, -16, 1) != (11025, -16, 2)

First differing element 2:
1
2

- (11025, -16, 1)
?              ^

+ (11025, -16, 2)
?              ^


----------------------------------------------------------------------
Ran 1816 tests in 46.094s

FAILED (failures=1)

```

**Comment by illume** [comment]
I think that mixer test is buggy. Thanks for mentioning it.

When you start the mixer, you request the settings. But it can be that a sound system doesn’t support what you request… and it gives you back something close to what you request but not equal.

**Comment by illume** [comment]
Hi.

Have a look at this one: https://github.com/pygame/pygame/pull/3843 it is adding a new function so it shows all of the changes required.

1. Stubs. See other stubs in buildconfig/stubs Check the existing keyword argument names match the docs and what is used in the .c files.
2. Docs. See other functions in the docs with keyword params.
3. tests. Yeah, it will need tests before merging it in.
4. new branch. It might be a better idea to start a new pull request doing just one function, and finish that one function all the way through. It's easier to manage than doing lots at once.

**Comment by illume** [comment]
@jonotassia ps. I 'fixed' that mixer issue in https://github.com/pygame/pygame/pull/3846 (by commenting out the test... since it didn't really make sense). Thanks again for the report.

**Comment by jonotassia** [comment]
I'm going to close this PR now and instead use #3852 as a tracking tool for this, with one PR per function, which I will link out from there! Thanks for all the feedback so far!

**Pull request closed without merging**
