### PR TITLE
Aaline Python-algo & tests

### PR DESCRIPTION
**Pull request by e1000**
Hi there,

again I try to progress on **aaline** issues. 

This branch contains only python-code modification (algorithm & tests), however it still segfaults with
```
SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=disk python test/draw_test.py -v
```

So, it seems, the error must come from somewhere else, right? And I have no clue where to look...
Anyone has a hint or solution ?

### CODE REVIEW

**Comment by e1000** [comment]
hm, I can't reproduce the `FAIL: test_path_data_validation` that you show. And I still get the 
mentionned errors with `SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=disk` : 
```
$ SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=disk python test/draw_test.py 
pygame 1.9.5.dev0
Hello from the pygame community. https://www.pygame.org/contribute.html
xxxx..Fatal Python error: (pygame parachute) Segmentation Fault

Current thread 0x00007ff851471700 (most recent call first):
  File "test/draw_test.py", line 295 in test_color_validation
  File "/usr/lib/python3.5/unittest/case.py", line 601 in run
  File "/usr/lib/python3.5/unittest/case.py", line 649 in __call__
  File "/usr/lib/python3.5/unittest/suite.py", line 122 in run
  File "/usr/lib/python3.5/unittest/suite.py", line 84 in __call__
  File "/usr/lib/python3.5/unittest/suite.py", line 122 in run
  File "/usr/lib/python3.5/unittest/suite.py", line 84 in __call__
  File "/usr/lib/python3.5/unittest/runner.py", line 176 in run
  File "/usr/lib/python3.5/unittest/main.py", line 255 in runTests
  File "/usr/lib/python3.5/unittest/main.py", line 94 in __init__
  File "test/draw_test.py", line 837 in <module>
Aborted
```
I haved tried to use `git rebase` to have a nicer pull-request but it seems, this doesn't work...

**Comment by dlon** [comment]
This might help:

git rebase origin/master master
git rebase master aaline-pyalgo

(or whatever this remote is called instead of "origin")

Maybe deleting the build directory and recompiling would fix the segfault.

**Comment by illume** [comment]
@charlesej started a new PR about some line test improvements at https://github.com/pygame/pygame/pull/799 but maybe we should try and help @e1000 get this one merged first.

Seems the branch is a bit messed up. @e1000 have you done anything further? If not, I could try and fix this branch somehow.

**Comment by charlesej** [comment]
I thought this PR and PR #611 were abandoned. I just submitted PR #802 to fix the aaline issue and opened #801 to track some aaline issues with `draw_py.py`

**Comment by illume** [comment]
Thanks for fixing the branch @dlon

**Pull request merged**
