### PR TITLE
Implementation of Vector2.from_polar and ClassObjectMethod descriptor

### PR DESCRIPTION
**Pull request by joaquin30**
Another possible implementation of #3734.

### CODE REVIEW

**Comment by illume** [comment]
The lint error is because of clang-format. If you install that, and then format it should be good. Then you can run before checking:

`python3 setup.py lint`

**Comment by illume** [comment]
The windows compilation error can be seen here: https://ci.appveyor.com/project/pygame/pygame/builds/46412174/job/bhnaqycrhpa09l20#L763

> src_c/math.c(4345): error C2099: initializer is not a constant

**Comment by joaquin30** [comment]
For math.pyi I checked some code with mypy and it seems to output the correct errors, except when using `Vector2.from_polar(Vector2(), (1,1))` (shows no errors), but it gives a syntax error using python. The problem is the test "Ubuntu sdist / build (ubuntu-22.04) (pull_request)", but if I use `@classmethod` or `@staticmethod` it will fail further tests, and mypy doesn't work correctly. Maybe we should just leave it as it is?

**Comment by illume** [comment]
Nice progress.

There seems to be an issue with the mypy stubtest.
https://github.com/pygame/pygame/actions/runs/4355791723/jobs/7612896124#step:6:19

```
  cd buildconfig/stubs
  python3 -m pip install mypy==0.982
  python3 -m mypy.stubtest pygame --allowlist mypy_allow_list.txt
```

```
pygame/math.pyi:223: error: Self argument missing for a non-static method (or an invalid type for self)
pygame/math.pyi:233: error: A function returning TypeVar should receive at least one argument containing the same Typevar
pygame/math.pyi:233: note: Consider using the upper bound "_GenericVector" instead
pygame/math.pyi:325: error: Self argument missing for a non-static method (or an invalid type for self)
pygame/math.pyi:325: error: A function returning TypeVar should receive at least one argument containing the same Typevar
pygame/math.pyi:325: note: Consider using the upper bound "_GenericVector" instead
```

**Comment by illume** [comment]
> For math.pyi I checked some code with mypy and it seems to output the correct errors, except when using Vector2.from_polar(Vector2(), (1,1)) (shows no errors), but it gives a syntax error using python. The problem is the test "Ubuntu sdist / build (ubuntu-22.04) (pull_request)", but if I use @classmethod or @staticmethod it will fail further tests, and mypy doesn't work correctly. Maybe we should just leave it as it is?

Did you try using cls as the first argument for the class method? https://docs.python.org/3/library/functions.html?highlight=classmethod#classmethod

**Comment by joaquin30** [comment]
OK, I think i have a workaround:

~~~pyi
from typing_extensions import Protocol

# Not defined in code, only for type checking from_polar ClassObjectMethod
class _from_polar_protocol(Protocol):
    def __call__(self, value: Tuple[float, float]) -> Optional[_TVec]: ...

class Vector2(_GenericVector):
    from_polar: _from_polar_protocol
~~~

I tried the test and type-checking some code and seems that it works. Also, i can't use `@classmethod` or `@staticmethod` because it shows an error that the method is not a classmethod at runtime.

**Review by illume — APPROVED** [review]
Thanks 🎈 🎉

**Pull request merged**
