### PR TITLE
event.get speedup, timer fixes

### PR DESCRIPTION
**Pull request by ankith26**
Keeping a list here of the issues that have been confirmed working by @illume manually testing.

- [x] #1236 unicode keydown field when mashing 4 keys at once. Adds unicode field to keyup event.
- [x] #1238 posting keydown events fills the fields.
- [x] #1524
- [x] #1550 set_event_timer Event param (needs testing).
- [x] #2146
- [x] #2214 WINDOWEVENT event name change (needs testing, and API review).
- [x] #2319 event.get(type) does not return a list of all events posted
- [x] #2347 pygame.time.set_timer() num_events/loops param naming needs to be decided.
- [x] #2378 unicode keydown field when mashing 4 keys at once

A list of open tasks to do (I will move these to other issues later)

- [x] document "Add unicode field to keyup event."
- [x] add type for "Add unicode field to keyup event."
- [ ] docs, types for set_event_timer event param.
- [x] WINDOWEVENT event name change docs, types, testing, and API review.
- [ ] pygame.time.set_timer() accept numevents argument docs, types
- [ ] pygame.event.post() returning bool docs, types
- [ ] a unit test for event.get(type) is needed. See test case in #2319
- [ ] test for end event allowing gap-less playback. Does grabing the GIL in the end callback cause a problem for this?

----
@illume 
This PR does some more event-refactor stuff.
As suggested by you. I will be breaking my mega PR into seperate PR to make reviews easier.

Coming to the topic of this PR, I did some more event.get speed up stuff, so pygame.event.get is roughly 3-4 times faster than 2.0.0

I set an event buffer for SDL events to speed stuff up. The downside to this idea is that one call to pygame event.get cannot return more than 128 events at a time (that number is customizable, though)

I was also playing around with speeding up python object creation, which you have mentioned are going to be a bit on the slower side.
And you have correctly predicted that one, I tried a hacky batch allocation of python objects. And I got a 5-6 times speed up.
But that was a too hacky hyperoptimisation. And it created other issues, particularly, object dealloc issues, segfaults etc. 
So I dropped that one (but I am still open to ideas on how to speed up PyObject allocations)

I did some timer fixes as well

### CODE REVIEW

**Comment by ankith26** [comment]
Python 3.7.3
SDL 2.0.9

Posting 120 events (100 loops)
Pygame 2.0.0
Average: 876.5292600128305
This Branch
Average: 123.04630001381156

Graph to treat your eyes
Figure_1

**Comment by illume** [comment]
> Graph to treat your eyes

treat appreciated :)

**Comment by ankith26** [comment]
So can I merge this into my main PR?
If any discussion needs to be done on this. It can be done here, before merging.

**Comment by illume** [comment]
Yeah, let's discuss here. I haven't had a chance to read through it properly or test it yet.

I wonder if there can be no extra lost events because of the 128 limit, or if that should be handled somehow? Events should be drained between pumps, so it appears conceptually that there will be lost events in some cases. But I haven't looked at it properly yet.

**Comment by ankith26** [comment]
That won’t be a problem. Because the events that are not collected in a call to that function will be collected in the next call to that function. Because events don’t get lost just like that. Pumping events only put new events on the queue.

This limit will be a little bit of an issue, incase someone is dealing with a large number of events. Then again, that’s a very tiny minority. And the advantages of the speed up outweighs that

**Comment by illume** [comment]
Yeah, as well as a change of semantics, it leaks. I'll explain the leak...

Every frame, 
- post a large number of events more than 128. Let's use 2000 events for example.
- call event.get(), getting 128 events, leaving 1872 on the SDL queue.

It needs to drain all the events every time it's called to keep the semantics of the call and prevent leaks.

**Comment by ankith26** [comment]
Hmm I get it now. I will try to remove this limitation ASAP, and rewrite some code

**Comment by ankith26** [comment]
I fixed that :)
The only reason I kept the limit before, was I was trying to optimize stuff. But now, it works like before, and it’s performance has not been affected too much. 
So thats good.

Side note: I will be taking a break from github for the whole of 2021. So you all will not see me for a year or so. I’m gonna miss pygame and the pygame community. I will be back after a year, though.
So that means I have just 2 weeks now to wrap up my PRs and get them merged. I would not want to leave any of them in an unfinished state.

**Comment by illume** [comment]
> But now, it works like before, and it’s performance has not been affected too much. So thats good.

Nice one :)

> Side note: I will be taking a break from github for the whole of 2021. So you all will not see me for a year or so. I’m gonna miss pygame and the pygame community. I will be back after a year, though. So that means I have just 2 weeks now to wrap up my PRs and get them merged. I would not want to leave any of them in an unfinished state.

Yeah, cool. I guess we can manage that. The main thing is to go through the list of issues, and if there is a reproducer/test in there run it to check. I'm waiting for the SDL 2.0.14 release before doing pygame 2.0.2, but after that we can merge this one in. It's held up by one bug https://discourse.libsdl.org/t/kmsdrm-using-atomic-mode-setting-breaks-gpu-compatibility/28372/8 so I guess SDL 2.0.14 will be released "soon".

If you need a reference letter for linkedin, work, or school email me and I can write one up. Hope your next year is fun, whatever it is you're up to :)

**Comment by ankith26** [comment]
Thanks :)
Well I have figured that I need to focus more on my higher education stuff. 

> If you need a reference letter for linkedin, work, or school email me and I can write one up. Hope your next year is fun, whatever it is you're up to :)

Thanks. I really appreciate it. But I don’t need it for now :)

**Comment by illume** [comment]
I added a checklist for me to run through testing for the issue list from the other PR here. The second is a list of open tasks which I'll move to another issue later.

**Comment by illume** [comment]
>  Well I have figured that I need to focus more on my higher education stuff.

Wise plan.

**Comment by illume** [comment]
I went through and manually tested them where I could. I still need to manually test a few of them, because there wasn't already some easy test code in the issues I could use.

**Comment by ankith26** [comment]
I have went through the issues that still need ticks, and have left some comments on those

**Comment by ankith26** [comment]
Added some unit tests in latest commit. Also improvised a few old ones

**Comment by ankith26** [comment]
Those were some nasty typos. Fixed them :)

**Review by illume — APPROVED** [review]
👍 great.

We can merge this in to main, after the other one is merged in.

**Comment by ankith26** [comment]
Or we could merge this into the other one, and then merge that.
I still have a little thing to add, though

**Comment by ankith26** [comment]
Latest commit fixes a GIL deadlock that would happen when pygame.quit() was called when the python interpreter is not finalizing.
As you can see, I fixed some other code in rwobject.c that was acquiring the GIL, and returning before releasing the GIL.
I also did a few more minor changes in my code, so now everything is working :)

**Comment by illume** [comment]
That's good news about the timing and the GIL tests you did! (https://github.com/pygame/pygame/pull/2357#issuecomment-748795180) I just want to make sure the use case of the end event works ok. I added a task to the list above to make an issue for that test. It shouldn't stop a merge of these event PRs.

So, are you happy now with everything event related? Any open things left before merge? Anything you'd like me to test? I'd probably like to merge this in 'soon' if you are ok with it. Then do a 2.0.1.dev2 pre-release with SDL2 (which looks like it's on for a release tomorrow/today). I'll start preparing the other things, and await your response on if we should merge or not.

**Comment by ankith26** [comment]
Well I would love this to get merged ASAP too.
Just to one last thing kept me thinking - #2214 

That one could be addressed later too, that’s not a priority. 

We could probably merge this PR into the main one, and then merge the main one into pygame main

If any fixes or stuff need to be done. I can open another PR soonish
(Still have free time for 1-2 more weeks)

**Comment by illume** [comment]
Ok, if it's not a show stopper... I'll do the merging now :)

**Pull request merged**
