### PR TITLE
Fix pixelarray error handling issue

### LINKED ISSUE #2442: "<class 'int'> returned a result with an error set" occurs when trying to cast a number to int.
**Environment:** IDLE 3.8.4

You can get some of this info from the text that pops up in the console when you run a pygame program.

- **Operating system** (e.g. Windows, Linux(Debian), Linux(Ubuntu), Mac): Windows 10 (build: 19042.685)
- **Python version** (e.g. 3.7.9, 3.8.5) : 3.8.4
- **SDL version** (e.g. SDL 2.0.12): unknown
- **PyGame version** (e.g. 2.0.0.dev10, 1.9.6): 2.0.1
- **Relevant hardware** (e.g. if reporting a bug about a controller, tell us the brand & name of it): n/a

**Current behavior:** The error: "SystemError: <class 'int'> returned a result with an error set" occurs when running my code, while I am trying to learn to use pygame. I understand that this is a potential sign of an implementation problem. I have sought help with this issue on reddit and the official python bug tracker, and was advised to come here.
Link: https://bugs.python.org/issue42879

Describe how the bug manifests.

**Expected behavior:**

No error to occur

**Screenshots**

Not applicable

**Steps to reproduce:**

The problem can be reproduced deterministically by simply running the code.

**Test code**

If possible add a simple test program that shows the problem described in this report.
```
# Display grid


import pygame, sys, random, datetime
from pygame.locals import *

# Initialize pygame
pygame.init()
#Create game window
windowSurface = pygame.display.set_mode((600,600), 0, 32)
pygame.display.set_caption('Moving colours')

WHITE = (255, 255, 255)

# Fill background
windowSurface.fill(WHITE)

# Set up parameters
pixelOffset = (400,400)
gridDisplaySize = (400,400)
minVal = 0
maxVal = 100

# Create sample grid
gridSize = (50,50)
grid = [[]]
for x in range (gridSize[0]):
    for y in range(gridSize[1]):
        #grid[x].append(random.randint(minVal,maxVal))  #Random values between min and max
        if x > 150 and x < 250 and y > 150 and y < 250:
            grid[x].append(100)  #Fill left
        else:
            grid[x].append(0)
    grid.append([])

# Writes the content of a 2d array to a pygame surface
def writeGridToSurface(surface, grid, gridSize, pixelOffset, gridDisplaySize, minVal, maxVal):
    if gridSize[0] > gridDisplaySize[0] or gridSize[1] > gridDisplaySize[1]:
        print("WARNING: The data being displayed requires more space. Some data points will not be shown.")

    # Get a pixel array of the surface.
    pixArray = pygame.PixelArray(surface)


    for x in range(pixelOffset[0],pixelOffset[0]+gridDisplaySize[0]):
        for y in range(pixelOffset[1],pixelOffset[1]+gridDisplaySize[1]):
            xNorm = x - pixelOffset[0]
            xNorm = xNorm / gridDisplaySize[0]
            xNorm = xNorm * gridSize[0]
            xNorm = int(xNorm)

            yNorm = y - pixelOffset[1]
            yNorm = yNorm / gridDisplaySize[1]
            yNorm = yNorm * gridSize[1]
            yNorm = int(yNorm)

            upscaledValue = int((grid[xNorm][yNorm] - minVal) *(255 / maxVal))
            
            pixArray[x][y] = (0, 0, upscaledValue)
            
    del pixArray

# Lets pixels flow to neighbours
# Params
# grid: the grid which will flow
# gridsize: a tuple of the x and y size of the grid
# velocity: the rate at which pixels transfer. Linear. 0 = no flow, 1 = instant equalisation
def iterateGridFlow(grid, gridSize, velocity):
    for x in range (gridSize[0]):
        for y in range(gridSize[1]):
            xDif = 0
            yDif = 0
            if x + 1 < gridSize[0]:
                xDif = grid[x][y] - grid[x+1][y]
            else:
                xDif = 0
            if y + 1 < gridSize[1]:
                yDif = grid[x][y] - grid[x][y+1]
            else:
                yDif = 0

            xFlow = xDif/2
            yFlow = yDif/2
            
            xDelta = xFlow * velocity
            yDelta = yFlow * velocity

            # X change
            if xDif != 0:
                grid[x+1][y] = grid[x+1][y] + xDelta
                grid[x][y] = grid[x][y] - xDelta

            # Y change
            if yDif != 0:
                grid[x][y+1] = grid[x][y+1] + yDelta
                grid[x][y] = grid[x][y] - yDelta
            

# Write grid to display
writeGridToSurface(windowSurface, grid, gridSize, pixelOffset, gridDisplaySize, minVal, maxVal)

# Draw the window onto the screen.
pygame.display.update()

updateTime = datetime.datetime.now()
count = 0

# Run the game loop.
while True:
    for event in pygame.event.get():
        if event.type == QUIT:
            pygame.quit()
            sys.exit()

    if datetime.datetime.now() > updateTime + datetime.timedelta(hours=0, minutes=0, seconds=0.1):
        iterateGridFlow(grid, gridSize, 0.1)
        writeGridToSurface(windowSurface, grid, gridSize, pixelOffset, gridDisplaySize, minVal, maxVal)
        pygame.display.update()
        updateTime = datetime.datetime.now()
        print(grid[0][0])

```

Stack trace below:

```
IndexError: array index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "V:\GitRepos\pydev\Projects\Crepper Simulation\Movement.py", line 100, in <module>
    writeGridToSurface(windowSurface, grid, gridSize, pixelOffset, gridDisplaySize, minVal, maxVal)
  File "V:\GitRepos\pydev\Projects\Crepper Simulation\Movement.py", line 50, in writeGridToSurface
    xNorm = int(xNorm)
SystemError: <class 'int'> returned a result with an error set
```

### PR DESCRIPTION
**Pull request by ankith26**
Hopefully fix #2442 
Since I am away from computer at the moment, I will test this one later.

### CODE REVIEW

**Comment by ankith26** [comment]
Finally got time to do local testing. And this PR works :)

**Review by Starbuck5 — APPROVED** [review]
Looks good!

**Review by zoldalma999 — APPROVED** [review]
👍

**Comment by ankith26** [comment]
CI restart....
I really want to close the issue that this PR addresses, so that pygame can proudly show off 1000 closed issues ;)
The closed issue count is at 999 now

**Pull request merged**
