### PR TITLE
WIP: MacOS clang failed to build the alphablit SSE stuff.

### PR DESCRIPTION
**Pull request by illume**
Related: 
- https://github.com/pygame/pygame/pull/1711
- https://github.com/pygame/pygame/pull/1715

### CODE REVIEW

**Comment by MyreMylar** [comment]
Curious to know what errors clang produced?

**Comment by illume** [comment]
It looks like the error is happening with SDL1 and clang.
```c
src_c/alphablit.c:1101:5: error: use of undeclared identifier '__m128i'
    __m128i src1, dst1, mm_alpha, mm_zero, mm_alpha2, multmask2_128;
    ^
...
```

I guess SDL2 includes the intrinsics properly or so.

**Comment by MyreMylar** [comment]
I feel like this define is slightly wrong for `alphablit.c` as it is not currently using any SSE4.2 intrinsic functions. Looking at this answer:

https://stackoverflow.com/questions/11228855/header-files-for-x86-simd-intrinsics

Perhaps it should it just be:

    #ifdef PG_ENABLE_ARM_NEON
        // sse2neon.h is from here: https://github.com/DLTcollab/sse2neon
        #include "include/sse2neon.h"
    #else 
        #include <immintrin.h>  // should pull in all supported intrinsic functions
    #endif /* PG_ENABLE_ARM_NEON */

I guess SDL1 just doesn't include the right intrinsic headers.

**Comment by illume** [comment]
The intrinsics header here is only required for SDL1+clang it seems (maybe only on macos... haven't tried linux+clang). We could try including this in src_c/include/pgplatform.h when using SDL1?

I should probably try and get a macosx robot going on travis ci again.

**Comment by illume** [comment]
There's a fix for this in https://github.com/pygame/pygame/pull/1832

**Pull request closed without merging**
