### PR TITLE
Surface.convert tests updated in surface_test.py

### PR DESCRIPTION
**Pull request by bwright8**
added test for Surface.convert() on a fresh clone

For #1795

### CODE REVIEW

**Review by MyreMylar — CHANGES_REQUESTED** [review]
I think the only thing not being tested is this part:

> The converted Surface will have no pixel alphas. They will be stripped if the original had them. See convert_alpha() for preserving or creating per-pixel alphas.

Which is the most interesting part to test at the moment because it currently behaves differently on SDL1 to SDL2 we believe.

With SDL1 we believe that the alpha 'losses' are set to 8 which then affects the rest of the blitting - but the blendmode/SRCALPHA flag is left intact. Meanwhile on SDL2 we believe that the blenmode/SRCALPHA flag is removed and the alpha losses left alone at 0. You can get the alpha losses using:

`surface.get_losses()[3]`

and the SRCALPHA flag using:

`surface.get_flags() & pygame.SRCALPHA`

AFAIK this hasn't been properly tested on all platforms yet so this test would be a good opportunity. To see if it currently does as work as we believe. You can branch to test only on SDL1/SDL2 with:

`if SDL1:` or `if not SDL1:`

**Comment by bwright8** [comment]
> I think the only thing not being tested is this part:
> 
> > The converted Surface will have no pixel alphas. They will be stripped if the original had them. See convert_alpha() for preserving or creating per-pixel alphas.
> 
> Which is the most interesting part to test at the moment because it currently behaves differently on SDL1 to SDL2 we believe.
> 
> With SDL1 we believe that the alpha 'losses' are set to 8 which then affects the rest of the blitting - but the blendmode/SRCALPHA flag is left intact. Meanwhile on SDL2 we believe that the blenmode/SRCALPHA flag is removed and the alpha losses left alone at 0. You can get the alpha losses using:
> 
> `surface.get_losses()[3]`
> 
> and the SRCALPHA flag using:
> 
> `surface.get_flags() & pygame.SRCALPHA`
> 
> AFAIK this hasn't been properly tested on all platforms yet so this test would be a good opportunity. To see if it currently does as work as we believe. You can branch to test only on SDL1/SDL2 with:
> 
> `if SDL1:` or `if not SDL1:`

thanks for the tips and patience :)

**Comment by illume** [comment]
@MyreMylar note there is a test in this PR with some alpha stuff https://github.com/pygame/pygame/pull/2340 Maybe we can add a skipif-sdl2 to the test_convert_get_alpha in #2340 and merge that? (Then keep the alpha functionality of convert separate from this PR, since it's not really clear yet?).

**Comment by MyreMylar** [comment]
@illume Could do, that too - though I guess we'd need to add the `get_losses()[3] == 8` part to it as well to finish off that test. 

I'll leave it up to you @bwright8 you can stop here and we'll fix up the other PR a little to cover the alpha blending behaviour, or you could look at that one too and try and roll it all into this PR if you like. Separating it out into a new `test_convert__alpha_stripping()` function with a skip decorator is a good idea too.

**Comment by illume** [comment]
OK... I'll merge this one in, and fix the other PR up with a skip for now.

Thanks @bwright8 :)

**Review by illume — APPROVED** [review]
👍

**Pull request merged**
