### PR TITLE
Update to pygame.image docs

### PR DESCRIPTION
**Pull request by ankith26**
This PR is related to #1732 
My first commit is fixing a small typo. 
I may make future commits in this PR to add more docs (or not, if it’s not required)

### CODE REVIEW

**Comment by ankith26** [comment]
I have noticed that the appveyor build is failing on python 2.7 and python 3.5. This is because twine 2.0.0 removed support for versions less than 3.6.

**Comment by ankith26** [comment]
I guess I have done all the required changes. If devs are happy with these, then this PR can be merged. Of course, I’m open to any other suggestions to change anything, or to revert any of the changes I made that are not good.

**Review by MyreMylar — APPROVED** [review]
Seems fine to me.

**Review by illume — APPROVED** [review]
👍

**Pull request merged**
