### PR TITLE
Adds a num_buttons parameter to mouse.get_pressed()

### PR DESCRIPTION
**Pull request by MyreMylar**
This is for smooth backwards compatibility with pygame 1 the parameter defaults to 3, but can also be set to 5 to support five button mice. Previously we were breaking compatibility by always returning five buttons.

Related to:
https://github.com/pygame/pygame/issues/1329

### CODE REVIEW

**Comment by ankith26** [comment]
This change is nice, it will make the function backwards compatible.

**Review by illume — APPROVED** [review]
👍

**Comment by illume** [comment]
Thinking about this from a game writers perspective... how do I use this function so it will work with different versions of pygame (at least pygame 1.9.6 and pygame 2)? Using `mouse.get_pressed()` with an argument will not raise an error on `pygame < 2.0.0.dev13`, so we are safe to pass in 5.

--

To use pygame.mouse.get_pressed(5) so it is compatible with old versions of pygame you can use some code like this:
```python
buttons = pygame.mouse.get_pressed(5)
buttons5 = buttons[:3] + (buttons[-2:] if len(buttons) == 5 else (False, False))
```
For mice without 5 buttons they will always be False.

**Comment by illume** [comment]
If SDL suddenly supports 6 button mice (strangely they do exist)... then having the type error will give users who want to support that a bit more trouble in the future. Can we remove the type error with an incorrect count?

Probably a `dict[button_num]-> pressed` would have been a better return type... but we have what we have.

**Comment by MyreMylar** [comment]
I guess the ValueError might give a few people problems but can they not just use `try: except:` blocks? For example in a hypothetical 6 button future, where they need to support 1+ versions of pygame something like:


```
try:
    buttons = pygame.get_pressed(num_buttons=6)
    if len(buttons != 6):  # Need this if you want to support pygame 1
         raise ValueError
except ValueError:
    try:
        buttons = pygame.get_pressed(num_buttons=5)
        if len(buttons != 5):  # Need this if you want to support pygame 1
            raise ValueError
    except:
        buttons = pygame.get_pressed()
```

And if you only want to support pygame 2+ with 6 or 5 button mice it would just be:

```
try:
    buttons = pygame.get_pressed(num_buttons=6)
except ValueError:
    buttons = pygame.get_pressed(num_buttons=5)
      
```
In which you could pad the tuple or do whatever else you need as necessary. The pygame 1+ version is a bit messy, but once you drop pygame 1 support it cleans up fairly nicely.

I feel like we should probably give clear feedback on what amount of buttons are _currently_ supported for most users and let the small minority of pygame library makers (people like me basically) who are going to manage different mouse button configurations over different versions of pygame figure that out.

I'm mostly thinking of people right now trying:

```
buttons = pygame.get_pressed(num_buttons=6)
```

With no ValueError it will just silently carry on and they might miss that their sixth button isn't getting recorded until some later point in the code.

**Pull request merged**
