### PR TITLE
Fix inconsistent-return-statement signaled by pylint

### PR DESCRIPTION
**Pull request by Pierre-Sassoulas**
Ie: Either all return statements in a function should return an
expression, or none of them should.

This make the fact that functions can return None more apparent.

### CODE REVIEW

**Review by ankith26 — APPROVED** [review]
This PR is making good code cleanups
Thanks :) 👍

**Comment by Pierre-Sassoulas** [comment]
I tried to understand and fix the problem with travis, but I think it's something wrong on the master branch. (The same problem appear on both my pull request). I'll rebase when master is fixed :)

**Comment by MyreMylar** [comment]
It looks like the recent `match_font()` changes don't work properly on mac/OSX with python 2.7 to me. I don't know exactly why they don't work as I don't have a mac.

These are the failing tests though:

```
======================================================================
FAIL: test_match_font_all_exist (pygame.tests.font_test.FontModuleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/tmp2fuh6uv6/lib/python2.7/site-packages/pygame/tests/font_test.py", line 113, in test_match_font_all_exist
    self.assertFalse(path is None)
AssertionError: True is not false
======================================================================
FAIL: test_match_font_bold (pygame.tests.font_test.FontModuleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/tmp2fuh6uv6/lib/python2.7/site-packages/pygame/tests/font_test.py", line 182, in test_match_font_bold
    self.assertTrue(any(pygame_font.match_font(font, bold=True) for font in fonts))
AssertionError: False is not true
======================================================================
FAIL: test_match_font_italic (pygame.tests.font_test.FontModuleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/tmp2fuh6uv6/lib/python2.7/site-packages/pygame/tests/font_test.py", line 189, in test_match_font_italic
    any(pygame_font.match_font(font, italic=True) for font in fonts)
AssertionError: False is not true
======================================================================
FAIL: test_match_font_name (pygame.tests.font_test.FontModuleTest)
that match_font accepts names of various types
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/tmp2fuh6uv6/lib/python2.7/site-packages/pygame/tests/font_test.py", line 126, in test_match_font_name
    self.assertFalse(font_path is None)
AssertionError: True is not false
----------------------------------------------------------------------

======================================================================
FAIL: test_match_font_all_exist (pygame.tests.ftfont_test.FtFontModuleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/tmp2fuh6uv6/lib/python2.7/site-packages/pygame/tests/font_test.py", line 113, in test_match_font_all_exist
    self.assertFalse(path is None)
AssertionError: True is not false
======================================================================
FAIL: test_match_font_bold (pygame.tests.ftfont_test.FtFontModuleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/tmp2fuh6uv6/lib/python2.7/site-packages/pygame/tests/font_test.py", line 182, in test_match_font_bold
    self.assertTrue(any(pygame_font.match_font(font, bold=True) for font in fonts))
AssertionError: False is not true
======================================================================
FAIL: test_match_font_italic (pygame.tests.ftfont_test.FtFontModuleTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/tmp2fuh6uv6/lib/python2.7/site-packages/pygame/tests/font_test.py", line 189, in test_match_font_italic
    any(pygame_font.match_font(font, italic=True) for font in fonts)
AssertionError: False is not true
======================================================================
FAIL: test_match_font_name (pygame.tests.ftfont_test.FtFontModuleTest)
that match_font accepts names of various types
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/tmp2fuh6uv6/lib/python2.7/site-packages/pygame/tests/font_test.py", line 126, in test_match_font_name
    self.assertFalse(font_path is None)
AssertionError: True is not false
----------------------------------------------------------------------
```

Which strongly suggests the bug has come from the changes to made to `match_font()` by @BastiHz as these are the only tests that call that function. The changes do work on every other configuration though. I guess if nobody has a build that can compile OSX with 2.7 we could just  break the `match_font()` function down into smaller steps and fire micro tests at the CI. Maybe @illume can run this config locally?

**Comment by BastiHz** [comment]
I don't own a mac either and don't know why theses tests are failing. It seemed fine when I submitted my pull request.  
If someone is going to repair `match_font()` I suggest doing the same with `SysFont()` because the for-loops in both functions look very similar.

**Comment by illume** [comment]
They're not failing locally on mac+python27, but I'll look into it though (Maybe it's a filesystem encoding difference issue).

**Comment by MyreMylar** [comment]
The failures this time seem to be a CI timeout for the mac build and a random failure to start on one of the windows builds. I don't think either are related to this PR.

**Comment by ankith26** [comment]
This PR is making good code cleanups. This PR is only making aesthetical changes, so it is safe to merge.
Thanks again :) 👍

**Pull request merged**
