### PR TITLE
manylinux: Upgrade to SDL2-2.0.22

### PR DESCRIPTION
**Pull request by illume**
SDL 2.0.22 release notes are here: https://github.com/libsdl-org/SDL/releases/tag/release-2.0.22

We have windows on 2.0.22 already... so to make it consistent with mac/linux we do this as well.

### CODE REVIEW

**Comment by illume** [comment]
These docker images are pushed.

**Comment by ankith26** [comment]
Downloaded wheels from CI of this PR, and it's still on SDL 2.0.20 somehow, and it's working well in my basic testing

**Comment by illume** [comment]
> Downloaded wheels from CI of this PR, and it's still on SDL 2.0.20 somehow, and it's working well in my basic testing

Oops. I guess these built before the docker image upload finished. Closed/reopened and I hope this time it works ok.

**Review by Starbuck5 — APPROVED** [review]
If Ankith is fine moving forward with this right now, so am I.

The actual diff in the PR is straightforward to approve.

**Comment by ankith26** [comment]
Well, I suppose we *could* wait for SDL 2.24.2 (on both windows and *nix) since that has a fix for the issue blocking the windows update, and also a workaround for my WSL issue. But if it's too much wait, then we can also release with 2.0.22

**Comment by Starbuck5** [comment]
Let's go to SDL 2.0.22, having the newer version will probably help other problems that we're not even aware of.

**Comment by illume** [comment]
> Let's go to SDL 2.0.22, having the newer version will probably help other problems that we're not even aware of.

Yeah, agreed. Merging this in, the appveyor failure is unrelated noise.

**Pull request merged**
